/**
 * This code was generated by Builder.io.
 */
import React from "react";

const CheckoutSection = () => {
  return (
    <section className="p-11 mt-10 w-full bg-white rounded-3xl max-w-[1252px] max-md:px-5 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-[64%] max-md:ml-0 max-md:w-full">
          <div className="flex flex-col items-start mt-1.5 w-full text-base leading-loose max-md:mt-10 max-md:max-w-full">
            <h2 className="text-4xl font-bold leading-none text-black">
              Оформление заказа
            </h2>
            <div className="flex overflow-hidden flex-wrap gap-3 self-stretch py-2 pr-20 pl-4 mt-8 w-full text-sm leading-loose bg-orange-50 rounded-xl max-md:pr-5 max-md:max-w-full">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/685fc6e3a0ec50fae55b8f1b507c2109bc04fbae1ec91a12ef55ab33944d3868?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                alt=""
                className="object-contain shrink-0 aspect-square w-[26px]"
              />
              <div className="flex gap-1 items-start my-auto">
                <span className="font-medium text-yellow-500">
                  Есть промокод?
                </span>
                <button className="font-semibold text-yellow-500">
                  Ввести промокод →
                </button>
              </div>
            </div>
            <h3 className="mt-8 text-2xl font-semibold leading-none text-black">
              Данные оплаты
            </h3>
            <form>
              <div className="mt-4 text-black">
                <label htmlFor="name" className="block">
                  ваше имя (необязательно)
                </label>
                <input
                  id="name"
                  type="text"
                  className="flex shrink-0 self-stretch mt-2 rounded-xl bg-slate-100 h-[50px] w-full max-md:max-w-full"
                />
              </div>
              <div className="mt-4 text-black">
                <label htmlFor="country" className="block">
                  страна/регион (необязательно)
                </label>
                <input
                  id="country"
                  type="text"
                  className="flex shrink-0 self-stretch mt-2 rounded-xl bg-slate-100 h-[50px] w-full max-md:max-w-full"
                />
              </div>
              <div className="flex mt-4 whitespace-nowrap">
                <label htmlFor="email" className="grow text-black">
                  email<span className="font-bold text-orange-600">*</span>
                </label>
              </div>
              <input
                id="email"
                type="email"
                required
                className="flex shrink-0 self-stretch mt-2 rounded-xl bg-slate-100 h-[50px] w-full max-md:max-w-full"
              />
            </form>
          </div>
        </div>
        <div className="flex flex-col ml-5 w-[36%] max-md:ml-0 max-md:w-full">
          <div className="flex overflow-hidden flex-col p-6 mx-auto w-full text-sm text-black rounded-3xl bg-slate-100 max-md:px-5 max-md:mt-10">
            <div className="flex gap-5 justify-between text-2xl font-semibold leading-none text-black whitespace-nowrap">
              <span>товар</span>
              <span className="text-right">итого</span>
            </div>
            <div className="flex shrink-0 mt-3 h-px bg-slate-200" />
            <div className="flex gap-5 justify-between mt-5">
              <div className="flex flex-col">
                <div className="leading-6">
                  Mortal Kombat 11 Ultimate PS4 & PS5
                </div>
                <div className="z-10 self-start mt-0 ml-12 font-bold leading-loose max-md:ml-2.5">
                  х 1
                </div>
              </div>
              <div className="self-start font-semibold leading-loose text-right">
                6 790 ₽
              </div>
            </div>
            <div className="flex shrink-0 mt-5 h-px bg-slate-200" />
            <div className="flex gap-5 justify-between mt-5 leading-loose">
              <span>итого</span>
              <span className="font-semibold text-right">6 790 ₽</span>
            </div>
            <div className="flex shrink-0 mt-5 h-px bg-slate-200" />
            <div className="flex gap-2 items-center self-start mt-8 leading-loose">
              <input
                type="radio"
                id="robokassa"
                name="payment"
                className="flex shrink-0 self-stretch my-auto w-5 h-5 border-purple-600 border-solid bg-neutral-100 border-[6px] rounded-[50px]"
              />
              <label htmlFor="robokassa" className="self-stretch my-auto">
                оплатить через сервис Robokassa
              </label>
            </div>
            <div className="flex gap-2 items-center self-start mt-5 leading-loose">
              <input
                type="radio"
                id="cryptocloud"
                name="payment"
                className="flex shrink-0 self-stretch my-auto w-5 h-5 bg-slate-200 rounded-[50px]"
              />
              <label htmlFor="cryptocloud" className="self-stretch my-auto">
                CryptoCloud Payment System
              </label>
            </div>
            <button className="overflow-hidden gap-2.5 self-stretch px-8 py-3 mt-8 text-base font-medium leading-loose text-center lowercase bg-purple-600 min-h-[50px] rounded-[50px] text-neutral-200 max-md:px-5">
              подтвердить заказ
            </button>
            <p className="mt-4 text-xs leading-5 underline opacity-40">
              Ваши личные данные будут использоваться для обработки ваших
              заказов, упрощения вашей работы с сайтом и для других целей,
              описанных в нашей{" "}
              <a
                href="https://psplusdev.ru/?page_id=3"
                className="text-black underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                политика конфиденциальности
              </a>
              .
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default CheckoutSection;
