/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer = () => {
  return (
    <footer className="flex overflow-hidden flex-col items-center self-stretch px-20 pb-10 mt-16 w-full bg-neutral-900 max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="flex shrink-0 max-w-full h-px bg-neutral-800 w-[1252px]" />
      <div className="flex flex-wrap gap-10 self-start mt-16 w-full max-w-[1186px] max-md:mt-10 max-md:max-w-full">
        <div className="flex flex-col self-start">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/6d641deacf194df02ed2065b19fdce97a031e3f2f70393d4fe04466b09343e57?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Company logo"
            className="object-contain max-w-full aspect-[3.72] w-[156px]"
          />
          <div className="mt-9 mr-7 text-2xl font-semibold leading-none text-neutral-200 max-md:mr-2.5">
            hello@playstationplus.store
          </div>
          <div className="mt-1 text-base font-medium leading-loose text-neutral-400">
            принимаем заявки с 11:00 до 21:00 (МСК)
          </div>
          <div className="flex gap-2 self-start mt-4">
            <a href="#" aria-label="Visit our social media page">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/9e6026c93497c05916de173ea3de67c0fbb215f5f28189918e1ffec1b564ccd3?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                alt=""
                className="object-contain shrink-0 aspect-square fill-zinc-800 w-[42px]"
              />
            </a>
            <a href="#" aria-label="Visit our social media page">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/fc98f7b2cc057874edd3a9f97cb549b5a21b0aff88f1a7c616164ae6c4b7012d?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                alt=""
                className="object-contain shrink-0 aspect-square w-[42px]"
              />
            </a>
          </div>
        </div>
        <nav className="flex-auto max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            <div className="flex flex-col w-[28%] max-md:ml-0 max-md:w-full">
              <div className="flex flex-col whitespace-nowrap max-md:mt-10">
                <h3 className="text-2xl font-semibold leading-none text-neutral-200">
                  магазин
                </h3>
                <ul className="flex flex-col self-start mt-5 text-sm font-medium leading-loose text-neutral-400">
                  <li>
                    <a href="#">каталог</a>
                  </li>
                  <li>
                    <a href="#">подписки</a>
                  </li>
                  <li>
                    <a href="#">скидки</a>
                  </li>
                </ul>
              </div>
            </div>
            <div className="flex flex-col ml-5 w-[73%] max-md:ml-0 max-md:w-full">
              <div className="flex flex-col grow max-md:mt-10">
                <h3 className="self-start text-2xl font-semibold leading-none text-neutral-200">
                  покупателям
                </h3>
                <ul className="flex flex-col mt-5 text-sm font-medium leading-loose text-neutral-400">
                  <li>
                    <a href="#">возвраты</a>
                  </li>
                  <li>
                    <a href="#">реквизиты</a>
                  </li>
                  <li>
                    <a href="#">политика конфиденциальности</a>
                  </li>
                  <li>
                    <a href="#">публичная оферта</a>
                  </li>
                  <li>
                    <a href="#">согласие на рекламную рассылку</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </nav>
      </div>
      <div className="flex shrink-0 mt-20 max-w-full h-px bg-neutral-800 w-[1252px] max-md:mt-10" />
      <div className="flex flex-wrap gap-5 justify-between mt-10 w-full max-w-[1252px] max-md:max-w-full">
        <div className="text-sm leading-loose text-neutral-400">
          © 2024, «GamePropaganda»
        </div>
        <div className="flex gap-6">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/011250b04b13b2ef1f7c84e2d6a809cc7c8dde8f41e194a7b23c330b5e9c31e7?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method"
            className="object-contain shrink-0 my-auto w-10 aspect-[2]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/f7556b439e5e01025691f932f8d4748eff67e0af690571dc8944a12ae1236b7e?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method"
            className="object-contain shrink-0 my-auto w-11 aspect-[2.2]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/b67aa76b490bdffb7fb01cb2fbc2e131623714cd0cb6ba7ada47d1df9664bb66?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method"
            className="object-contain shrink-0 my-auto w-12 aspect-[2.4]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/88d997ccae29e1cb0866254ca896c5130020af68198fadaec3b1617f5c779891?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method"
            className="object-contain shrink-0 aspect-[1.75] w-[42px]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/68859d7bafb41c57cdf7c859ca9fe1477d7d82a05ce41207c767e9f456be4271?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method"
            className="object-contain shrink-0 w-9 aspect-[1.5]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/7ea1a27541c08af93039573d88093b0a7be8179179262388c6e9e088d299d776?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method"
            className="object-contain shrink-0 aspect-[2.16] w-[52px]"
          />
        </div>
      </div>
    </footer>
  );
};

export default Footer;
