/**
 * This code was generated by Builder.io.
 */
import React from "react";

const GameSelection = () => {
  const games = [
    {
      title: "Star Wars Outlaws",
      price: "9 490 ₽",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/1db612b45ac8aea299ffa9be53fb7116a8c8f7f733e77088ceb12e4fe9ec6b16?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    },
    {
      title: "Death's Door",
      price: "2 690 ₽",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/4ee7bdf7c3ba4327304c3aa712708bba8a6abab3f2cfdb4e3be174ebd82e3ac3?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    },
    {
      title: "God of War Ragnarök",
      price: "9 490 ₽",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/5687194c40331e1940902bea5c033a5d6cbba8302e742a00fb92643f1eb10e11?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
      featured: true,
    },
    {
      title: "Doki Doki Literature Club Plus!",
      price: "1 290 ₽",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/3bb9524df9041f0cf641ecddfbde79500c6faaab6e786c55a20f9b32eb1e29a5?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    },
  ];

  return (
    <section className="mt-4 w-full max-w-[1252px] max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        {games.map((game, index) => (
          <div
            key={index}
            className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full"
          >
            <div
              className={`flex overflow-hidden flex-col items-start px-2 pt-2 pb-5 mx-auto w-full rounded-3xl bg-neutral-800 ${
                game.featured ? "border-2 border-lime-400 border-solid" : ""
              } max-md:mt-5`}
            >
              <div className="flex overflow-hidden flex-col items-center self-stretch rounded-xl aspect-square bg-zinc-800">
                <img
                  loading="lazy"
                  src={game.image}
                  alt={game.title}
                  className="object-contain w-full aspect-square"
                />
              </div>
              <h3 className="mt-3 text-base font-medium leading-loose whitespace-nowrap text-ellipsis text-neutral-200 max-md:ml-2">
                {game.title}
              </h3>
              <div className="gap-2.5 self-stretch mt-14 text-2xl font-semibold leading-none text-neutral-200 max-md:mt-10 max-md:ml-2">
                {game.price}
              </div>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
};

export default GameSelection;
