/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Navigation from "./Navigation";

const Header = () => {
  return (
    <header className="flex overflow-hidden flex-col items-center bg-neutral-900">
      <div className="flex overflow-hidden relative flex-col self-stretch pb-28 w-full min-h-[678px] max-md:pb-24 max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/a83171dee89d4592163a1563ace8d17d36bc78672839a0c450b183f2ab9af33c?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          alt=""
          className="object-cover absolute inset-0 size-full"
        />
        <div className="flex relative flex-col pt-4 w-full bg-neutral-900 bg-opacity-60 max-md:max-w-full">
          <div className="flex gap-5 justify-between items-center self-center w-full max-w-[1252px] max-md:max-w-full">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/f9a38d3a4f19b57febf8ce8025b0bfaf8bf8289a9832eb778169057739f3c0bb?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt="Company logo"
              className="object-contain shrink-0 self-stretch max-w-full aspect-[3.72] w-[156px]"
            />
            <Navigation />
            <div className="overflow-hidden gap-2.5 self-stretch px-5 pt-1.5 pb-2 font-medium text-center text-black bg-lime-400 rounded-[100px]">
              оформить подписку
            </div>
          </div>
          <div className="flex gap-2.5 self-stretch my-auto">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/67c7c8046a64f55a9a58df4d8198fb23627937744d63f32cbadf9d4b2308b99b?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt=""
              className="object-contain shrink-0 aspect-square w-[38px]"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/0ca4fb9d3bc9212f9b516d7b8a964484e6b1a75cb74907e73035c24ea81086ca?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt=""
              className="object-contain shrink-0 aspect-square w-[38px]"
            />
          </div>
        </div>
        <div className="flex mt-3.5 w-full bg-neutral-800 min-h-[1px] max-md:max-w-full" />
      </div>
    </header>
  );
};

export default Header;
