/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Hero = () => {
  return (
    <section className="flex relative flex-col items-start mt-44 mb-0 ml-24 max-w-full text-white w-[441px] max-md:mt-10 max-md:mb-2.5">
      <h1 className="self-stretch text-5xl font-black leading-[50px] max-md:max-w-full max-md:text-4xl max-md:leading-10">
        Создадим тебе личный турецкий аккаунт PSN
      </h1>
      <h2 className="mt-5 text-3xl tracking-normal">на твою почту</h2>
      <button className="overflow-hidden gap-2.5 self-stretch px-8 py-4 mt-16 text-base font-bold leading-tight text-black bg-lime-400 min-h-[50px] rounded-[1000px] max-md:px-5 max-md:mt-10">
        Купить аккаунт
      </button>
    </section>
  );
};

export default Hero;
