/**
 * This code was generated by Builder.io.
 */
import React from "react";

const PricingSection = () => {
  return (
    <section className="flex gap-5 max-md:flex-col">
      <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
        <div className="flex flex-col px-16 py-16 mx-auto w-full bg-zinc-900 rounded-[40px] max-md:px-5 max-md:mt-2 max-md:max-w-full">
          <h2 className="self-start text-3xl font-bold tracking-normal leading-tight text-white">
            Стоимость аккаунта
          </h2>
          <div className="p-9 mt-8 bg-white border border-solid border-white border-opacity-10 rounded-[30px] max-md:px-5 max-md:max-w-full">
            <div className="flex gap-5 max-md:flex-col">
              <div className="flex flex-col w-[76%] max-md:ml-0 max-md:w-full">
                <div className="flex flex-col w-full font-bold max-md:mt-10">
                  <div className="self-start text-6xl leading-none text-zinc-800 max-md:text-4xl">
                    450 ₽
                  </div>
                  <button className="overflow-hidden gap-2.5 self-stretch px-8 py-5 mt-11 text-base leading-none text-center text-white bg-rose-500 min-h-[60px] rounded-[1000px] max-md:px-5 max-md:mt-10">
                    Купить аккаунт
                  </button>
                </div>
              </div>
              <div className="flex flex-col ml-5 w-[24%] max-md:ml-0 max-md:w-full">
                <div className="flex flex-col grow max-md:mt-10">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/f823e99e36a94d81b8493d5155957251e1ab9d2c5672b4f807068040d06fdc3e?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                    alt=""
                    className="object-contain aspect-[1.3] w-[70px]"
                  />
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/894eb466e7c91d08b1549fe550e52614fa456f9e065c2c66d02c9fab40b819ed?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                    alt=""
                    className="object-contain mt-16 ml-5 aspect-square rounded-[43px] w-[50px] max-md:mt-10 max-md:ml-2.5"
                  />
                </div>
              </div>
            </div>
          </div>
          <p className="mt-5 text-base tracking-normal text-white max-md:mr-2.5 max-md:max-w-full">
            Или купи у нас подписку/любую игру и получи аккаунт бесплатно
          </p>
          <div className="flex gap-1 mt-5 max-w-full text-base font-bold leading-tight text-black w-[416px]">
            <button className="overflow-hidden gap-2.5 self-stretch px-8 py-4 bg-lime-400 min-h-[50px] rounded-[1000px] max-md:px-5">
              Купить подписку
            </button>
            <button className="overflow-hidden gap-2.5 self-stretch px-8 py-4 bg-lime-400 min-h-[50px] rounded-[1000px] max-md:px-5">
              Купить игру
            </button>
          </div>
        </div>
      </div>
      <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
        <div className="flex flex-col items-start px-16 py-16 mx-auto w-full text-xl tracking-normal leading-7 text-white border border-solid bg-zinc-900 border-zinc-800 rounded-[40px] max-md:px-5 max-md:mt-2 max-md:max-w-full">
          <h2 className="text-3xl font-bold leading-tight">Преимущества</h2>
          <ul className="list-none p-0">
            {[
              {
                img: "https://cdn.builder.io/api/v1/image/assets/TEMP/033625e38345dc9717e78bf47315f1372d26ffadea5363c51f65c754bdcc264d?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
                text: "Данные от аккаунты ты получишь от 2 двух до 4 часов после покупки",
              },
              {
                img: "https://cdn.builder.io/api/v1/image/assets/TEMP/3043f2477a72d61e1a6a617a02d0f53150e32370c0d634372a63fca38020a39a?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
                text: "Низкие цены на игры и подписку",
              },
              {
                img: "https://cdn.builder.io/api/v1/image/assets/TEMP/34e23c2563759241579a77dcc9ab9e867ec828120d1d7a39feab680a7a290ad9?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
                text: "Можно связать с российским аккаунтом",
              },
              {
                img: "https://cdn.builder.io/api/v1/image/assets/TEMP/714857ec2fa7fd90bca3a46d06fc9325ef8219033670383c6ed271bf63661649?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
                text: "После покупки ты можешь поменять все данные и подключить 2FA",
              },
            ].map((item, index) => (
              <li key={index} className="flex gap-6 mt-10">
                <img
                  loading="lazy"
                  src={item.img}
                  alt=""
                  className="object-contain shrink-0 self-start rounded-none aspect-square w-[50px]"
                />
                <div className={index === 2 ? "w-[270px]" : "flex-auto"}>
                  {item.text}
                </div>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </section>
  );
};

export default PricingSection;
