/**
 * This code was generated by Builder.io.
 */
import React from "react";

const TestimonialSection = () => {
  return (
    <section className="px-10 mt-36 w-full rounded-3xl bg-zinc-900 max-w-[1252px] max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full">
          <div className="flex flex-col items-start self-stretch my-auto w-full text-sm text-white max-md:mt-10">
            <h2 className="self-stretch text-3xl font-bold tracking-normal leading-none">
              Что говорят о нас
            </h2>
            <p className="mt-2 tracking-normal">
              Актуальные отзывы от клиентов
            </p>
            <div className="gap-2.5 self-stretch px-2.5 pt-1.5 pb-2 mt-14 font-semibold leading-none text-center bg-rose-500 rounded-[100px] max-md:mt-10">
              1500+ отзывов
            </div>
          </div>
        </div>
        <div className="flex flex-col ml-5 w-[57%] max-md:ml-0 max-md:w-full">
          <div className="flex flex-wrap grow gap-2 mt-0 max-md:mt-4 max-md:max-w-full">
            <div className="flex overflow-hidden relative flex-col grow shrink-0 items-start pt-44 basis-0 min-h-[258px] w-fit max-md:pt-24 max-md:max-w-full">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/1677d4d3997d88a24777e4b977699142aa628ecb1edf83c218420099ac3a3dd6?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                alt="Customer testimonial"
                className="object-cover absolute inset-0 size-full"
              />
              <div className="flex relative shrink-0 h-[81px] max-md:max-w-full" />
            </div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/e9cb99b448fd155ebfde34c7e0d10cf6e16a3e9ac979a21f12aa03437839fd01?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt=""
              className="object-contain shrink-0 self-end mt-48 aspect-square rounded-[73px] w-[26px] max-md:mt-10"
            />
          </div>
        </div>
        <div className="flex flex-col ml-5 w-[18%] max-md:ml-0 max-md:w-full">
          <button className="gap-2.5 self-stretch px-8 py-4 mt-10 w-full text-base font-bold leading-tight text-center text-black bg-lime-400 min-h-[50px] rounded-[100px] max-md:px-5">
            Cмотреть отзывы
          </button>
        </div>
      </div>
    </section>
  );
};

export default TestimonialSection;
