/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ActionButton({ children, primary }) {
  const baseClasses =
    "overflow-hidden gap-2.5 self-stretch py-4 px-7 min-h-[50px] rounded-[1000px] max-md:px-5";
  const primaryClasses = "bg-lime-400";
  const secondaryClasses = "bg-white";

  return (
    <button
      className={`${baseClasses} ${
        primary ? primaryClasses : secondaryClasses
      }`}
    >
      {children}
    </button>
  );
}

export default ActionButton;
