/**
 * This code was generated by Builder.io.
 */
import React from "react";

function FeatureCard({ icon, title, description }) {
  return (
    <div className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col tracking-normal text-white max-md:mt-10">
        <img
          loading="lazy"
          src={icon}
          alt=""
          className="object-contain w-11 aspect-[1.1]"
        />
        <div className="flex flex-col mt-6">
          <h3 className="text-xl font-bold">{title}</h3>
          <p className="mt-5 text-lg leading-7">{description}</p>
        </div>
      </div>
    </div>
  );
}

export default FeatureCard;
