/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Footer() {
  return (
    <footer className="flex overflow-hidden flex-col items-center self-stretch px-20 pb-10 mt-16 w-full bg-neutral-900 max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="flex shrink-0 max-w-full h-px bg-neutral-800 w-[1252px]" />
      <div className="flex flex-wrap gap-10 self-start mt-16 w-full max-w-[1186px] max-md:mt-10 max-md:max-w-full">
        <div className="flex flex-col self-start">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/fd6a46dd8ab0cdedf7cf7afc6b4ecd2f055cd29ccee94258dbdb801a7a64c716?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Company logo"
            className="object-contain max-w-full aspect-[3.72] w-[156px]"
          />
          <div className="mt-9 mr-7 text-2xl font-semibold leading-none text-neutral-200 max-md:mr-2.5">
            hello@playstationplus.store
          </div>
          <div className="mt-1 text-base font-medium leading-loose text-neutral-400">
            принимаем заявки с 11:00 до 21:00 (МСК)
          </div>
          <div className="flex gap-2 self-start mt-4">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/9e6026c93497c05916de173ea3de67c0fbb215f5f28189918e1ffec1b564ccd3?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt="Social media icon 1"
              className="object-contain shrink-0 aspect-square fill-zinc-800 w-[42px]"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/82bc375cf21f23dd196b5eb4ba10e90b3c643e0a58d181eacd952cd07d571335?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt="Social media icon 2"
              className="object-contain shrink-0 aspect-square w-[42px]"
            />
          </div>
        </div>
        <div className="flex-auto max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            <div className="flex flex-col w-[28%] max-md:ml-0 max-md:w-full">
              <div className="flex flex-col whitespace-nowrap max-md:mt-10">
                <h3 className="text-2xl font-semibold leading-none text-neutral-200">
                  магазин
                </h3>
                <nav className="flex flex-col self-start mt-5 text-sm font-medium leading-loose text-neutral-400">
                  <a href="#catalog">каталог</a>
                  <a href="#subscriptions" className="mt-3">
                    подписки
                  </a>
                  <a href="#discounts" className="mt-3">
                    скидки
                  </a>
                </nav>
              </div>
            </div>
            <div className="flex flex-col ml-5 w-[73%] max-md:ml-0 max-md:w-full">
              <div className="flex flex-col grow max-md:mt-10">
                <h3 className="self-start text-2xl font-semibold leading-none text-neutral-200">
                  покупателям
                </h3>
                <nav className="flex flex-col mt-5 text-sm font-medium leading-loose text-neutral-400">
                  <a href="#returns">возвраты</a>
                  <a href="#requisites" className="mt-3">
                    реквизиты
                  </a>
                  <a href="#privacy-policy" className="mt-3">
                    политика конфиденциальности
                  </a>
                  <a href="#public-offer" className="mt-3">
                    публичная оферта
                  </a>
                  <a href="#advertising-consent" className="mt-3">
                    согласие на рекламную рассылку
                  </a>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex shrink-0 mt-20 max-w-full h-px bg-neutral-800 w-[1252px] max-md:mt-10" />
      <div className="flex flex-wrap gap-5 justify-between mt-10 w-full max-w-[1252px] max-md:max-w-full">
        <div className="text-sm leading-loose text-neutral-400">
          © 2024, «GamePropaganda»
        </div>
        <div className="flex gap-6">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/f5455ccbb330084f7b0cb574a8e0b68afb0d5f4dc38bf9e76ff0f76a9d99766d?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method 1"
            className="object-contain shrink-0 my-auto w-10 aspect-[2]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/91a62148d22cbd713bab3bef710c79f2d9e5f1354af94fba53d5e37119d8cafa?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method 2"
            className="object-contain shrink-0 my-auto w-11 aspect-[2.2]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/4b2a6c59f7e94330b8796e7b53253ded8ed6451821221f3aa480848ca9495e92?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method 3"
            className="object-contain shrink-0 my-auto w-12 aspect-[2.4]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/0850381c6f3b98698ad95be445de09b1a538bda359412ce87b5f6129b012c7d7?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method 4"
            className="object-contain shrink-0 aspect-[1.75] w-[42px]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/1e4338052ad996d28ca75471bc3dd46ade0110f9cb60e0e412463b5d2e367c35?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method 5"
            className="object-contain shrink-0 w-9 aspect-[1.5]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/b0490cff0979d7b0b3352bdee4e8571375bd5ab6c186abbd0c2a1aa3953b315d?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method 6"
            className="object-contain shrink-0 aspect-[2.16] w-[52px]"
          />
        </div>
      </div>
    </footer>
  );
}

export default Footer;
