/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FeatureCard from "./FeatureCard";

const features = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/4b40e891166fb4a0f2451eaee884a60c5cb22d2d33f6251791ece79e2f7bce91?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Многопользовательский режим",
    description: "Включает сетевой многопользовательский режим на консоли",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/7175530ce9243eb635019cfcd733e568ab4ed484e0723d182cbf3fddcfdb8836?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Загружайте консольные и PC игры",
    description:
      "Загрузите и играйте на своей консоли или компьютере WIndows c помощью Ultimate",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/48a9a1d4e8cabc1c2608ac037a2f1c080b678a40de8c1122926fc7d709dabc16?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "EA Play",
    description:
      "Членство EA Play включено в Ultimate без дополнительной платы",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/c28bc345dc6fd7c0f97ec3b0001f53679b0818a2b8cd1f8b25522ed84c272d39?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Преимущества",
    description:
      "Наслаждайтесь бесплатными привилегиями, такими как внутриигровые дополнения и партнерские предложения",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/8cd16ecf156250d0b5420c3d1b4379f7e6926381f8d722820d74018ccd5cb35c?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Новые игры",
    description:
      "Новые игры добавляются постоянно, включая игры, добавленные в день выпуска",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/2f6659a37f0a7bf60bce908abe38ea1786d155721e009c6a3671d345e1d0d81f?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Скидки",
    description: "Воспользуйтесь специальными скидками и предложениями",
  },
];

function GamePassInfo() {
  return (
    <section className="flex relative flex-col justify-center items-center px-20 py-16 mt-5 w-full rounded-none max-w-[1400px] min-h-[845px] max-md:px-5 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/55f9339a5cfba309576117f29f40986e6b33b448fa5481630988ce0d4f85bae2?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        alt=""
        className="object-cover absolute inset-0 size-full"
      />
      <div className="flex relative flex-col w-full max-w-[1141px] max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/4952c6c3baa3d7d67c0d419d5adb6141f8961111efe8fbff801d90b4074db5f7?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          alt="Game Pass logo"
          className="object-contain self-center rounded-none aspect-square w-[50px]"
        />
        <h2 className="self-center mt-2.5 text-5xl font-bold leading-none text-center text-white max-md:max-w-full">
          Что такое Game Pass?
        </h2>
        <div className="mt-10 max-md:max-w-full">
          <div className="flex flex-wrap gap-5 justify-center">
            {features.map((feature, index) => (
              <FeatureCard key={index} {...feature} />
            ))}
          </div>
        </div>
        <button className="overflow-hidden px-16 py-6 mt-12 text-base font-bold leading-none text-center text-black bg-lime-400 rounded-[1000px] max-md:px-5 max-md:mt-10">
          Оформить подписку
        </button>
      </div>
    </section>
  );
}

export default GamePassInfo;
