/**
 * This code was generated by Builder.io.
 */
import React from "react";

function GameCard({ imageSrc, title, price }) {
  return (
    <div className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full">
      <div className="flex overflow-hidden flex-col items-start px-2 pt-2 pb-5 mx-auto w-full rounded-3xl bg-neutral-800 max-md:mt-5">
        <div className="flex overflow-hidden flex-col items-center self-stretch rounded-xl aspect-square bg-zinc-800">
          <img
            loading="lazy"
            src={imageSrc}
            alt={title}
            className="object-contain w-full aspect-square"
          />
        </div>
        <div className="mt-3 text-base font-medium leading-loose text-ellipsis text-neutral-200 max-md:ml-2">
          {title}
        </div>
        <div className="gap-2.5 self-stretch mt-14 text-2xl font-semibold leading-none text-neutral-200 max-md:mt-10 max-md:ml-2">
          {price}
        </div>
      </div>
    </div>
  );
}

export default GameCard;
