/**
 * This code was generated by Builder.io.
 */
import React from "react";
import GameCard from "./GameCard";

const games = [
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/57bca8200e725ff235d2d1f4db4fe215498279dbc8c03a1121ec674f6dec2041?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Isonzo",
    price: "9 490 ₽",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/d81d9c073bbff9bce7cb5d0c5ff3550aa616b88746a645c74c013dd9b601707f?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Lords of the Fallen",
    price: "2 690 ₽",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/abc3fe9e346616c043079a8d0d74d1349f38bdde01e88d9ebf7baf1edc303ee7?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Nickelodeon All-Star Brawl 2",
    price: "9 490 ₽",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/0bcf4b8111b5a5882d288ddba646bff1a9b6cb338b085a3d601494048e1478dd?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Tchia",
    price: "1 290 ₽",
  },
];

function GameSection() {
  return (
    <section className="mt-24 w-full max-w-[1252px] max-md:max-w-full">
      <h2 className="mt-24 text-5xl font-bold tracking-tight leading-10 text-center text-white max-md:mt-10 max-md:max-w-full max-md:text-4xl max-md:leading-10">
        Отправляйся навстречу со своей <br /> новой любимой игрой
      </h2>
      <div className="flex gap-5 max-md:flex-col">
        {games.map((game, index) => (
          <GameCard key={index} {...game} />
        ))}
      </div>
      <button className="overflow-hidden gap-2.5 self-stretch px-5 py-3.5 mt-10 max-w-full text-sm font-medium leading-loose text-center text-white border border-white border-solid min-h-[50px] rounded-[100px] w-[346px]">
        Показать еще
      </button>
    </section>
  );
}

export default GameSection;
