/**
 * This code was generated by Builder.io.
 */
import React from "react";
import GameCard from "./GameCard";

const games = [
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/115905ac2c4b5ad37e669cf3884dc094fd28645f242f0af41d786c1f556fe4c3?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Sea of Stars",
    price: "9 490 ₽",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/6e1abb080da8866137ec8b85a8ceff99a396ed0fcb85ac37c9d95d7bc84b98a2?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Spiritfarer®: Farewell Edition",
    price: "2 690 ₽",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/c1df88eccda9e44ad1565c3785f9b1bea62d1c9a50f94392ffc2003a257d93f1?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Lightyear Frontier",
    price: "9 490 ₽",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/24b7e5d46b76727d18c48f42104f45829a019248a7c9710f0e7b85e46b1ba3e0?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "GRIS",
    price: "1 290 ₽",
  },
];

function GameCatalog() {
  return (
    <section className="mt-24 w-full max-w-[1252px] max-md:max-w-full">
      <h2 className="text-5xl font-bold tracking-tight leading-none text-center text-white max-md:text-4xl">
        Каталог игр
      </h2>
      <div className="flex flex-col items-center self-stretch pl-20 mt-10 w-full max-md:pl-5 max-md:max-w-full">
        <div className="self-start w-full max-w-[1252px] max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            {games.map((game, index) => (
              <GameCard key={index} {...game} />
            ))}
          </div>
        </div>
        <button className="overflow-hidden gap-2.5 self-stretch px-5 py-3.5 mt-10 max-w-full text-sm font-medium leading-loose text-center text-white border border-white border-solid min-h-[50px] rounded-[100px] w-[346px]">
          Показать еще
        </button>
      </div>
    </section>
  );
}

export default GameCatalog;
