/**
 * This code was generated by Builder.io.
 */
import React from "react";
import PlanCard from "./PlanCard";

const plans = [
  {
    title: "ДЛЯ ПК",
    description: "Подписка действует только для ПК",
    features: [
      "Многопользовательский онлайн-режим",
      "Сотни высококачественных игр на ПК",
      "Предложения и скидки для участников",
      "Новые игры в первый день выхода",
      "Подписка EA Play",
    ],
    price: "от 1 190 ₽",
  },
  {
    title: "ULTIMATE",
    description: "Действует для ПК и Консолей",
    features: [
      "Многопользовательский онлайн-режим",
      "Сотни высококачественных игр на консоли, ПК и в облаке",
      "Предложения и скидки для участников",
      "Новые игры в первый день выхода",
      "Подписка EA Play",
    ],
    price: "от 1 790 ₽",
  },
  {
    title: "CORE",
    description: "Подписка действует только для Консолей",
    features: [
      "Многопользовательский онлайн-режим",
      "Каталог более 25 качественных игр для консолей",
      "Предложения и скидки для участников",
    ],
    price: "от 1 290 ₽",
  },
];

function GamePassPlans() {
  return (
    <section className="mt-32 w-full max-w-[1251px] max-md:mt-10 max-md:max-w-full">
      <h2 className="text-5xl font-bold leading-none text-center text-white max-md:max-w-full max-md:text-4xl">
        Что входит в подписку
      </h2>
      <p className="mt-5 text-xl leading-8 text-center text-white w-[636px] max-md:max-w-full">
        Открой для себя возможности PS+ сравнив тарифы и выбрав оптимальное
        решение по цене и преимуществам
      </p>
      <div className="flex gap-5 mt-12 max-md:flex-col max-md:mt-10">
        {plans.map((plan, index) => (
          <PlanCard key={index} {...plan} />
        ))}
      </div>
    </section>
  );
}

export default GamePassPlans;
