/**
 * This code was generated by Builder.io.
 */
import React from "react";

const guarantees = [
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/d51801a85fedc141bf9ac8216e3661b97e2ecf50307a36add143c42f124a6bf8?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/3f8f972e12d5c00e1e8f38c09f0a4af2a2249172c107e0efbd78442fda92e97f?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/9a651022b0209471e213b1b3d6d20c5f3e2364e5573a9e82e9cce2d4f01b60aa?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/6b540ee7c4f5a870e60066f590d80e7e32a13e4d3fefc16095fbaaa9f20df947?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/17a43e12c21d8fccf1f672bc2e103d136d49abd346bc58a589e5287801ec9a36?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
];

function Guarantees() {
  return (
    <section className="flex flex-wrap gap-4 self-end mt-32 w-full max-w-[1300px] max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-col grow shrink-0 items-center self-start basis-0 w-fit max-md:max-w-full">
        <h2 className="text-5xl font-bold leading-none text-center text-white max-md:text-4xl">
          Наши гарантии
        </h2>
        <div className="self-stretch mt-11 max-md:mt-10 max-md:max-w-full">
          <div className="flex gap-5 flex-wrap justify-center">
            {guarantees.map((guarantee, index) => (
              <img
                key={index}
                loading="lazy"
                src={guarantee.imageSrc}
                alt={`Guarantee ${index + 1}`}
                className="object-contain grow w-full rounded-none aspect-[2.34] max-md:mt-4"
              />
            ))}
          </div>
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/e6bac581e5439d7935af4edc6a56f215ffff0269871db0cace7cb17eb861daa8?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          alt="Decoration"
          className="object-contain shrink-0 max-w-full aspect-[0.27] w-[123px]"
        />
      </div>
    </section>
  );
}

export default Guarantees;
