/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ActionButton from "./ActionButton";

function Hero() {
  return (
    <section className="flex flex-col items-center self-stretch px-20 pb-24 mt-28 w-full rounded-[40px] max-md:px-5 max-md:pb-24 max-md:mt-10 max-md:max-w-full">
      <div className="flex z-10 flex-col mt-0 mb-0 max-w-full w-[904px] max-md:mb-2.5">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/4ba87590434e0ec3a36925b428a1cfb3c6a1928e4003db02eee59100f4a7355a?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          alt="Xbox logo"
          className="object-contain self-center max-w-full rounded-none aspect-square w-[153px]"
        />
        <div className="flex flex-col items-center mt-8 text-center text-white max-md:max-w-full">
          <h1 className="text-6xl font-black leading-[61px] max-md:max-w-full max-md:text-4xl max-md:leading-10">
            Покупай игры и подписки для Xbox
          </h1>
          <p className="mt-8 text-xl tracking-normal w-[406px]">
            Оформи подписку Game Pass на свою почту без VPN и заморочек
          </p>
        </div>
        <div className="flex gap-2.5 self-center mt-12 max-w-full text-base font-bold leading-tight text-center text-black w-[422px] max-md:mt-10">
          <ActionButton primary>Оформить подписку</ActionButton>
          <ActionButton>Купить игру</ActionButton>
        </div>
        <div className="flex flex-wrap gap-10 items-center mt-28 mr-7 ml-7 max-md:mt-10 max-md:mr-2.5 max-md:max-w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/a0766a7cf17d7de23bdccb99795a327d8d4b52181ba804a1ec4abcb31bc771af?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Partner logo 1"
            className="object-contain shrink-0 self-stretch my-auto aspect-[5.49] w-[187px]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/28c8c025f32c1eb6684210a549f7d370a03f3852696717fd5274bd9869cac10d?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Partner logo 2"
            className="object-contain shrink-0 self-stretch my-auto aspect-[6.8] w-[163px]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/2711ca3a36f75477f4dfc1b97886e1f76920a535730e0887d19876c4a22ea9b0?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Partner logo 3"
            className="object-contain shrink-0 self-stretch my-auto aspect-[5.24] w-[178px]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/f9db75fd6da0e0f5e82fd7b41e8c4535a42746054d4cac2047e555919a478778?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Partner logo 4"
            className="object-contain shrink-0 self-stretch my-auto aspect-[5.08] w-[173px]"
          />
        </div>
      </div>
    </section>
  );
}

export default Hero;
