/**
 * This code was generated by Builder.io.
 */
import React from "react";
import StepCard from "./StepCard";

const steps = [
  {
    number: 1,
    title: "Выбери товар",
    description:
      "Выбери любой товар на сайте, будь то подписка, игра, дополнение или игровая валюта.",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/314562e967139ff06b628f5c8becdb267b62f9ff513e2cf5b17a1b9a99c781af?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    number: 2,
    title: "Авторизируйся",
    description:
      "Зарегистрируйся в личном кабинете за пару кликов, чтобы экономить время, для следующих покупок.",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/0bccbd02525d96c4458f78b643241915002387971dc15264160cd4d7df3d79ef?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    number: 3,
    title: "Оплати",
    description:
      "Оплати выбранные товары одним из удобных тебе способов: Visa, МИР, Яндекс, Мастеркард, МТС, СБП.",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/dc3506f2bd2b6002e6ddec5c7cd8b609e67812b979edb1cf22e5e0e86e95f593?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    number: 4,
    title: "Перейди",
    description:
      "Переходи в нашего бота после покупки для уточнения деталей твоего заказа.",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/aa20a1e5a2f5040ee95b9d3a3db957093193a9d3e7318c896c589574fe28afdf?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    number: 5,
    title: "Напиши",
    description:
      "Передай данные твоего логина и пароля от аккаунта или почту на которую нужно создать новый аккаунт нашему оператору.",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/fa958f71f4eac576645df632cdff71d97e1159b7a8546bf088d719c9e6524808?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    number: 6,
    title: "Играй",
    description:
      "Наслаждайся купленной игрой. И не забывай что наше сообщество всегда подскажет тебе самые лушие цены на твои любимые игры.",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/f5ea57c12b7c68abf2ce9dc35765f33dbcd1ca0d82f25516f97d83e26abbcb3e?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
];

function HowItWorks() {
  return (
    <section className="mt-24 max-w-[1015px]">
      <h2 className="text-5xl font-bold leading-none text-center text-white max-md:mt-10 max-md:max-w-full max-md:text-4xl">
        Как это работает?
      </h2>
      <div className="flex flex-wrap gap-5 justify-between mt-10 w-full max-md:max-w-full">
        {steps.map((step, index) => (
          <StepCard key={index} {...step} />
        ))}
      </div>
    </section>
  );
}

export default HowItWorks;
