/**
 * This code was generated by Builder.io.
 */
import React from "react";
import GameCard from "./GameCard";

const newGames = [
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/bc88685766269c987f7ab7017179a083fb77d6927c71157c9cb5f9e74c92bfef?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Call of Duty®: Modern Warfare® III - Cross-Gen Bundle",
    price: "Играть бесплатно",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/9530c06eb60e466c34a6bb657d1347ff1a6500ca663af518f5d60642c9e50b7b?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Flock",
    price: "Играть бесплатно",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/77bcc4aae011918e206cff0203a46b6da996edcbc3cedb4fd6460acddbb01b2a?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Dungeons Of Hinterberg",
    price: "Играть бесплатно",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/bae6fbd92a99550c211d75dbda88b40484da69cfb9f418892d70c7004292bc7a?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Kunitsu-Gami: Path of the Goddess",
    price: "Играть бесплатно",
  },
];

function NewGames() {
  return (
    <section className="mt-32 max-md:mt-10">
      <h2 className="text-5xl font-bold leading-none text-center text-white max-md:max-w-full max-md:text-4xl">
        Новые игры в игровом каталоге
      </h2>
      <p className="mt-5 text-xl leading-8 text-center text-white w-[636px] max-md:max-w-full">
        Играй в эти игры бесплатно прямо сейчас. Эти игры входят <br />в
        следующие типы подписок:
      </p>
      <div className="flex flex-wrap gap-5 mt-10 max-w-full text-base font-bold text-center text-black tracking-[3.2px] w-[706px]">
        <span className="px-16 py-1 bg-white rounded-lg max-md:px-5">
          ДЛЯ ПК
        </span>
        <span className="px-16 py-1 whitespace-nowrap bg-white rounded-lg max-md:px-5">
          ULTIMATE
        </span>
        <span className="px-16 py-1 whitespace-nowrap bg-white rounded-lg max-md:px-5">
          CORE
        </span>
      </div>
      <div className="self-start mt-10 w-full max-w-[1252px] max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          {newGames.map((game, index) => (
            <GameCard key={index} {...game} />
          ))}
        </div>
      </div>
      <button className="overflow-hidden gap-2.5 self-stretch px-5 py-3.5 mt-10 max-w-full text-sm font-medium leading-loose text-center text-white border border-white border-solid min-h-[50px] rounded-[100px] w-[346px]">
        Смотреть все игры
      </button>
    </section>
  );
}

export default NewGames;
