/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Newsletter() {
  return (
    <section className="mt-5 w-full max-w-[1252px] max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
          <div className="flex flex-col items-start pt-8 pr-20 pb-12 pl-10 mx-auto w-full font-bold rounded-3xl bg-zinc-900 max-md:px-5 max-md:mt-5 max-md:max-w-full">
            <h3 className="text-xl tracking-normal leading-tight text-white">
              Подпишись на нашу рассылку
            </h3>
            <p className="mt-2 text-sm tracking-normal text-white w-[360px]">
              Отправляем скидки на любимые игры, акции и специальные предложения
            </p>
            <form className="flex gap-2.5 mt-6 max-w-full text-base leading-tight whitespace-nowrap w-[408px]">
              <input
                type="email"
                placeholder="Email"
                aria-label="Email для подписки"
                className="overflow-hidden gap-2.5 self-stretch py-4 pr-40 bg-white min-h-[50px] rounded-[100px] text-stone-900"
              />
              <button
                type="submit"
                className="gap-2.5 self-stretch px-8 py-4 text-center text-black bg-lime-400 min-h-[50px] rounded-[100px] max-md:px-5"
              >
                подписаться
              </button>
            </form>
          </div>
        </div>
        <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
          <div className="flex flex-col items-start pt-8 pr-20 pb-12 pl-10 mx-auto w-full rounded-3xl bg-zinc-900 max-md:px-5 max-md:mt-5 max-md:max-w-full">
            <h3 className="text-xl font-bold tracking-normal leading-tight text-white">
              Подпишись на наш Telegram-канал
            </h3>
            <p className="mt-2 text-sm tracking-normal text-white">
              Постим самые интересные новости первыми
            </p>
            <div className="flex gap-2.5 mt-10">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/22b7c55a44d6c226aa219e51fefd705f1b432ae3e4ce3747b94144fc13c37bf7?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                alt="Telegram channel QR code"
                className="object-contain shrink-0 max-w-full rounded-none aspect-[3.4] w-[170px]"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/66214c20cd25892d6d28cd63e7ef92765275b98973856fa6a5a67dee4a56c24c?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                alt="Telegram channel link"
                className="object-contain shrink-0 max-w-full rounded-none aspect-[3.4] w-[170px]"
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

export default Newsletter;
