/**
 * This code was generated by Builder.io.
 */
import React from "react";

function PlanCard({ title, description, features, price }) {
  return (
    <div className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow items-start pt-10 pr-20 pb-7 pl-8 w-full tracking-normal text-white bg-green-700 rounded-3xl max-md:px-5 max-md:mt-8">
        <h3 className="text-3xl font-bold leading-none">{title}</h3>
        <p className="mt-2.5 text-sm">{description}</p>
      </div>
      <div className="flex flex-col items-start px-8 pt-6 pb-9 mx-auto w-full font-bold text-white rounded-3xl bg-zinc-900 max-md:px-5 max-md:mt-8">
        <ul className="flex gap-5 text-lg">
          {features.map((feature, index) => (
            <li key={index} className="flex gap-5 mt-5 leading-7">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/45043092b8cd155b10431494578f289fcf7eea18cde5af3265643c9576e8b49f?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                alt=""
                className="object-contain shrink-0 self-start w-6 aspect-[0.07] max-md:hidden"
              />
              <span>{feature}</span>
            </li>
          ))}
        </ul>
        <div className="mt-48 ml-2.5 text-4xl tracking-tight leading-none max-md:mt-10">
          {price}
        </div>
        <button className="overflow-hidden gap-2.5 self-stretch px-5 py-3.5 mt-5 ml-2.5 text-base leading-none text-center text-black bg-lime-400 min-h-[50px] rounded-[100px]">
          Добавить в корзину
        </button>
      </div>
    </div>
  );
}

export default PlanCard;
