/**
 * This code was generated by Builder.io.
 */
import React from "react";
import GameCard from "./GameCard";

const releaseGames = [
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/893ba2c523a7ae843a6f807a8561f55e5a0d703befd8506c5f534366862d1157?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Senua's Saga: Hellblade II",
    price: "Купить игру с подпиской",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/3281bbc65174fe44bc9d918603d389ebc4dc9ef209ff23a5a8a8cd5a747e7478?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Indiana Jones and the Great Circle",
    price: "Купить игру с подпиской",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/ea82c4f3b057ca0c2ab9d0e480c14d0ee8e37ed3341d328928f030d8fff9d772?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
    price: "Купить игру с подпиской",
  },
];

function ReleaseGames() {
  return (
    <section className="mt-24 max-md:mt-10">
      <h2 className="text-5xl font-bold leading-none text-center text-white max-md:max-w-full max-md:text-4xl">
        Играй в день релиза
      </h2>
      <p className="mt-5 text-xl leading-8 text-center text-white w-[974px] max-md:max-w-full">
        Наслаждайся невероятными новыми играми от Xbox Game Studios с первого же
        дня, а также культовыми франшизами от Bethesda Softworks, инди-играми,
        блокбастерами и многим другим. Эти игры будут доступны в день релиза для
        следующих подписок:
      </p>
      <div className="flex gap-5 mt-10 max-w-full text-base font-bold text-center text-black tracking-[3.2px] w-[464px]">
        <span className="px-16 py-1 bg-white rounded-lg max-md:px-5">
          ДЛЯ ПК
        </span>
        <span className="px-16 py-1 whitespace-nowrap bg-white rounded-lg max-md:px-5">
          ULTIMATE
        </span>
      </div>
      <div className="mt-10 max-w-full w-[934px]">
        <div className="flex gap-5 max-md:flex-col">
          {releaseGames.map((game, index) => (
            <GameCard key={index} {...game} />
          ))}
        </div>
      </div>
    </section>
  );
}

export default ReleaseGames;
