/**
 * This code was generated by Builder.io.
 */
import React from "react";

function TopUpCard({ amount, price, special }) {
  return (
    <div className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full">
      <div
        className={`flex flex-col items-center px-0.5 pt-8 ${
          special ? "" : "mt-12"
        } font-bold text-center rounded-xl max-md:mt-10`}
      >
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/89c3ff6db9d582360f2174d738a32504559834f68ec9c47e6e3485d4ada89064?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          alt="PlayStation logo"
          className="object-contain w-24 aspect-[3]"
        />
        <div className="z-10 mt-14 text-2xl tracking-normal text-white max-md:mt-10">
          {amount}
        </div>
        <div className="flex overflow-hidden relative flex-col self-stretch px-12 pt-5 pb-11 w-full aspect-[1.254] max-md:px-5">
          <img
            loading="lazy"
            src={`http://b.io/ext_${special ? "48" : "46"}-`}
            alt=""
            className="object-cover absolute inset-0 size-full"
          />
          <div className="relative self-center text-6xl tracking-tight leading-none text-white max-md:text-4xl">
            {price}
          </div>
          <button className="overflow-hidden relative gap-2.5 self-stretch px-8 py-4 mt-16 text-base leading-tight text-black whitespace-nowrap bg-white min-h-[50px] rounded-[1000px] max-md:px-5 max-md:mt-10">
            {special ? "Написать нам" : "Купить"}
          </button>
        </div>
      </div>
    </div>
  );
}

export default TopUpCard;
