/**
 * This code was generated by Builder.io.
 */
import React from "react";

const accountLevels = [
  "Новобранец",
  "Странник",
  "Воин",
  "Рыцарь",
  "Чародей",
  "Магистр",
  "Владыка",
  "Архимаг",
  "Дракон",
  "Повелитель",
];

function AccountLevelsSection() {
  return (
    <section className="mt-10">
      <div className="flex shrink-0 w-0.5 h-[99px]" />
      <h2 className="mt-5 text-6xl font-light text-center uppercase leading-[60px] w-[522px] max-md:text-4xl max-md:leading-10">
        Уровни аккаунтов
      </h2>
      <p className="mt-5 text-base text-center text-white">
        Пройди путь от новобранца до повелителя
      </p>
      <div className="flex flex-wrap gap-1.5 justify-center items-center mt-16 text-sm font-bold leading-none text-center text-white whitespace-nowrap max-md:mt-10 max-md:max-w-full">
        {accountLevels.map((level, index) => (
          <div
            key={level}
            className={`overflow-hidden gap-2.5 self-stretch py-3 my-auto min-h-[40px] rounded-[1000px] w-[120px] ${
              index === 0 ? "bg-white text-neutral-900" : "bg-zinc-800"
            }`}
          >
            {level}
          </div>
        ))}
      </div>
    </section>
  );
}

export default AccountLevelsSection;
