/**
 * This code was generated by Builder.io.
 */
import React from "react";

function CallToActionSection() {
  return (
    <section className="flex relative flex-col justify-center items-start py-4 mt-24 w-full max-w-[999px] min-h-[470px] max-md:mt-10 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/99f0624433f4839904c13f67a713b26e9bfd25dfcc4c047b93ba341a9ce35be8?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        alt="Background image"
        className="object-cover absolute inset-0 size-full"
      />
      <div className="flex relative flex-col items-center px-20 pt-4 pb-12 mr-0 w-full max-md:px-5 max-md:max-w-full">
        <div className="flex flex-col items-center max-w-full w-[493px]">
          <div className="flex gap-3 max-w-full text-2xl tracking-normal w-[250px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/cce84df9fd1e9b6eab88517f73aa51b4f3b0ad562a75b7282ccd8194b84d7438?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt="Game Propaganda logo"
              className="object-contain shrink-0 self-start aspect-square rounded-[32px] w-[29px]"
            />
            <div className="grow shrink w-[203px]">Game Propaganda</div>
          </div>
          <h2 className="self-stretch mt-8 text-8xl text-center uppercase font-[250] leading-[106px] tracking-[7.29px] max-md:max-w-full max-md:text-4xl max-md:leading-10">
            Premium Club
          </h2>
          <button className="overflow-hidden gap-2.5 self-stretch py-4 pr-6 pl-6 mt-12 max-w-full text-base font-bold leading-tight text-center bg-white min-h-[50px] rounded-[1000px] text-neutral-900 w-[170px] max-md:px-5 max-md:mt-10">
            Вступить в клуб
          </button>
        </div>
      </div>
    </section>
  );
}

export default CallToActionSection;
