/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Header() {
  return (
    <header className="flex flex-col self-stretch pt-4 w-full bg-neutral-900 max-md:max-w-full">
      <div className="flex flex-wrap gap-5 justify-between self-center w-full max-w-[1252px] max-md:max-w-full">
        <nav className="flex flex-wrap gap-10 text-sm leading-loose whitespace-nowrap text-neutral-200 max-md:max-w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/86d89d504fb597a169c5213d0d82a138244d5f3770c6e0987bbbe0353b1a67ca?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Company Logo"
            className="object-contain shrink-0 max-w-full aspect-[3.72] w-[156px]"
          />
          <div className="flex gap-10 items-start my-auto max-md:max-w-full">
            <a href="#catalog">каталог</a>
            <div className="flex gap-1 items-center">
              <a href="#subscriptions" className="self-stretch my-auto">
                подписки
              </a>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/33c2b98cda6e5be318319541cc105a353120ea650a1d054f8aff2432fe72fa7b?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                alt=""
                className="object-contain shrink-0 self-stretch my-auto w-4 aspect-square"
              />
            </div>
            <a href="#blog">блог</a>
            <div className="flex gap-1 items-center">
              <a href="#accounts" className="self-stretch my-auto">
                аккаунты
              </a>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/33c2b98cda6e5be318319541cc105a353120ea650a1d054f8aff2432fe72fa7b?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                alt=""
                className="object-contain shrink-0 self-stretch my-auto w-4 aspect-square"
              />
            </div>
            <div className="flex gap-1 items-center">
              <a href="#balance" className="self-stretch my-auto">
                баланс
              </a>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/33c2b98cda6e5be318319541cc105a353120ea650a1d054f8aff2432fe72fa7b?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                alt=""
                className="object-contain shrink-0 self-stretch my-auto w-4 aspect-square"
              />
            </div>
          </div>
        </nav>
        <div className="flex gap-2.5 my-auto">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/67c7c8046a64f55a9a58df4d8198fb23627937744d63f32cbadf9d4b2308b99b?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="User profile"
            className="object-contain shrink-0 aspect-square w-[38px]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/0ca4fb9d3bc9212f9b516d7b8a964484e6b1a75cb74907e73035c24ea81086ca?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Shopping cart"
            className="object-contain shrink-0 aspect-square w-[38px]"
          />
        </div>
      </div>
      <div className="flex mt-3.5 w-full bg-neutral-800 min-h-[1px] max-md:max-w-full" />
    </header>
  );
}

export default Header;
