/**
 * This code was generated by Builder.io.
 */
import React from "react";

function HeroSection() {
  return (
    <section className="flex flex-col items-center">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/972945a6b0619a7749675d64400b468bcec0e35bb2a3d6472c9c12d23f5e2afa?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        alt="Premium Club Logo"
        className="object-contain mt-48 w-28 max-w-full rounded-none aspect-[1.58] max-md:mt-10"
      />
      <h1 className="z-10 mt-8 text-8xl leading-none text-center uppercase font-[250] tracking-[43.73px] max-md:max-w-full max-md:text-4xl">
        Premium Club
      </h1>
      <div className="flex flex-col items-center self-stretch px-20 pt-11 pb-20 w-full text-center bg-neutral-900 rounded-[40px] max-md:px-5 max-md:max-w-full">
        <div className="flex flex-col w-full max-w-[996px] max-md:max-w-full">
          <div className="self-center text-3xl tracking-normal">
            от Game Propaganda
          </div>
          <p className="mt-72 text-2xl leading-8 text-white max-md:mt-10 max-md:max-w-full">
            Мы создали сообщество, состоящее из самых преданных и
            заинтересованных пользователей нашего сервиса. Мы отдали им максимум
            возможного, превосходя все ожидания.
          </p>
        </div>
      </div>
    </section>
  );
}

export default HeroSection;
