/**
 * This code was generated by Builder.io.
 */
import React from "react";

function JoinMethodsSection() {
  return (
    <section className="mt-20 max-md:mt-10">
      <div className="flex shrink-0 w-0.5 h-[99px]" />
      <h2 className="mt-5 text-6xl font-light text-center uppercase leading-[60px] w-[522px] max-md:text-4xl max-md:leading-10">
        как стать участником
      </h2>
      <div className="mt-10 w-full max-w-[1250px] max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full">
            <div className="flex flex-col grow items-center px-20 pt-12 w-full text-center rounded-3xl border border-solid bg-white bg-opacity-10 border-white border-opacity-20 max-md:px-5 max-md:mt-4">
              <h3 className="text-3xl font-light leading-none uppercase">
                Способ 1
              </h3>
              <p className="self-stretch mt-3.5 text-base text-white">
                Купить PS5 от нашей компании
              </p>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/352527274077613dedb862e250d3b34f1616eec8768464b57af9fc32a69cac48?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                alt="PlayStation 5"
                className="object-contain mt-3.5 max-w-full aspect-[0.66] w-[183px]"
              />
            </div>
          </div>
          <div className="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
            <div className="flex flex-col grow items-center px-8 py-11 w-full text-center rounded-3xl border border-solid bg-white bg-opacity-10 border-white border-opacity-20 max-md:px-5 max-md:mt-4">
              <h3 className="text-3xl font-light leading-none uppercase">
                Способ 2
              </h3>
              <p className="mt-3.5 text-base leading-6 text-white">
                Потратить за один месяц 20.000₽ на покупки в нашем магазине
              </p>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/d99f54ba1a7d10a2cf2b67c9c358de34b50417d3ef9a156f88dba8a5c1766e36?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                alt="Shopping cart illustration"
                className="object-contain self-stretch mt-9 w-full rounded-xl aspect-[1.76]"
              />
            </div>
          </div>
          <div className="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
            <div className="flex flex-col grow items-center px-16 py-24 w-full text-center rounded-3xl border border-solid bg-white bg-opacity-10 border-white border-opacity-20 max-md:px-5 max-md:mt-4">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/5703346bf542f983b925ff37c46c778cd657711859567774acf9e933f9a321ff?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                alt=""
                className="object-contain w-12 rounded-none aspect-square"
              />
              <h3 className="mt-8 text-3xl font-light leading-none uppercase">
                Что дальше?
              </h3>
              <p className="self-stretch mt-5 text-base leading-6 text-white">
                После выполнения условий тебе придет письмо на почту с
                приглашением в наш канал и аккаунт автоматически станет
                премиальным
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

export default JoinMethodsSection;
