/**
 * This code was generated by Builder.io.
 */
import React from "react";

function NewbieAccountSection() {
  return (
    <section className="mt-5 w-full max-w-[1400px] max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
          <div className="flex flex-col grow px-20 pt-11 pb-px w-full border border-solid bg-neutral-900 border-white border-opacity-10 rounded-[40px] max-md:px-5 max-md:mt-2.5 max-md:max-w-full">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/d6de9459e8b0ee2176e3b41668fbd308c33aa8405715b329fc775bac0510b9e1?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt="Account level illustration"
              className="object-contain w-full aspect-[0.96] max-md:max-w-full"
            />
          </div>
        </div>
        <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
          <div className="flex flex-col px-20 py-16 mx-auto w-full border border-solid bg-white bg-opacity-0 border-white border-opacity-10 rounded-[40px] max-md:px-5 max-md:mt-3 max-md:max-w-full">
            <div className="max-md:max-w-full">
              <div className="flex gap-5 max-md:flex-col">
                <div className="flex flex-col w-4/5 max-md:ml-0 max-md:w-full">
                  <div className="flex flex-col grow max-md:mt-10">
                    <h3 className="text-5xl font-light leading-none uppercase max-md:text-4xl">
                      Новобранец
                    </h3>
                    <p className="self-start mt-2.5 text-base leading-6 text-white">
                      Начальный уровень, доступ к базовым функциям и новостям
                    </p>
                  </div>
                </div>
                <div className="flex flex-col ml-5 w-1/5 max-md:ml-0 max-md:w-full">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/8df57a71539c8a5212819dd9dd266338ff65fd0799f737bb13178d7d42eb8123?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                    alt="Newbie badge"
                    className="object-contain grow shrink-0 bg-blend-screen aspect-[0.79] w-[82px] max-md:mt-10"
                  />
                </div>
              </div>
            </div>
            <div className="flex flex-col mt-20 max-w-full w-[458px] max-md:mt-10">
              <div className="flex gap-6 w-full rounded-xl">
                <div className="z-10 self-start px-2.5 mt-1.5 text-4xl font-semibold text-center whitespace-nowrap rounded-xl text-neutral-700">
                  %
                </div>
                <div className="flex flex-col grow shrink-0 text-white basis-0 w-fit">
                  <h4 className="self-start text-2xl">
                    Разовая скидка на подписку 10%
                  </h4>
                  <p className="mt-1.5 text-base leading-6">
                    Чтобы перейти на 2 уровень, потратьте больше 10к рублей или
                    купите 5 раз за 1 месяц
                  </p>
                </div>
              </div>
              <div className="flex gap-6 mt-8 w-full rounded-xl">
                <div className="z-10 self-start px-2.5 mt-1.5 text-4xl font-semibold text-center whitespace-nowrap rounded-xl text-neutral-700">
                  %
                </div>
                <div className="flex flex-col grow shrink-0 text-white basis-0 w-fit">
                  <h4 className="self-start text-2xl">
                    Разовая скидка на подписку 10%
                  </h4>
                  <p className="mt-1.5 text-base leading-6">
                    Чтобы перейти на 2 уровень, потратьте больше 10к рублей или
                    купите 5 раз за 1 месяц
                  </p>
                </div>
              </div>
            </div>
            <div className="flex flex-wrap gap-5 justify-between p-1 mt-12 text-base text-right text-white rounded-xl border border-solid bg-white bg-opacity-0 border-white border-opacity-10 max-md:mt-10 max-md:max-w-full">
              <div className="flex shrink-0 h-9 bg-orange-700 rounded-lg w-[54px]" />
              <div className="my-auto">Уровень 1</div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

export default NewbieAccountSection;
