/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function PrivilegesSection() {
  return (
    <section className="mt-8 w-full max-w-[1216px] max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-[26%] max-md:ml-0 max-md:w-full">
          <div className="flex flex-col self-stretch my-auto mr-0 max-md:mt-10">
            <h2 className="text-5xl font-light uppercase leading-[50px] max-md:text-4xl max-md:leading-10">
              Ваши <br /> привилегии
            </h2>
            <div className="flex flex-col items-start pr-16 pl-8 mt-28 w-full max-md:px-5 max-md:mt-10">
              <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/54c5048155556c0dbe150b9e8bc7dfa1f956898cc291f951a777a0dda8ddd7b2?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c" alt="" className="object-contain w-12 rounded-none aspect-square" />
              <p className="mt-11 text-base leading-6 text-white max-md:mt-10">
                Мы создали канал, в котором постим только самые главные новости и эксклюзивные новинки, будущие акции
              </p>
              <button className="overflow-hidden gap-2.5 self-stretch py-4 pr-6 pl-6 mt-11 text-base font-bold leading-tight text-center text-black bg-white min-h-[50px] rounded-[1000px] w-[121px] max-md:px-5 max-md:mt-10">
                Хочу в клуб
              </button>
            </div>
          </div>
        </div>
        <div className="flex flex-col ml-5 w-[74%] max-md:ml-0 max-md:w-full">
          <div className="flex flex-col w-full max-md:max-w-full">
            <div className="w-full max-md:max-w-full">
              <div className="flex gap-5 max-md:flex-col">
                <div className="flex flex-col w-9/12 max-md:ml-0 max-md:w-full">
                  <div className="flex relative flex-col flex-wrap gap-10 items-start px-20 pb-4 text-4xl font-semibold text-center whitespace-nowrap min-h-[721px] pt-[625px] text-neutral-700 max-md:px-5 max-md:pt-24 max-md:max-w-full">
                    <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/3323bc23223f584730c736505a694e6903a3d7d4f96482eff25d9c82d40b233b?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c" alt="Background image" className="object-cover absolute inset-0 size-full" />
                    <div className="relative z-10 self-start px-2.5 rounded-xl">%</div>
                    <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/73acd87b64c1c4dda265b83a71e980ad5e263c91e857c11bbf5ae8f9af6ea10c?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c" alt="" className="object-contain shrink-0 self-end mt-8 w-12 rounded-none aspect-square" />
                  </div>
                </div>
                <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
                  <div className="flex flex-col mt-80 text-base leading-6 text-white max-md:mt-10">
                    <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/67ff50869368f83447ed7434f01184c9ff145566f261bd6aa50c7c8e97e3594d?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c" alt="" className="object-contain w-12 rounded-none aspect-square" />
                    <p className="mt-11 max-md:mt-10">
                      Continuing from where we left off:

                    Обычно все общение проходит через бота, и иногда возникают небольшие очереди. Однако в нашем клубе это исключено: вы получаете персонального менеджера, который незамедлительно активирует все заказы и отвечает на все вопросы
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div className="z-10 -mt-1.5 ml-20 max-w-full w-[528px]">
            <div className="flex gap-5 max-md:flex-col">
              <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
                <p className="text-base leading-6 text-white max-md:mt-10">
                  Вы получите сразу 5-ый уровень аккаунта: на этом уровне у вас будет пожизненная скидка 5% на все товары, которая со временем может увеличиться до 10%.
                </p>
              </div>
              <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
                <p className="mt-8 text-base leading-6 text-white max-md:mt-10">
                  Возможность влиять на наши будущие проекты и быть в курсе всех новостей компании
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    </section>
  );
}

export default PrivilegesSection;