/**
 * This code was generated by Builder.io.
 */
import React from "react";

function AdvantagesSection() {
  const advantages = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/b61234027919c037268e24f62a64ddcbe314bd1b9f88504a2cc997c3a5a552a4?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
      text: "Данные от аккаунты ты получишь от 2 двух до 4 часов после покупки",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/262b679206081c49503b64300da2843ddaf1576570fafdb1fdb9a3f4d313374c?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
      text: "Низкие цены на игры и подписку",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/2b931f754e9c0c4c57f28005873f2160b7c88c3dec8766735b33bb87e7bbc812?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
      text: "Можно связать с российским аккаунтом",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/63faa8381a470ace7b424c995b9705704034bdf65b1e2f7074a049b1b64021c9?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
      text: "После покупки ты можешь поменять все данные и подключить 2FA",
    },
  ];

  return (
    <section className="flex flex-col items-start px-16 py-16 mx-auto w-full text-xl tracking-normal leading-7 text-white border border-solid bg-zinc-900 border-zinc-800 rounded-[40px] max-md:px-5 max-md:mt-2 max-md:max-w-full">
      <h2 className="text-3xl font-bold leading-tight">Преимущества</h2>
      {advantages.map((advantage, index) => (
        <div key={index} className="flex gap-6 mt-10">
          <img
            loading="lazy"
            src={advantage.icon}
            alt=""
            className="object-contain shrink-0 self-start rounded-none aspect-square w-[50px]"
          />
          <div className="flex-auto">{advantage.text}</div>
        </div>
      ))}
    </section>
  );
}

export default AdvantagesSection;
