/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Logo from "./Logo";
import SocialIcons from "./SocialIcons";

function Footer() {
  const footerLinks = [
    {
      title: "магазин",
      links: ["каталог", "подписки", "скидки"],
    },
    {
      title: "покупателям",
      links: [
        "возвраты",
        "реквизиты",
        "политика конфиденциальности",
        "публичная оферта",
        "согласие на рекламную рассылку",
      ],
    },
  ];

  const paymentMethods = [
    "https://cdn.builder.io/api/v1/image/assets/TEMP/c9f94ce25e4029f5402fb3bd8b58c24ec5a384446f386c7a0371eef74123beb3?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    "https://cdn.builder.io/api/v1/image/assets/TEMP/e7ef90ce1d09e71b19ac222a1dcfa6463d753dd4f21cf419d9d08a6b67b7284a?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    "https://cdn.builder.io/api/v1/image/assets/TEMP/50d71faf4d3c3d8aca4220f493c872bd090cdafd6008b4f97ed638b9ac173074?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    "https://cdn.builder.io/api/v1/image/assets/TEMP/e2920dd3657ab83c30c8eb8cb13e0f747c6be23b85a786e78579df7b236fa993?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    "https://cdn.builder.io/api/v1/image/assets/TEMP/cf0899962d0f4b01ba52e1f5496ab218416c69884d2932fcd23daa1f51d571b4?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    "https://cdn.builder.io/api/v1/image/assets/TEMP/e1365850e339d0a5600defa0187930f50de47abaf9660fbae40f215dee4a1b44?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  ];

  return (
    <footer className="flex overflow-hidden flex-col items-center self-stretch px-20 pb-10 mt-16 w-full bg-neutral-900 max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="flex shrink-0 max-w-full h-px bg-neutral-800 w-[1252px]" />
      <div className="flex flex-wrap gap-10 self-start mt-16 w-full max-w-[1186px] max-md:mt-10 max-md:max-w-full">
        <div className="flex flex-col self-start">
          <Logo />
          <div className="mt-9 mr-7 text-2xl font-semibold leading-none text-neutral-200 max-md:mr-2.5">
            hello@playstationplus.store
          </div>
          <div className="mt-1 text-base font-medium leading-loose text-neutral-400">
            принимаем заявки с 11:00 до 21:00 (МСК)
          </div>
          <SocialIcons />
        </div>
        <div className="flex-auto max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            {footerLinks.map((section, index) => (
              <div
                key={index}
                className="flex flex-col w-[28%] max-md:ml-0 max-md:w-full"
              >
                <div className="flex flex-col whitespace-nowrap max-md:mt-10">
                  <h3 className="text-2xl font-semibold leading-none text-neutral-200">
                    {section.title}
                  </h3>
                  <div className="flex flex-col self-start mt-5 text-sm font-medium leading-loose text-neutral-400">
                    {section.links.map((link, linkIndex) => (
                      <div
                        key={linkIndex}
                        className={linkIndex > 0 ? "mt-3" : ""}
                      >
                        {link}
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
      <div className="flex shrink-0 mt-20 max-w-full h-px bg-neutral-800 w-[1252px] max-md:mt-10" />
      <div className="flex flex-wrap gap-5 justify-between mt-10 w-full max-w-[1252px] max-md:max-w-full">
        <div className="text-sm leading-loose text-neutral-400">
          © 2024, «GamePropaganda»
        </div>
        <div className="flex gap-6">
          {paymentMethods.map((src, index) => (
            <img
              key={index}
              loading="lazy"
              src={src}
              alt={`Payment method ${index + 1}`}
              className="object-contain shrink-0 my-auto w-10 aspect-[2]"
            />
          ))}
        </div>
      </div>
    </footer>
  );
}

export default Footer;
