/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Logo from "./Logo";
import Navigation from "./Navigation";
import SubscribeButton from "./SubscribeButton";
import SocialIcons from "./SocialIcons";

function Header() {
  return (
    <header className="flex relative flex-col pt-4 w-full bg-neutral-900 bg-opacity-60 max-md:max-w-full">
      <div className="flex gap-5 justify-between items-center self-center w-full max-w-[1252px] max-md:max-w-full">
        <Logo />
        <Navigation />
        <SubscribeButton />
        <SocialIcons />
      </div>
      <div className="flex mt-3.5 w-full bg-neutral-800 min-h-[1px] max-md:max-w-full" />
    </header>
  );
}

export default Header;
