/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Hero() {
  return (
    <section className="flex overflow-hidden relative flex-col self-stretch pb-28 w-full min-h-[678px] max-md:pb-24 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/a83171dee89d4592163a1563ace8d17d36bc78672839a0c450b183f2ab9af33c?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        alt="Background"
        className="object-cover absolute inset-0 size-full"
      />
      <div className="flex relative flex-col items-start mt-44 mb-0 ml-24 max-w-full text-white w-[494px] max-md:mt-10 max-md:mb-2.5">
        <h1 className="self-stretch text-5xl font-black leading-[50px] max-md:max-w-full max-md:text-4xl max-md:leading-10">
          Создадим тебе личный турецкий аккаунт PSN
        </h1>
        <p className="mt-5 text-3xl tracking-normal">на твою почту</p>
        <button className="overflow-hidden gap-2.5 self-stretch px-8 py-4 mt-16 text-base font-bold leading-tight text-black bg-lime-400 min-h-[50px] rounded-[1000px] max-md:px-5 max-md:mt-10">
          Купить аккаунт
        </button>
      </div>
    </section>
  );
}

export default Hero;
