/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Logo() {
  return (
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/f9a38d3a4f19b57febf8ce8025b0bfaf8bf8289a9832eb778169057739f3c0bb?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
      alt="Company Logo"
      className="object-contain shrink-0 self-stretch max-w-full aspect-[3.72] w-[156px]"
    />
  );
}

export default Logo;
