/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Hero from "./Hero";
import PricingSection from "./PricingSection";
import AdvantagesSection from "./AdvantagesSection";
import TestimonialsSection from "./TestimonialsSection";
import NewsletterSection from "./NewsletterSection";
import TelegramSection from "./TelegramSection";
import Footer from "./Footer";

function MainLayout() {
  return (
    <div className="flex overflow-hidden flex-col items-center pb-16 bg-neutral-900">
      <Header />
      <Hero />
      <div className="mt-11 w-full max-w-[1398px] max-md:mt-10 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
            <PricingSection />
          </div>
          <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
            <AdvantagesSection />
          </div>
        </div>
      </div>
      <TestimonialsSection />
      <div className="mt-5 w-full max-w-[1252px] max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
            <NewsletterSection />
          </div>
          <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
            <TelegramSection />
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}

export default MainLayout;
