/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Navigation() {
  const navItems = [
    { label: "каталог", hasDropdown: false },
    { label: "подписки", hasDropdown: true },
    { label: "блог", hasDropdown: false },
    { label: "аккаунты", hasDropdown: true },
    { label: "баланс", hasDropdown: true },
  ];

  return (
    <nav className="flex flex-wrap gap-10 self-stretch my-auto text-sm leading-loose max-md:max-w-full">
      {navItems.map((item, index) => (
        <div key={index} className="flex gap-1 items-center text-neutral-200">
          <div className="self-stretch my-auto">{item.label}</div>
          {item.hasDropdown && (
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/33c2b98cda6e5be318319541cc105a353120ea650a1d054f8aff2432fe72fa7b?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-4 aspect-square"
            />
          )}
        </div>
      ))}
    </nav>
  );
}

export default Navigation;
