/**
 * This code was generated by Builder.io.
 */
import React from "react";

function NewsletterSection() {
  return (
    <section className="flex flex-col items-start pt-8 pr-20 pb-12 pl-10 mx-auto w-full font-bold rounded-3xl bg-zinc-900 max-md:px-5 max-md:mt-5 max-md:max-w-full">
      <h2 className="text-xl tracking-normal leading-tight text-white">
        Подпишись на нашу рассылку
      </h2>
      <p className="mt-2 text-sm tracking-normal text-white">
        Рассказываем все новости игрового мира
      </p>
      <form className="flex gap-2.5 mt-10 max-w-full text-base leading-tight whitespace-nowrap w-[410px]">
        <label htmlFor="email" className="sr-only">
          Email
        </label>
        <input
          type="email"
          id="email"
          placeholder="Email"
          className="overflow-hidden gap-2.5 self-stretch py-4 pr-40 bg-white min-h-[50px] rounded-[100px] text-stone-900"
        />
        <button
          type="submit"
          className="gap-2.5 self-stretch px-8 py-4 text-center text-black bg-lime-400 min-h-[50px] rounded-[100px] max-md:px-5"
        >
          Подписаться
        </button>
      </form>
    </section>
  );
}

export default NewsletterSection;
