/**
 * This code was generated by Builder.io.
 */
import React from "react";

function PricingSection() {
  return (
    <section className="flex flex-col px-16 py-16 mx-auto w-full bg-zinc-900 rounded-[40px] max-md:px-5 max-md:mt-2 max-md:max-w-full">
      <h2 className="self-start text-3xl font-bold tracking-normal leading-tight text-white">
        Стоимость аккаунта
      </h2>
      <div className="p-9 mt-8 bg-white border border-solid border-white border-opacity-10 rounded-[30px] max-md:px-5 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-[76%] max-md:ml-0 max-md:w-full">
            <div className="flex flex-col w-full font-bold max-md:mt-10">
              <div className="self-start text-6xl leading-none text-zinc-800 max-md:text-4xl">
                450 ₽
              </div>
              <button className="overflow-hidden gap-2.5 self-stretch px-8 py-5 mt-11 text-base leading-none text-center text-white bg-rose-500 min-h-[60px] rounded-[1000px] max-md:px-5 max-md:mt-10">
                Купить аккаунт
              </button>
            </div>
          </div>
          <div className="flex flex-col ml-5 w-[24%] max-md:ml-0 max-md:w-full">
            <div className="flex flex-col grow max-md:mt-10">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/8697915f63bb2e8c9cbe88a51c314396d0110735b9dba776959c0a8f21ab127d?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                alt="Icon 1"
                className="object-contain aspect-[1.3] w-[70px]"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/894eb466e7c91d08b1549fe550e52614fa456f9e065c2c66d02c9fab40b819ed?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                alt="Icon 2"
                className="object-contain mt-16 ml-5 aspect-square rounded-[43px] w-[50px] max-md:mt-10 max-md:ml-2.5"
              />
            </div>
          </div>
        </div>
      </div>
      <p className="mt-5 text-base tracking-normal text-white max-md:mr-2.5 max-md:max-w-full">
        Или купи у нас подписку/любую игру и получи аккаунт бесплатно
      </p>
      <div className="flex gap-1 mt-5 max-w-full text-base font-bold leading-tight text-black w-[416px]">
        <button className="overflow-hidden gap-2.5 self-stretch px-8 py-4 bg-lime-400 min-h-[50px] rounded-[1000px] max-md:px-5">
          Купить подписку
        </button>
        <button className="overflow-hidden gap-2.5 self-stretch px-8 py-4 bg-lime-400 min-h-[50px] rounded-[1000px] max-md:px-5">
          Купить игру
        </button>
      </div>
    </section>
  );
}

export default PricingSection;
