/**
 * This code was generated by Builder.io.
 */
import React from "react";

function SocialIcons() {
  const icons = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/67c7c8046a64f55a9a58df4d8198fb23627937744d63f32cbadf9d4b2308b99b?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
      alt: "Social Icon 1",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/0ca4fb9d3bc9212f9b516d7b8a964484e6b1a75cb74907e73035c24ea81086ca?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
      alt: "Social Icon 2",
    },
  ];

  return (
    <div className="flex gap-2.5 self-stretch my-auto">
      {icons.map((icon, index) => (
        <img
          key={index}
          loading="lazy"
          src={icon.src}
          alt={icon.alt}
          className="object-contain shrink-0 aspect-square w-[38px]"
        />
      ))}
    </div>
  );
}

export default SocialIcons;
