/**
 * This code was generated by Builder.io.
 */
import React from "react";

function TelegramSection() {
  return (
    <section className="flex flex-col items-start pt-8 pr-20 pb-12 pl-10 mx-auto w-full rounded-3xl bg-zinc-900 max-md:px-5 max-md:mt-5 max-md:max-w-full">
      <h2 className="text-xl font-bold tracking-normal leading-tight text-white">
        Подпишись на наш Telegram-канал
      </h2>
      <p className="mt-2 text-sm tracking-normal text-white">
        Постим самые интересные новости первыми
      </p>
      <div className="flex gap-2.5 mt-10">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/e66ca1db4fb278b71f6fb2089bdcce2937a05331199648944d48802cfcafe7e8?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          alt="Telegram QR Code"
          className="object-contain shrink-0 max-w-full rounded-none aspect-[3.4] w-[170px]"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/ed77b89986fb8bc22c2a898c7654b4bb7f360fb09914f8ecd1392d15916755b7?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          alt="Telegram App Store"
          className="object-contain shrink-0 max-w-full rounded-none aspect-[3.4] w-[170px]"
        />
      </div>
    </section>
  );
}

export default TelegramSection;
