/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Footer() {
  return (
    <footer className="flex overflow-hidden flex-col items-center self-stretch px-20 pb-10 mt-16 w-full bg-neutral-900 max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="flex shrink-0 max-w-full h-px bg-neutral-800 w-[1252px]" />
      <div className="flex flex-wrap gap-10 self-start mt-16 w-full max-w-[1186px] max-md:mt-10 max-md:max-w-full">
        <div className="flex flex-col self-start">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/c39dc0b750d2abfdc8478669bbf60d59534ef62fbf3f8479f4db3ccfdcd8cc77?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Company logo"
            className="object-contain max-w-full aspect-[3.72] w-[156px]"
          />
          <div className="mt-9 mr-7 text-2xl font-semibold leading-none text-neutral-200 max-md:mr-2.5">
            hello@playstationplus.store
          </div>
          <div className="mt-1 text-base font-medium leading-loose text-neutral-400">
            принимаем заявки с 11:00 до 21:00 (МСК)
          </div>
          <div className="flex gap-2 self-start mt-4">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/9e6026c93497c05916de173ea3de67c0fbb215f5f28189918e1ffec1b564ccd3?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt="Social media icon"
              className="object-contain shrink-0 aspect-square fill-zinc-800 w-[42px]"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/82bc375cf21f23dd196b5eb4ba10e90b3c643e0a58d181eacd952cd07d571335?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt="Social media icon"
              className="object-contain shrink-0 aspect-square w-[42px]"
            />
          </div>
        </div>
        <nav className="flex-auto max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            <div className="flex flex-col w-[28%] max-md:ml-0 max-md:w-full">
              <div className="flex flex-col whitespace-nowrap max-md:mt-10">
                <h3 className="text-2xl font-semibold leading-none text-neutral-200">
                  магазин
                </h3>
                <ul className="flex flex-col self-start mt-5 text-sm font-medium leading-loose text-neutral-400">
                  <li>
                    <a href="#">каталог</a>
                  </li>
                  <li className="mt-3">
                    <a href="#">подписки</a>
                  </li>
                  <li className="mt-3">
                    <a href="#">скидки</a>
                  </li>
                </ul>
              </div>
            </div>
            <div className="flex flex-col ml-5 w-[73%] max-md:ml-0 max-md:w-full">
              <div className="flex flex-col grow max-md:mt-10">
                <h3 className="self-start text-2xl font-semibold leading-none text-neutral-200">
                  покупателям
                </h3>
                <ul className="flex flex-col mt-5 text-sm font-medium leading-loose text-neutral-400">
                  <li>
                    <a href="#">возвраты</a>
                  </li>
                  <li className="mt-3">
                    <a href="#">реквизиты</a>
                  </li>
                  <li className="mt-3">
                    <a href="#">политика конфиденциальности</a>
                  </li>
                  <li className="mt-3">
                    <a href="#">публичная оферта</a>
                  </li>
                  <li className="mt-3">
                    <a href="#">согласие на рекламную рассылку</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </nav>
      </div>
      <div className="flex shrink-0 mt-20 max-w-full h-px bg-neutral-800 w-[1252px] max-md:mt-10" />
      <div className="flex flex-wrap gap-5 justify-between mt-10 w-full max-w-[1252px] max-md:max-w-full">
        <div className="text-sm leading-loose text-neutral-400">
          © 2024, «GamePropaganda»
        </div>
        <div className="flex gap-6">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/26fd758e44f5cffcf7e84fa0bf511f09c1cecf3943bea3ab58349e818b1d1a82?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method"
            className="object-contain shrink-0 my-auto w-10 aspect-[2]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/84dd3b9d49b1ee5db426fd9d146a4b34dabb6c31bf4392b4071007ae059c4378?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method"
            className="object-contain shrink-0 my-auto w-11 aspect-[2.2]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/7de3e0fe40e02c3933194807b84e326b3154eed0d6d41ec19e971e270ea5803b?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method"
            className="object-contain shrink-0 my-auto w-12 aspect-[2.4]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/f2341440780a0cc6e3411f462a2d2e32a51b01db17a51b579c3506b8f87af1a5?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method"
            className="object-contain shrink-0 aspect-[1.75] w-[42px]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/4335356edf9a699b4980631162f0e91a44d4ed6573f3721dafe48e628e1a1418?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method"
            className="object-contain shrink-0 w-9 aspect-[1.5]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/ce7a371e5c7bc46f788cb1d094c9219a57dac2f7b50f23d38167e00592665985?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method"
            className="object-contain shrink-0 aspect-[2.16] w-[52px]"
          />
        </div>
      </div>
    </footer>
  );
}

export default Footer;
