/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Hero() {
  return (
    <section className="flex relative flex-col items-start mt-28 mb-0 ml-24 max-w-full text-white w-[567px] max-md:mt-10 max-md:mb-2.5">
      <h1 className="text-5xl font-black leading-[50px] max-md:max-w-full max-md:text-4xl max-md:leading-10">
        Купи новый Sony PlayStation 5{" "}
        <span className="text-white">с аккаунтом, подпиской и играми</span>
      </h1>
      <p className="self-stretch mt-8 text-xl tracking-normal max-md:max-w-full">
        Получи полный комплект без заморочек, а также доступ к Premium клубу от
        Game Propaganda с персональным менеджером и премиальной техподдержкой
      </p>
      <button className="overflow-hidden gap-2.5 self-stretch px-8 py-4 mt-12 text-base font-bold leading-tight text-black bg-lime-400 min-h-[50px] rounded-[1000px] max-md:px-5 max-md:mt-10">
        Купить комплект
      </button>
    </section>
  );
}

export default Hero;
