/**
 * This code was generated by Builder.io.
 */
import React from "react";

function PackageItem({ emoji, text }) {
  return (
    <div className="flex overflow-hidden gap-4 justify-center items-center py-2 pr-3.5 pl-2 rounded-xl border border-solid bg-zinc-800 border-neutral-700">
      <div className="flex flex-col self-stretch my-auto w-12 text-3xl font-semibold leading-none text-center whitespace-nowrap rounded-xl">
        <div className="px-2.5 py-3 rounded-xl">{emoji}</div>
      </div>
      <div className="my-auto text-base font-medium leading-5">{text}</div>
    </div>
  );
}

export default PackageItem;
