/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import PackageItem from './PackageItem';

const packageItems = [
  { emoji: '💬', text: 'Новенький PS5 Slim Pro 1 TB' },
  { emoji: '💻', text: '1 джойстик' },
  { emoji: '💳', text: 'Подписка Deluxe на 1 месяц' },
  { emoji: '🧑‍💻', text: 'Переходник для розетки' },
  { emoji: '🫶', text: 'Личный турецкий аккаунт на вашу почту' },
  { emoji: '🤩', text: 'Членство в Premium Club от Game Propaganda' },
  { emoji: '📜', text: 'Игры месяца' },
  { emoji: '👾', text: 'Mortal Kombat 11' },
  { emoji: '🎮', text: 'Grand Theft Auto V' },
  { emoji: '🧑', text: "Assassin's Creed Valhalla" }
];

function PackageContents() {
  return (
    <section className="mt-2.5 text-center text-white">
      <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/5b642e248def847f474caee15b07d42f3685fbf47e73a519433e6ffd3b9f2b3b?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c" alt="" className="object-contain rounded-none aspect-square w-[70px]" />
      <h2 className="mt-2.5 text-5xl font-bold leading-none max-md:max-w-full max-md:text-4xl">
        Что входит в комплект
      </h2>
      <div className="flex flex-wrap gap-2.5 justify-center items-start mt-8 w-full text-white max-w-[980px] max-md:max-w-full">
        {packageItems.map((item, index) => (
          <PackageItem key={index} {...item} />
        ))}
      </div>
    </section>
  );
}

export default PackageContents;