/**
 * This code was generated by Builder.io.
 */
import React from "react";
import PremiumClubFeature from "./PremiumClubFeature";

const features = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/fe404cdee9450effeba3659324cfd1ce0c238da77e12affd0d49c61a153bd864?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    text: "Скидка на все покупки на нашем сервисе",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/9b80a581ec855ae829110804e358ebbbcb1e1545d9b9cb3032b187ac7af910f3?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    text: "Собственный менеджер",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/c71794eba8722d2c76dfba42203b5428644c8880ce1b6f130754098261f6bb9d?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    text: "Выжимка авторских новостей",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/deed274d467f37e0aded919cf27dc19a5c60f7fff0c15e912cdcf00b5ed5d4fd?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    text: "Эксклюзивные акции",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/f34bbdd5cd9e2d1bac8e4eea36e3f4fbc530308efd59350dd029f9287850e040?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    text: "Поддержка 24/7",
  },
];

function PremiumClub() {
  return (
    <section className="flex flex-col justify-center items-center px-20 py-24 mt-16 w-full text-white max-w-[1400px] max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-col items-center w-full max-w-[997px] max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/60e8d60f6faf28bec19a3915b6a55d03ef381409d17b5508b5df27d466be2e09?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          alt="Premium Club logo"
          className="object-contain w-20 aspect-square rounded-[85px]"
        />
        <h2 className="mt-10 text-6xl font-black text-center leading-[61px] w-[774px] max-md:max-w-full max-md:text-4xl max-md:leading-10">
          Что такое Premium Club от Game Propaganda
        </h2>
        <div className="flex flex-wrap gap-10 justify-center items-start self-stretch mt-16 w-full text-xl tracking-normal leading-7 max-md:mt-10 max-md:max-w-full">
          {features.map((feature, index) => (
            <PremiumClubFeature key={index} {...feature} />
          ))}
        </div>
        <button className="overflow-hidden gap-2.5 self-stretch px-8 py-4 mt-12 max-w-full text-base font-bold leading-tight text-black bg-lime-400 min-h-[50px] rounded-[1000px] w-[206px] max-md:px-5 max-md:mt-10">
          Попасть в клуб
        </button>
      </div>
    </section>
  );
}

export default PremiumClub;
