/**
 * This code was generated by Builder.io.
 */
import React from "react";

function TechnicalSpecs() {
  return (
    <section className="mt-32 w-full max-w-[1398px] max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
          <div className="flex flex-col grow tracking-normal text-white max-md:mt-2 max-md:max-w-full">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/81979f028e8e948ae4a952fa040927aeb022a793fcb8bc996c36976aaf6e1882?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt="PlayStation 5 console"
              className="object-contain w-full rounded-none aspect-[0.9] max-md:max-w-full"
            />
            <div className="flex flex-col items-start px-16 py-12 mt-2 border border-solid bg-zinc-900 border-zinc-800 rounded-[40px] max-md:px-5 max-md:max-w-full">
              <h3 className="text-3xl font-bold">Процессор и память</h3>
              <dl className="flex flex-col items-start mt-10 max-w-full text-sm leading-snug w-[529px]">
                <div className="flex flex-wrap gap-5 justify-between pb-3 w-full rounded-none">
                  <dt className="self-start">Процессов</dt>
                  <dd>x86-64-AMD Ryzen Zen 2</dd>
                </div>
                <div className="flex flex-wrap gap-5 justify-between pb-3 mt-2.5 w-full rounded-none">
                  <dt className="self-start">Количество ядер</dt>
                  <dd>8</dd>
                </div>
                <div className="flex flex-wrap gap-10 pb-3 mt-2.5 w-full rounded-none">
                  <dt className="grow shrink w-[135px]">
                    Тактовая частота (МГц)
                  </dt>
                  <dd className="flex-auto w-[285px]">8</dd>
                </div>
                {/* Repeat for other specifications */}
              </dl>
            </div>
          </div>
        </div>
        {/* Right column content */}
      </div>
    </section>
  );
}

export default TechnicalSpecs;
