/**
 * This code was generated by Builder.io.
 */
import React from "react";

function TelegramChannel() {
  return (
    <section className="flex flex-col items-start pt-8 pr-20 pb-12 pl-10 mx-auto w-full rounded-3xl bg-zinc-900 max-md:px-5 max-md:mt-5 max-md:max-w-full">
      <h3 className="text-xl font-bold tracking-normal leading-tight text-white">
        Подпишись на наш Telegram-канал
      </h3>
      <p className="mt-2 text-sm tracking-normal text-white">
        Постим самые интересные новости первыми
      </p>
      <div className="flex gap-2.5 mt-10">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/74d6a88e94385f80ec3f433542440ef3896c1ea3033de16f273503a69145fa7e?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          alt="Telegram channel QR code"
          className="object-contain shrink-0 max-w-full rounded-none aspect-[3.4] w-[170px]"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/66214c20cd25892d6d28cd63e7ef92765275b98973856fa6a5a67dee4a56c24c?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          alt="Telegram channel link"
          className="object-contain shrink-0 max-w-full rounded-none aspect-[3.4] w-[170px]"
        />
      </div>
    </section>
  );
}

export default TelegramChannel;
