/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FeatureCard from "./FeatureCard";

const features = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/8787e0ac01f1c2c7f40b344263fec4a82b375be4e10bc38f8e94b6b971559101?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Награды для подписчиков",
    description:
      "Открой для себя уникальные внутриигровые испытания и награды, которые сделают твою игру ярче и помогут выделиться.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/4ffe0ee65707736110f3f2d3aca93abb64bcb3b65f81ca291b4a2617feedad83?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "The Play List",
    description:
      "Получай неограниченный доступ к коллекции лучших игр и хитов от Electronic Arts.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/e341c33acbdbd91cf06fb60b03e7a365160cb26d33f3b68b8b6884b9ef763db0?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Пробный доступ к играм",
    description:
      "Пробуй новейшие хиты бесплатно до 10 часов. Все твои достижения и прогресс сохранятся, если решишь купить игру.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/29374a9d7806f5ada74b71395f168473eef7c86f55258df71f3784f92dd9e459?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Скидка 10%",
    description:
      "Наслаждайся скидкой 10% на весь цифровой контент от Electronic Arts: игры, дополнения, Season Pass и комплекты очков.",
  },
];

function EAPlaySection() {
  return (
    <section className="flex flex-col items-center px-20 pt-16 pb-28 mt-40 w-full border border-solid bg-zinc-900 border-zinc-800 rounded-[40px] max-md:px-5 max-md:pb-24 max-md:mt-10 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/ea9ee65ac2957fb9f686017404433debefa9cf5da682f1fb691e854667c07116?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        alt=""
        className="object-contain rounded-none aspect-square w-[50px]"
      />
      <h2 className="mt-2.5 text-5xl font-bold leading-none text-center text-white">
        Что такое EA Play?
      </h2>
      <div className="self-stretch mt-16 mb-0 max-md:mt-10 max-md:mb-2.5 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          {features.map((feature, index) => (
            <FeatureCard key={index} {...feature} />
          ))}
        </div>
      </div>
    </section>
  );
}

export default EAPlaySection;
