/**
 * This code was generated by Builder.io.
 */
import React from "react";

function FeatureCard({ icon, title, description }) {
  return (
    <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col w-full tracking-normal text-white max-md:mt-10 max-md:max-w-full">
        <div className="flex flex-wrap gap-6">
          <img
            loading="lazy"
            src={icon}
            alt=""
            className="object-contain shrink-0 self-start mt-1.5 rounded-none aspect-square w-[50px]"
          />
          <div className="flex flex-col grow shrink-0 basis-0 w-fit max-md:max-w-full">
            <h3 className="self-start text-3xl font-bold leading-tight">
              {title}
            </h3>
            <p className="mt-4 text-base leading-6 max-md:max-w-full">
              {description}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default FeatureCard;
