/**
 * This code was generated by Builder.io.
 */
import React from "react";

function FooterColumn({ title, links }) {
  return (
    <div className="flex flex-col w-[28%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col whitespace-nowrap max-md:mt-10">
        <h3 className="text-2xl font-semibold leading-none text-neutral-200">
          {title}
        </h3>
        <div className="flex flex-col self-start mt-5 text-sm font-medium leading-loose text-neutral-400">
          {links.map((link, index) => (
            <div key={index} className={index > 0 ? "mt-3" : ""}>
              {link}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default FooterColumn;
