/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Hero from "./Hero";
import EAPlaySection from "./EAPlaySection";
import SubscriptionPlans from "./SubscriptionPlans";
import Testimonials from "./Testimonials";
import Newsletter from "./Newsletter";
import Footer from "./Footer";

function MainContent() {
  return (
    <div className="flex overflow-hidden flex-col bg-neutral-900">
      <Header />
      <main>
        <Hero />
        <EAPlaySection />
        <SubscriptionPlans />
        <div className="self-center mt-24 text-5xl font-bold tracking-normal leading-none text-center text-white max-md:mt-10 max-md:max-w-full">
          Что входит в подписку
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/f6ac3ad258c335540af601d260170e8d97770a42b569c34257ddea60a964e1a8?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          alt="Subscription features"
          className="object-contain self-center mt-12 ml-3 w-full rounded-none aspect-[3.05] max-w-[1276px] max-md:mt-10 max-md:max-w-full"
        />
        <Testimonials />
        <Newsletter />
      </main>
      <Footer />
    </div>
  );
}

export default MainContent;
