/**
 * This code was generated by Builder.io.
 */
import React from "react";

const paymentMethods = [
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/8ed1e33b9281c273b1dda0a8fe7bb88815e7487eb6894b0bc7b1e89625e4601b?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    alt: "Payment method 1",
    className: "w-10 aspect-[2]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/157be4ed29b4b94b07796916b0cace460e8f2afba7e2e5b88faf824d845c2fbb?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    alt: "Payment method 2",
    className: "w-11 aspect-[2.2]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/f02220f509be2520dc77919bae56f6349e836d16378f5c975cc735f37246038d?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    alt: "Payment method 3",
    className: "w-12 aspect-[2.4]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/2719be4f2bb7e200a2c2435146fe1ab6029b6e57669045ca4ae52694fb69ea5a?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    alt: "Payment method 4",
    className: "aspect-[1.75] w-[42px]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/0824b62c13da210ef9c37b84d9a0ff80ca6be82e21d4e618db468c01f8a2ff1c?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    alt: "Payment method 5",
    className: "w-9 aspect-[1.5]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/899e11ec39ca8eabbdf6ff9fdba386f3cc76798d8f96096f053c2c5140a98d66?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    alt: "Payment method 6",
    className: "aspect-[2.16] w-[52px]",
  },
];

function PaymentMethods() {
  return (
    <div className="flex gap-6">
      {paymentMethods.map((method, index) => (
        <img
          key={index}
          loading="lazy"
          src={method.src}
          alt={method.alt}
          className={`object-contain shrink-0 my-auto ${method.className}`}
        />
      ))}
    </div>
  );
}

export default PaymentMethods;
