/**
 * This code was generated by Builder.io.
 */
import React from "react";

function SocialIcons() {
  return (
    <div className="flex gap-2 self-start mt-4">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/9e6026c93497c05916de173ea3de67c0fbb215f5f28189918e1ffec1b564ccd3?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        alt="Social media icon 1"
        className="object-contain shrink-0 aspect-square fill-zinc-800 w-[42px]"
      />
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/fc98f7b2cc057874edd3a9f97cb549b5a21b0aff88f1a7c616164ae6c4b7012d?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        alt="Social media icon 2"
        className="object-contain shrink-0 aspect-square w-[42px]"
      />
    </div>
  );
}

export default SocialIcons;
