/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FAQItem from "./FAQItem";

const faqItems = [
  "Что представляет собой «Классика Ubisoft+»?",
  "Как мне оформить отдельную подписку на классику Ubisoft+?",
  "Подписка PlayStation Plus «Экстра» включает каталог игр классики Ubisoft+?",
  "Как мне установить игры из каталога «Классика Ubisoft+» по подписке?",
  "Как мне установить игры из каталога «Классика Ubisoft+» на моей консоли PlayStation 4?",
  "Что будет с моими сохраненными играми, если я отменю подписку?",
  "Что, если у меня уже есть подписка PlayStation Plus «Экстра» или «Люкс»?",
  "Что, если у меня уже есть подписка «Классика Ubisoft+», но я хочу подписаться на PlayStation Plus «Экстра» или «Люкс»?",
  "Сколько «Классика Ubisoft+» стоит на PlayStation?",
  "Где доступна «Классика Ubisoft+»?",
];

function FAQ() {
  return (
    <section className="mt-24 text-5xl font-bold tracking-normal leading-none text-center text-white max-md:mt-10 max-md:max-w-full">
      <h2>Ответы на вопросы</h2>
      <div className="flex flex-col mt-12 w-full text-base font-medium leading-loose max-w-[1252px] text-neutral-200 max-md:mt-10 max-md:max-w-full">
        {faqItems.map((item, index) => (
          <FAQItem key={index} question={item} />
        ))}
      </div>
    </section>
  );
}

export default FAQ;
