/**
 * This code was generated by Builder.io.
 */
import React from "react";

function FAQItem({ question }) {
  return (
    <div className="flex flex-wrap gap-10 justify-center px-4 py-5 w-full rounded bg-zinc-800 max-md:max-w-full">
      <div className="max-md:max-w-full">{question}</div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/4336a06fbc5a8ef535f025c73820bdb3d97764932cc9f5e472ff2bd7eaf38871?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        alt=""
        className="object-contain shrink-0 w-8 aspect-[2]"
      />
    </div>
  );
}

export default FAQItem;
