/**
 * This code was generated by Builder.io.
 */
import React from "react";

function GameCard() {
  return (
    <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow max-md:mt-2 max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/f4c8bafd3d24041b4e4128edee076666f2ef6a296b0cddd09c4bbc97f083de94?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          alt="Game cover"
          className="object-contain w-full aspect-[2.11] rounded-[40px] max-md:max-w-full"
        />
        <div className="flex flex-col items-start px-12 py-11 mt-2.5 w-full border border-solid bg-zinc-900 border-zinc-800 rounded-[40px] max-md:px-5 max-md:max-w-full">
          <h3 className="text-3xl font-bold tracking-normal leading-tight text-white">
            Assassin's Creed Valhalla
          </h3>
          <p className="mt-5 text-base tracking-normal leading-6 text-white w-[446px] max-md:max-w-full">
            Англия в эпоху викингов была раздробленной нацией мелких владык и
            враждующих королевств. Обуздайте хаос, и перед вами откроются
            богатые земли, ждущие завоевателя. Может быть, вас?
          </p>
          <div className="flex gap-2 mt-10">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/bdbce8223725f3dc17432d72e232767e0431302da0e1a72ac47c1aa6c4d1f5ab?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt="Platform icon 1"
              className="object-contain shrink-0 w-12 aspect-square fill-neutral-500"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/c189d9d7713e5fea785fbd6579cd81863c5ccf9c7fc6c167810822f5774d6c9d?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt="Platform icon 2"
              className="object-contain shrink-0 w-12 aspect-square fill-neutral-500"
            />
          </div>
        </div>
      </div>
    </div>
  );
}

export default GameCard;
