/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Hero() {
  return (
    <section className="flex relative flex-col items-center self-center mt-96 max-w-full text-center text-white w-[904px] max-md:mt-10">
      <h1 className="text-6xl font-black leading-[61px] max-md:max-w-full max-md:text-4xl max-md:leading-10">
        Подписка Ubisoft+ Classics
      </h1>
      <p className="mt-8 text-xl tracking-normal w-[636px] max-md:max-w-full">
        Сыграйте в тщательно подобранные игры из каталога отмеченных наградами
        игр Ubisoft, включая серии блокбастеров Assassin's Creed, Far Cry и Tom
        Clancy's Rainbow Six.
      </p>
    </section>
  );
}

export default Hero;
