/**
 * This code was generated by Builder.io.
 */
import React from "react";

function NavItem({ text, hasDropdown }) {
  return (
    <div className="flex gap-1 items-center">
      <div className="self-stretch my-auto">{text}</div>
      {hasDropdown && (
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/33c2b98cda6e5be318319541cc105a353120ea650a1d054f8aff2432fe72fa7b?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          alt=""
          className="object-contain shrink-0 self-stretch my-auto w-4 aspect-square"
        />
      )}
    </div>
  );
}

export default NavItem;
