/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Layout from "../components12/Layout";
import ArticleHeader from "../components12/ArticleHeader";
import ArticleImage from "../components12/ArticleImage";
import ArticleSection from "../components12/ArticleSection";
import CommentForm from "../components12/CommentForm";
import RelatedArticles from "../components12/RelatedArticles";

const articleData = {
  title: "Что показали на Xbox Games Showcase 2024 — Doom",
  date: "14 июля",
  author: "Marble",
  category: "Новости Xbox",
  mainImage:
    "https://cdn.builder.io/api/v1/image/assets/TEMP/f7502c5270fbf588a2bf43d40ebcedf57ad6948bde3f4285d875ba27d49715c1?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  sections: [
    {
      title: "Вступление в игры",
      content:
        "Психологический хоррор переплетается с шармом южной готики в леденящем душу переосмыслении культовой Alone in the Dark, ставшей эталоном жанра. Вам приоткроется дверь в мир безумия, где каждая встреча может оказаться последней. Вы ощутите, как с каждым шагом, что приближает вас к разгадке тайны Дерсето, взирающие из тьмы глаза становятся все голоднее. Каждая пуля чертит грань между выживанием и страшной смертью. Каждая следующая дверь может сулить беспросветный ужас, где нет ничего, кроме когтей, цепких щупалец и помешательства. Погрузитесь в межвоенную Луизиану, где эра упадка стала завесой для мрачной истории бегства от прошлых потрясений и бездушного общества в объятия чего-то темного — чего-то, что долгие века терпеливо ждало своего часа. Это Alone in the Dark, какой вы ее еще не видели, — искусный сплав элегантности южной готики и потустороннего безумия, отдающий дань уважения истокам, одновременно вознося нарратив жанра на новый уровень.",
    },
    {
      title: "Ужасающая история о тайнах и безумии",
      content:
        "Переступите порог поместья Дерсето, окутанного паутиной интриг и таящего страшное. Эмили Хартвуд и частный детектив Эдвардом Карнби отправляются на поиски истины. Эмили жаждет узнать правду об исчезновении дяди, а Эдварду предстоит раскрыть сложнейшее дело в своей жизни. Им обоим придется найти ответы на вопросы, которые они никогда не осмелились бы задать. Переосмысленная классика подарит вам незабываемое одиночное приключение, полное напряжения, ужасов и откровений, что потрясут границы воображения.",
    },
    {
      title: "Голливудские таланты",
      content:
        "Насладитесь мастерством известных актеров, способных как никто передать атмосферу хоррора на выживание, — Джоди Комер («Убивая Еву», «Главный герой») и Дэвида Харбора («Очень странные дела», «Черная вдова»). Хотя это их дебют в видеоиграх, Джоди и Дэвид безупречно вжились в роли Эмили Хартвуд и Эдварда Карнби, придав истории Alone in the Dark глубоко личных ноток — чтобы раскрыть все ее грани, игру нужно пройти дважды.",
    },
    {
      title: "Дань уважения родоначальникам жанра ужасов",
      content:
        "Снова ощутите сущность психологического хоррора в игре, что с почтением относится к оригиналу 1992 года, положившему начало жанру хоррора.",
    },
  ],
  relatedArticles: [
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/2d4b5f6253d1325ae3325691fd0fa7693efe5d91665d66dbe696760da855c912?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
      title: "Что показали на Xbox Games Showcase 2024 — Doom",
      date: "14 июля",
    },
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/2d4b5f6253d1325ae3325691fd0fa7693efe5d91665d66dbe696760da855c912?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
      title: "Что показали на Xbox Games Showcase 2024 — Doom",
      date: "14 июля",
    },
  ],
};

const ArticlePage = () => {
  return (
    <Layout>
      <article>
        <ArticleHeader
          title={articleData.title}
          date={articleData.date}
          author={articleData.author}
          category={articleData.category}
        />
        <ArticleImage src={articleData.mainImage} alt={articleData.title} />
        {articleData.sections.map((section, index) => (
          <ArticleSection
            key={index}
            title={section.title}
            content={section.content}
          />
        ))}
        <CommentForm />
        <RelatedArticles articles={articleData.relatedArticles} />
      </article>
    </Layout>
  );
};

export default ArticlePage;
