/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "../components11/Header";
import MainContent from "../components11/MainContent";
import Footer from "../components11/Footer";

function Blog() {
  return (
    <div className="flex overflow-hidden flex-col bg-neutral-900">
      <Header />
      <MainContent />
      <Footer />
    </div>
  );
}

export default Blog;
