/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "../components3/Header";
import PricingSection from "../components3/PricingSection";
import FeatureSection from "../components3/FeatureSection";
import SubscriptionSection from "../components3/SubscriptionSection";
import TestimonialSection from "../components3/TestimonialSection";
import NewsletterSection from "../components3/NewsletterSection";
import Footer from "../components3/Footer";

function DepositsPsnPage() {
  return (
    <div className="flex overflow-hidden flex-col bg-neutral-900">
      <Header />
      <PricingSection />
      <FeatureSection />
      <SubscriptionSection />
      <TestimonialSection />
      <NewsletterSection />
      <Footer />
    </div>
  );
}

export default DepositsPsnPage;
