/**
 * This code was generated by Builder.io.
 */
import React from "react";
import MainContent from "../components10/MainContent";

function EaPlay() {
  return (
    <div className="App">
      <MainContent />
    </div>
  );
}

export default EaPlay;
