/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Layout from "../components1/Layout";
import Hero from "../components1/Hero";
import GameGallery from "../components1/GameGallery";
import ViewAllPromotions from "../components1/ViewAllPromotions";
import PlayersChoice from "../components1/PlayersChoice";
import HotDeals from "../components1/HotDeals";
import ServiceHighlights from "../components1/ServiceHighlights";
import PlayStationSection from "../components1/PlayStationSection";
import XboxSection from "../components1/XboxSection";
import InGameCurrency from "../components1/InGameCurrency";
import InternetMentions from "../components1/InternetMentions";
import Testimonials from "../components1/Testimonials";
import Newsletter from "../components1/Newsletter";
import TelegramChannel from "../components1/TelegramChannel";

const HomePage = () => {
  return (
    <Layout>
      <Hero />
      <GameGallery />
      <ViewAllPromotions />
      <PlayersChoice />
      <HotDeals />
      <ServiceHighlights />
      <PlayStationSection />
      <XboxSection />
      <InGameCurrency />
      <InternetMentions />
      <Testimonials />
      <div className="mt-5 w-full max-w-[1252px] max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <Newsletter />
          <TelegramChannel />
        </div>
      </div>
    </Layout>
  );
};

export default HomePage;
