/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "../components7/Header";
import Footer from "../components7/Footer";
import HeroSection from "../components7/HeroSection";
import PrivilegesSection from "../components7/PrivilegesSection";
import JoinMethodsSection from "../components7/JoinMethodsSection";
import AccountLevelsSection from "../components7/AccountLevelsSection";
import NewbieAccountSection from "../components7/NewbieAccountSection";
import CallToActionSection from "../components7/CallToActionSection";

function PremiumClub() {
  return (
    <div className="flex overflow-hidden flex-col items-center bg-neutral-900">
      <Header />
      <main>
        <HeroSection />
        <PrivilegesSection />
        <JoinMethodsSection />
        <AccountLevelsSection />
        <NewbieAccountSection />
        <CallToActionSection />
      </main>
      <Footer />
    </div>
  );
}

export default PremiumClub;
