/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Layout from "../components6/Layout";
import Hero from "../components6/Hero";
import PricingSection from "../components6/PricingSection";
import StarterPackSection from "../components6/StarterPackSection";
import GameSelection from "../components6/GameSelection";
import SubscriptionSection from "../components6/SubscriptionSection";
import CheckoutSection from "../components6/CheckoutSection";
import TestimonialSection from "../components6/TestimonialSection";
import NewsletterSection from "../components6/NewsletterSection";

const PsAccountMain = () => {
  return (
    <Layout>
      <Hero />
      <PricingSection />
      <StarterPackSection />
      <GameSelection />
      <SubscriptionSection />
      <CheckoutSection />
      <TestimonialSection />
      <NewsletterSection />
    </Layout>
  );
};

export default PsAccountMain;
