/**
 * This code was generated by Builder.io.
 */
import React from "react";
import MainLayout from "../components4/MainLayout";

function PsAccount() {
  return <MainLayout />;
}

export default PsAccount;
