/**
 * This code was generated by Builder.io.
 */
import React from "react";
import MainContent from "../components5/MainContent";

function PsSet() {
  return (
    <div className="App">
      <MainContent />
    </div>
  );
}

export default PsSet;
