/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "../components8/Header";
import MainContent from "../components8/MainContent";
import Footer from "../components8/Footer";

function Stocks() {
  return (
    <div className="flex overflow-hidden flex-col items-center bg-neutral-900">
      <Header />
      <MainContent />
      <Footer />
    </div>
  );
}

export default Stocks;
