/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Layout from "../components13/Layout";
import Hero from "../components13/Hero";
import GameSection from "../components13/GameSection";
import HowItWorks from "../components13/HowItWorks";
import TurkishRegion from "../components13/TurkishRegion";
import GamePassInfo from "../components13/GamePassInfo";
import GamePassPlans from "../components13/GamePassPlans";
import GameCatalog from "../components13/GameCatalog";
import AccountTopUp from "../components13/AccountTopUp";
import NewGames from "../components13/NewGames";
import ReleaseGames from "../components13/ReleaseGames";
import Guarantees from "../components13/Guarantees";
import FAQ from "../components13/FAQ";
import Testimonials from "../components13/Testimonials";
import Newsletter from "../components13/Newsletter";

function XboxPage() {
  return (
    <Layout>
      <Hero />
      <GameSection />
      <HowItWorks />
      <TurkishRegion />
      <GamePassInfo />
      <GamePassPlans />
      <GameCatalog />
      <AccountTopUp />
      <NewGames />
      <ReleaseGames />
      <Guarantees />
      <FAQ />
      <Testimonials />
      <Newsletter />
    </Layout>
  );
}

export default XboxPage;
