/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ArticleImage = ({ src, alt }) => {
  return (
    <figure className="flex overflow-hidden flex-col justify-end mt-5 rounded-3xl border border-solid bg-neutral-800 border-white border-opacity-10 max-md:max-w-full">
      <img
        loading="lazy"
        src={src}
        alt={alt}
        className="object-contain w-full aspect-[1.91] max-md:max-w-full"
      />
    </figure>
  );
};

export default ArticleImage;
