/**
 * This code was generated by Builder.io.
 */
import React from "react";

const CommentForm = () => {
  return (
    <section className="flex flex-col px-10 py-11 mt-20 w-full rounded-3xl bg-neutral-800 max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <h2 className="self-start text-3xl font-semibold tracking-tight leading-none text-white">
        Оставить комментарий
      </h2>
      <form className="mt-8">
        <div className="flex flex-wrap gap-1.5 text-sm leading-loose text-neutral-200 max-md:max-w-full">
          <input
            type="text"
            placeholder="Ваше имя"
            aria-label="Ваше имя"
            className="overflow-hidden grow px-4 py-3.5 rounded-xl border-2 border-solid border-zinc-800 w-fit max-md:pr-5"
          />
          <input
            type="email"
            placeholder="Почта"
            aria-label="Почта"
            className="overflow-hidden grow px-4 py-3.5 whitespace-nowrap rounded-xl border-2 border-solid border-zinc-800 w-fit max-md:pr-5"
          />
        </div>
        <textarea
          placeholder="Текст комментария"
          aria-label="Текст комментария"
          className="overflow-hidden px-4 pt-3.5 pb-20 mt-1.5 w-full text-sm leading-loose rounded-xl border-2 border-solid border-zinc-800 text-neutral-200 max-md:pr-5 max-md:pb-28 max-md:max-w-full"
        ></textarea>
        <div className="flex flex-wrap gap-5 justify-between mt-5 w-full max-md:max-w-full">
          <button
            type="submit"
            className="gap-2.5 self-stretch px-8 py-4 text-base font-bold leading-tight text-center text-black whitespace-nowrap bg-lime-400 min-h-[50px] rounded-[100px] max-md:px-5"
          >
            Опубликовать
          </button>
          <div className="flex gap-8 my-auto text-sm leading-loose text-right text-neutral-200 max-md:max-w-full">
            <label htmlFor="rating" className="flex-auto my-auto">
              Насколько вам понравился материал?
            </label>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/ca1b2ce3729910cd10c2cbc0da0ab20ff5bf27f0baaa96f8cf956139dd8a2b99?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt="Rating stars"
              id="rating"
              className="object-contain shrink-0 max-w-full rounded-sm aspect-[5.52] w-[166px]"
            />
          </div>
        </div>
      </form>
    </section>
  );
};

export default CommentForm;
