/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Link } from "react-router-dom";

const Header = () => {
  return (
    <header className="flex flex-col pt-4 w-full bg-neutral-900 bg-opacity-60 max-md:max-w-full">
      <div className="flex gap-5 justify-between items-center self-center w-full max-w-[1252px] max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/6d641deacf194df02ed2065b19fdce97a031e3f2f70393d4fe04466b09343e57?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          alt="Company logo"
          className="object-contain shrink-0 self-stretch max-w-full aspect-[3.72] w-[156px]"
        />
        <nav className="flex flex-wrap gap-10 self-stretch my-auto text-sm leading-loose max-md:max-w-full">
          <div className="flex flex-auto gap-10 items-start my-auto whitespace-nowrap text-neutral-200 max-md:max-w-full">
            <Link to="/catalog">каталог</Link>
            <div className="flex gap-1 items-center">
              <Link to="/subscriptions">подписки</Link>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/33c2b98cda6e5be318319541cc105a353120ea650a1d054f8aff2432fe72fa7b?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                alt=""
                className="object-contain shrink-0 self-stretch my-auto w-4 aspect-square"
              />
            </div>
            <Link to="/blog">блог</Link>
            <div className="flex gap-1 items-center">
              <Link to="/accounts">аккаунты</Link>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/33c2b98cda6e5be318319541cc105a353120ea650a1d054f8aff2432fe72fa7b?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                alt=""
                className="object-contain shrink-0 self-stretch my-auto w-4 aspect-square"
              />
            </div>
            <div className="flex gap-1 items-center">
              <Link to="/balance">баланс</Link>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/33c2b98cda6e5be318319541cc105a353120ea650a1d054f8aff2432fe72fa7b?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                alt=""
                className="object-contain shrink-0 self-stretch my-auto w-4 aspect-square"
              />
            </div>
          </div>
          <button className="overflow-hidden gap-2.5 self-stretch px-5 pt-1.5 pb-2 font-medium text-center text-black bg-lime-400 rounded-[100px]">
            оформить подписку
          </button>
        </nav>
        <div className="flex gap-2.5 self-stretch my-auto">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/67c7c8046a64f55a9a58df4d8198fb23627937744d63f32cbadf9d4b2308b99b?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Social media icon"
            className="object-contain shrink-0 aspect-square w-[38px]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/57f9aaab2cbef3b4966c1fd1c13abdba381cf50f946e6f9c66e3b376411dab41?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Social media icon"
            className="object-contain shrink-0 aspect-square w-[38px]"
          />
        </div>
      </div>
      <div className="flex mt-3.5 w-full bg-neutral-800 min-h-[1px] max-md:max-w-full" />
    </header>
  );
};

export default Header;
