/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Footer from "./Footer";

const Layout = ({ children }) => {
  return (
    <div className="flex overflow-hidden flex-col bg-neutral-900">
      <Header />
      <main className="flex flex-col self-center mt-6 max-w-full w-[828px]">
        {children}
      </main>
      <Footer />
    </div>
  );
};

export default Layout;
