/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ArticleCard = ({ image, title, date }) => (
  <article className="flex overflow-hidden flex-col grow items-start px-2 pt-2 pb-6 w-full rounded-3xl bg-neutral-800 max-md:mt-5">
    <div className="flex overflow-hidden flex-col self-stretch rounded-xl bg-zinc-800">
      <img
        loading="lazy"
        src={image}
        alt={title}
        className="object-contain w-full aspect-[1.47]"
      />
    </div>
    <h3 className="mt-4 text-2xl font-medium leading-8 text-ellipsis text-neutral-200 max-md:ml-2">
      {title}
    </h3>
    <time className="mt-1 text-sm font-medium leading-7 text-neutral-400 max-md:ml-2">
      {date}
    </time>
  </article>
);

const RelatedArticles = ({ articles }) => {
  return (
    <section className="mt-20 max-md:mt-10">
      <h2 className="self-start text-3xl font-semibold tracking-tight leading-none text-white">
        Больше статей по теме
      </h2>
      <div className="mt-8 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          {articles.map((article, index) => (
            <div
              key={index}
              className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full"
            >
              <ArticleCard {...article} />
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default RelatedArticles;
