/**
 * This code was generated by Builder.io.
 */
import React from "react";

function AccountCard({ title, description, buttonText, price, iconSrc }) {
  return (
    <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
      Continuing from where we left off:
      <div className="flex relative flex-wrap grow gap-1.5 px-10 py-11 w-full font-bold bg-white border border-solid border-white border-opacity-10 rounded-[30px] max-md:px-5 max-md:mt-2">
        <div className="flex flex-col grow shrink-0 items-start basis-0 w-fit max-md:max-w-full">
          <h3 className="text-3xl tracking-normal leading-9 text-black">
            {title}
          </h3>
          <p className="self-stretch mt-5 text-base tracking-normal leading-6 text-black max-md:max-w-full">
            {description}
          </p>
          <div className="flex gap-10 mt-12 max-w-full w-[437px] max-md:mt-10">
            <button className="overflow-hidden gap-2.5 self-stretch px-8 py-5 text-base leading-none text-center text-white bg-rose-500 min-h-[60px] rounded-[1000px] max-md:px-5">
              {buttonText}
            </button>
            <div className="grow shrink text-6xl leading-none text-zinc-800 w-[142px] max-md:text-4xl">
              {price}
            </div>
          </div>
        </div>
        <img
          loading="lazy"
          src={iconSrc}
          alt=""
          className="object-contain shrink-0 self-start aspect-[1.3] w-[70px]"
        />
      </div>
    </div>
  );
}

export default AccountCard;
