/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ActionButton({ text, primary = false }) {
  const baseClasses =
    "overflow-hidden gap-2.5 self-stretch py-4 pr-7 pl-7 min-h-[50px] rounded-[1000px] max-md:px-5";
  const colorClasses = primary
    ? "bg-lime-400 text-black"
    : "bg-white text-black";

  return <button className={`${baseClasses} ${colorClasses}`}>{text}</button>;
}

export default ActionButton;
