/**
 * This code was generated by Builder.io.
 */
import React from "react";

function FAQItem({ question, iconSrc }) {
  return (
    <div className="flex flex-wrap gap-10 justify-center px-4 py-5 w-full rounded bg-zinc-800 max-md:max-w-full">
      <div className="max-md:max-w-full">{question}</div>
      <img
        loading="lazy"
        src={iconSrc}
        alt=""
        className="object-contain shrink-0 self-start w-8 aspect-[2]"
      />
    </div>
  );
}

export default FAQItem;
