/**
 * This code was generated by Builder.io.
 */
import React from "react";
import GameCard from "./GameCard";

const games = [
  {
    title: "Star Wars Outlaws",
    price: "9 490 ₽",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/1db612b45ac8aea299ffa9be53fb7116a8c8f7f733e77088ceb12e4fe9ec6b16?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    title: "Death's Door",
    price: "2 690 ₽",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/4ee7bdf7c3ba4327304c3aa712708bba8a6abab3f2cfdb4e3be174ebd82e3ac3?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    title: "God of War Ragnarök",
    price: "9 490 ₽",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/5687194c40331e1940902bea5c033a5d6cbba8302e742a00fb92643f1eb10e11?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    title: "Doki Doki Literature Club Plus!",
    price: "1 290 ₽",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/e91f0f3f6451d9b23461bcb44a789dfef2108565c5cebcc9e30e733ad8027fb1?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
];

function GameCatalog() {
  return (
    <section className="mt-32 max-md:mt-10 max-md:max-w-full">
      <h2 className="text-5xl font-bold tracking-tight leading-none text-white max-md:text-4xl">
        Каталог игр
      </h2>
      <div className="mt-10 w-full max-w-[1252px] max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          {games.map((game, index) => (
            <GameCard key={index} {...game} />
          ))}
        </div>
      </div>
      <button className="overflow-hidden gap-2.5 self-stretch px-5 py-3.5 mt-10 ml-3 max-w-full text-sm font-medium leading-loose text-center text-white border border-white border-solid min-h-[50px] rounded-[100px] w-[346px]">
        Показать еще
      </button>
    </section>
  );
}

export default GameCatalog;
