/**
 * This code was generated by Builder.io.
 */
import React from "react";

const guarantees = [
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/9c0de0d5875eac7e16f15c48b5c5481f2ae289162391de8b15867821c733e4cc?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/7eb9d9de5171cdcf13a19a7a12d0a69c5f720d3e937e3a9b1e872a67e2dfa1e3?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/8dc0c1182ade19827b991c9dd4018853f2e6706712625b48415c84e6075355f7?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/e60f74d71e71ffc39fa2aed5d93bc31ae8cf7b347b2aab78a181c50da9a8c80f?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/5cebb09d07e0f0fd7d122300ba1c48b5881df212babacd1c8de12b92b81151db?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
];

function Guarantees() {
  return (
    <section className="flex flex-wrap gap-4 self-end mt-32 w-full max-w-[1300px] max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-col grow shrink-0 items-center self-start basis-0 w-fit max-md:max-w-full">
        <h2 className="text-5xl font-bold leading-none text-center text-white max-md:text-4xl">
          Наши гарантии
        </h2>
        <div className="self-stretch mt-11 max-md:mt-10 max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            {guarantees.slice(0, 3).map((guarantee, index) => (
              <div
                key={index}
                className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full"
              >
                <img
                  loading="lazy"
                  src={guarantee.image}
                  alt={`Guarantee ${index + 1}`}
                  className="object-contain grow w-full rounded-none aspect-[2.34] max-md:mt-4"
                />
              </div>
            ))}
          </div>
        </div>
        <div className="max-w-full w-[767px]">
          <div className="flex gap-5 max-md:flex-col">
            {guarantees.slice(3).map((guarantee, index) => (
              <div
                key={index}
                className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full"
              >
                <img
                  loading="lazy"
                  src={guarantee.image}
                  alt={`Guarantee ${index + 4}`}
                  className="object-contain grow w-full rounded-none aspect-[2.34] max-md:mt-4"
                />
              </div>
            ))}
          </div>
        </div>
      </div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/3aca1d7997c0187240167a4a05824c7a7b408478dccb991c2e51d9f0d749ef99?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        alt=""
        className="object-contain shrink-0 max-w-full aspect-[0.27] w-[123px]"
      />
    </section>
  );
}

export default Guarantees;
