/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ActionButton from "./ActionButton";

function Hero() {
  return (
    <section className="flex flex-col items-center self-stretch px-20 pb-24 mt-28 w-full rounded-[40px] max-md:px-5 max-md:pb-24 max-md:mt-10 max-md:max-w-full">
      <div className="flex z-10 flex-col mt-0 mb-0 max-w-full w-[904px] max-md:mb-2.5">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/14bed20eb0fd1decb7f6ac42a97552fbb66a3aba1330ed76e1470f8f57839274?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          alt="PlayStation logo"
          className="object-contain self-center max-w-full rounded-none aspect-square w-[153px]"
        />
        <div className="flex flex-col items-center mt-8 text-center text-white max-md:max-w-full">
          <h1 className="text-6xl font-black leading-[61px] max-md:max-w-full max-md:text-4xl max-md:leading-10">
            Покупай игры и подписки для PlayStation
          </h1>
          <p className="mt-8 text-xl tracking-normal w-[406px]">
            Оформи подписку Playstation Plus на свою почту без VPN и заморочек
          </p>
        </div>
        <div className="flex gap-2.5 self-center mt-12 max-w-full text-base font-bold leading-tight text-center text-black w-[422px] max-md:mt-10">
          <ActionButton text="Оформить подписку" primary />
          <ActionButton text="Купить игру" />
        </div>
        <div className="flex flex-wrap gap-10 items-center mt-28 mr-7 ml-7 max-md:mt-10 max-md:mr-2.5 max-md:max-w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/a0766a7cf17d7de23bdccb99795a327d8d4b52181ba804a1ec4abcb31bc771af?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Partner logo"
            className="object-contain shrink-0 self-stretch my-auto aspect-[5.49] w-[187px]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/8aab28cabc53e3d81c9ff4bd40c57e424c595f383ffe73c3d8328d823f675b0d?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Partner logo"
            className="object-contain shrink-0 self-stretch my-auto aspect-[6.8] w-[163px]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/2711ca3a36f75477f4dfc1b97886e1f76920a535730e0887d19876c4a22ea9b0?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Partner logo"
            className="object-contain shrink-0 self-stretch my-auto aspect-[5.24] w-[178px]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/48b6514d4dcd6b7f5b9cd2a0eba9e83a6d2b0212ebbf290637417b6219249cdd?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Partner logo"
            className="object-contain shrink-0 self-stretch my-auto aspect-[5.08] w-[173px]"
          />
        </div>
      </div>
    </section>
  );
}

export default Hero;
