/**
 * This code was generated by Builder.io.
 */
import React from "react";
import StepCard from "./StepCard";

const steps = [
  {
    number: 1,
    title: "Выбери товар",
    description:
      "Выбери любой товар на сайте, будь то подписка, игра, дополнение или игровая валюта.",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/314562e967139ff06b628f5c8becdb267b62f9ff513e2cf5b17a1b9a99c781af?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    number: 2,
    title: "Авторизируйся",
    description:
      "Зарегистрируйся в личном кабинете за пару кликов, чтобы экономить время, для следующих покупок.",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/3a1a8b6b1b1e512001089fbcb94a426818aecae73fa55526317a588193ed013d?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    number: 3,
    title: "Оплати",
    description:
      "Оплати выбранные товары одним из удобных тебе способов: Visa, МИР, Яндекс, Мастеркард, МТС, СБП.",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/dc3506f2bd2b6002e6ddec5c7cd8b609e67812b979edb1cf22e5e0e86e95f593?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    number: 4,
    title: "Перейди",
    description:
      "Переходи в нашего бота после покупки для уточнения деталей твоего заказа.",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/aa20a1e5a2f5040ee95b9d3a3db957093193a9d3e7318c896c589574fe28afdf?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    number: 5,
    title: "Напиши",
    description:
      "Передай данные твоего логина и пароля от аккаунта или почту на которую нужно создать новый аккаунт нашему оператору.",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/65b717f2a14df0b8b07eb7367892c278fe372e9d1aef3b08e92f7c931df16150?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    number: 6,
    title: "Играй",
    description:
      "Наслаждайся купленной игрой. И не забывай что наше сообщество всегда подскажет тебе самые лушие цены на твои любимые игры.",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/f5ea57c12b7c68abf2ce9dc35765f33dbcd1ca0d82f25516f97d83e26abbcb3e?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
];

function HowItWorks() {
  return (
    <section className="mt-24 max-md:mt-10 max-md:max-w-full">
      <h2 className="text-5xl font-bold leading-none text-center text-white max-md:max-w-full max-md:text-4xl">
        Как это работает?
      </h2>
      <div className="flex flex-wrap gap-5 justify-between mt-10 w-full max-w-[1015px] max-md:max-w-full">
        {steps.map((step, index) => (
          <StepCard key={index} {...step} isEven={index % 2 === 0} />
        ))}
      </div>
    </section>
  );
}

export default HowItWorks;
