/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Footer from "./Footer";

function Layout({ children }) {
  return (
    <div className="flex overflow-hidden flex-col items-center bg-neutral-900">
      <Header />
      <main className="flex flex-col items-center w-full">{children}</main>
      <Footer />
    </div>
  );
}

export default Layout;
