/**
 * This code was generated by Builder.io.
 */
import React from "react";
import GameCard from "./GameCard";

const monthlyGames = [
  {
    title: "Borderlands 3",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/e1aadcb5cee1b17449203b9dae305e7e06eb697ea14a805bfee80471bd6fb2e9?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    title: "EA SPORTS™ NHL® 24",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/795ef3e471896c205471540f7d76aa73c436fb7c0c93b8fc5cd24be7e4a55b1f?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    title: "Among US",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/7480e27a8b0563a24e81b3b3dd6fe82cd1df2da133473de67fe44fdbeff5e09e?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
];

function MonthlyGames() {
  return (
    <section className="mt-32 max-md:mt-10 max-md:max-w-full">
      <h2 className="text-5xl font-bold leading-none text-center text-white max-md:max-w-full max-md:text-4xl">
        Новые игры в подписке этого месяца
      </h2>
      <p className="mt-5 text-xl leading-8 text-center text-white w-[636px] max-md:max-w-full">
        Забери эти игры бесплатно прямо сейчас. Эти игры входят <br />в
        следующие типы подписок:
      </p>
      <div className="flex flex-wrap gap-5 mt-10 max-w-full text-base font-bold text-center text-yellow-500 whitespace-nowrap tracking-[3.2px] w-[708px]">
        <div className="px-16 py-1 border border-white border-solid max-md:px-5">
          DELUXE
        </div>
        <div className="px-16 py-1 border border-yellow-500 border-solid max-md:px-5">
          EXTRA
        </div>
        <div className="px-14 py-1 text-white border border-white border-solid max-md:px-5">
          ESSENTIAL
        </div>
      </div>
      <div className="mt-10 max-w-full w-[934px]">
        <div className="flex gap-5 max-md:flex-col">
          {monthlyGames.map((game, index) => (
            <div
              key={index}
              className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full"
            >
              <div className="flex overflow-hidden flex-col px-2 pt-2 pb-6 mx-auto w-full rounded-3xl bg-neutral-800 max-md:mt-5">
                <div className="flex overflow-hidden flex-col items-center rounded-xl aspect-square bg-zinc-800">
                  <img
                    loading="lazy"
                    src={game.image}
                    alt={game.title}
                    className="object-contain w-full aspect-square"
                  />
                </div>
                <div className="self-start mt-3 text-base font-medium leading-loose whitespace-nowrap text-ellipsis text-neutral-200 max-md:ml-2">
                  {game.title}
                </div>
                <button className="overflow-hidden gap-2.5 self-stretch px-8 py-4 mx-4 mt-10 text-base font-bold leading-tight text-center text-black bg-lime-400 min-h-[50px] rounded-[1000px] max-md:px-5 max-md:mx-2.5">
                  Забрать игру
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

export default MonthlyGames;
