/**
 * This code was generated by Builder.io.
 */
import React from "react";
import GameCard from "./GameCard";

const newGames = [
  {
    title: "Remnant II",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/f54bebbfaab95d770f07aa3c5c634ee72d604b77b2bfeeed340740ea3d244c90?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    title: "CRISIS CORE –FINAL FANTASY VII– REUNION",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/256c693197cab62ee55fffe9372ceb819d8826eb2dac83aa0cdeed05ce8ab389?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    title: "Mount & Blade II: Bannerlord",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/b8036a8682af0b462909bd41cc6eb9d86a1839f5f003163bf2feb79d3fd29ae6?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    title: "The Jackbox Party Pack Part 9",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/e2879ad1f9177a70a3cb541c918b30ede02bde6b4944afe64f9d9cd1a656edf5?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
];

function NewGamesInCatalog() {
  return (
    <section className="mt-24 max-md:mt-10 max-md:max-w-full">
      <h2 className="text-5xl font-bold leading-none text-center text-white max-md:max-w-full max-md:text-4xl">
        Новые игры в игровом каталоге
      </h2>
      <p className="mt-5 text-xl leading-8 text-center text-white w-[636px] max-md:max-w-full">
        Играй в эти игры бесплатно прямо сейчас. Эти игры входят <br />в
        следующие типы подписок:
      </p>
      <div className="flex gap-5 mt-10 max-w-full text-base font-bold text-center text-yellow-500 whitespace-nowrap tracking-[3.2px] w-[466px]">
        <div className="px-16 py-1 border border-white border-solid max-md:px-5">
          DELUXE
        </div>
        <div className="px-16 py-1 border border-yellow-500 border-solid max-md:px-5">
          EXTRA
        </div>
      </div>
      <div className="flex flex-col self-stretch pl-20 mt-10 w-full max-md:pl-5 max-md:max-w-full">
        <div className="w-full max-w-[1252px] max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            {newGames.map((game, index) => (
              <div
                key={index}
                className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full"
              >
                <div className="flex overflow-hidden flex-col px-2 pt-2 pb-6 mx-auto w-full rounded-3xl bg-neutral-800 max-md:mt-5">
                  <div className="flex overflow-hidden flex-col items-center rounded-xl aspect-square bg-zinc-800">
                    <img
                      loading="lazy"
                      src={game.image}
                      alt={game.title}
                      className="object-contain w-full aspect-square"
                    />
                  </div>
                  <div className="self-start mt-3 text-base font-medium leading-loose whitespace-nowrap text-ellipsis text-neutral-200 max-md:ml-2">
                    {game.title}
                  </div>
                  <button className="overflow-hidden gap-2.5 self-stretch px-8 py-4 mx-4 mt-16 text-base font-bold leading-tight text-center text-black bg-lime-400 min-h-[50px] rounded-[1000px] max-md:px-5 max-md:mx-2.5 max-md:mt-10">
                    Играть бесплатно
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
        <button className="overflow-hidden gap-2.5 self-center px-5 py-3.5 mt-10 max-w-full text-sm font-medium leading-loose text-center text-white border border-white border-solid min-h-[50px] rounded-[100px] w-[346px]">
          Смотреть все игры
        </button>
      </div>
    </section>
  );
}

export default NewGamesInCatalog;
