/**
 * This code was generated by Builder.io.
 */
import React from "react";
import TopUpCard from "./TopUpCard";

const topUpOptions = [
  {
    amount: "500 лир",
    price: "2500 ₽",
    bgImage:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/fe274e07d5b2c4fbd3588ef560a9595ecfb030a931ea61cb8e48544739fe8b9a?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    amount: "1500 лир",
    price: "7500 ₽",
    bgImage:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/a82a3434f4a0024100edbe7b3b4fbc61c54e26b5174c435b04c6df898f0ca3ee?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    amount: "2500 лир",
    price: "12500 ₽",
    bgImage:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/2a3e6c33509fdfaff24e8f6f963a6ad30e15d791aec563fbb1505ac4e2f74a60?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
];

function PlaystationTopUp() {
  return (
    <section className="mt-28 max-md:mt-10">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/5548fd65a0a879d4a3a1f2f542910e1372beca114d5a7b2714cb19d8f274d189?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        alt=""
        className="object-contain mt-28 rounded-none aspect-square w-[50px] max-md:mt-10"
      />
      <h2 className="mt-3.5 text-5xl font-bold text-center text-white leading-[50px] w-[774px] max-md:max-w-full">
        Пополни аккаунт Playstation <br /> на любую сумму
      </h2>
      <div className="mt-5 w-full max-w-[1252px] max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          {topUpOptions.map((option, index) => (
            <TopUpCard key={index} {...option} />
          ))}
          <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col px-12 py-9 w-full font-bold text-center rounded-xl max-md:px-5 max-md:mt-5">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/89c3ff6db9d582360f2174d738a32504559834f68ec9c47e6e3485d4ada89064?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                alt="PlayStation Store logo"
                className="object-contain self-center w-24 aspect-[3]"
              />
              <div className="mt-14 text-6xl tracking-tight text-white leading-[54px] max-md:mt-10 max-md:mr-1.5 max-md:ml-1.5 max-md:text-4xl max-md:leading-10">
                Любая <br /> сумма
              </div>
              <button className="overflow-hidden gap-2.5 self-stretch px-8 py-4 mt-14 text-base leading-tight text-black bg-white min-h-[50px] rounded-[1000px] max-md:px-5 max-md:mt-10">
                Написать нам
              </button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

export default PlaystationTopUp;
