/**
 * This code was generated by Builder.io.
 */
import React from "react";
import PSPlusFeature from "./PSPlusFeature";

const features = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/4b40e891166fb4a0f2451eaee884a60c5cb22d2d33f6251791ece79e2f7bce91?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Многопользовательский режим",
    description: "Открой сетевой многопользовательский режим",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/48a9a1d4e8cabc1c2608ac037a2f1c080b678a40de8c1122926fc7d709dabc16?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Ранний доступ",
    description:
      "Играй в демоверсии игр и получай ранний доступ к бета-версиям",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/7cc806154c4b68181400afcc402ef28a97e8cb40cad0d73b881cc028aeaecac4?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Обратная совместимость",
    description: "Играй в избранные игры с предыдущих поколений PlayStation",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/c28bc345dc6fd7c0f97ec3b0001f53679b0818a2b8cd1f8b25522ed84c272d39?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Ежемесячные игры",
    description: "Получай доступ к бесплатным играм каждый месяц",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/8cd16ecf156250d0b5420c3d1b4379f7e6926381f8d722820d74018ccd5cb35c?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Внутриигровые дополнения",
    description: "Получай эксклюзивные внутриигровые дополнения и бонусы",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/2f6659a37f0a7bf60bce908abe38ea1786d155721e009c6a3671d345e1d0d81f?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Эксклюзивные скидки",
    description: "Пользуйся эксклюзивными скидками в PlayStation Store",
  },
];

function PSPlusSection() {
  return (
    <section className="flex relative flex-col justify-center items-center px-20 py-20 mt-5 w-full rounded-none max-w-[1400px] min-h-[845px] max-md:px-5 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/dfcc970738ceb2237453b7053c8e76121e4cf66e512725c3d7acd0a3c5b2ec6c?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        alt="Background"
        className="object-cover absolute inset-0 size-full"
      />
      <div className="flex relative flex-col w-full max-w-[1141px] max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/c65c0d36e7eb6251fcae05844e3e6236624d619939fd0255cdb3fbd4d1228de2?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          alt=""
          className="object-contain self-center rounded-none aspect-square w-[50px]"
        />
        <h2 className="self-center mt-2.5 text-5xl font-bold leading-none text-center text-white">
          Что такое PS Plus?
        </h2>
        <div className="mt-10 max-md:max-w-full">
          <div className="flex flex-wrap gap-5 justify-between">
            {features.map((feature, index) => (
              <PSPlusFeature key={index} {...feature} />
            ))}
          </div>
        </div>
        <button className="overflow-hidden px-16 py-6 mt-16 text-base font-bold leading-none text-center text-black bg-lime-400 rounded-[1000px] max-md:px-5 max-md:mt-10">
          Оформить подписку
        </button>
      </div>
    </section>
  );
}

export default PSPlusSection;
