/**
 * This code was generated by Builder.io.
 */
import React from "react";

function StepCard({ number, title, description, imageSrc, isEven }) {
  return (
    <div
      className={`flex flex-col ${isEven ? "" : "items-end"} max-md:max-w-full`}
    >
      <img
        loading="lazy"
        src={imageSrc}
        alt={`Step ${number} illustration`}
        className="object-contain w-full rounded-2xl aspect-[1.79] max-md:mr-0.5 max-md:max-w-full"
      />
      <div
        className={`flex flex-col ${
          isEven ? "self-end" : "self-start"
        } mt-24 max-w-full whitespace-nowrap w-[231px] max-md:mt-10`}
      >
        <div
          className={`${
            isEven ? "self-end" : "self-start"
          } px-3.5 py-3 text-base font-medium leading-loose text-center text-lime-400 rounded-full border-2 border-lime-400 border-solid stroke-[2px] stroke-lime-400`}
        >
          {number}
        </div>
        <div
          className={`mt-3.5 text-3xl font-bold leading-none ${
            isEven ? "text-right" : "text-left"
          } text-white max-md:mr-0.5`}
        >
          {title}
        </div>
      </div>
      <div
        className={`mt-4 ${isEven ? "ml-10" : "mr-10"} text-lg leading-7 ${
          isEven ? "text-right" : "text-left"
        } text-white max-md:mr-0.5 max-md:ml-2.5`}
      >
        {description}
      </div>
    </div>
  );
}

export default StepCard;
