/**
 * This code was generated by Builder.io.
 */
import React from "react";

function TariffCard({ name, description, color, bgColor, features, price }) {
  return (
    <div className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full">
      <div
        className={`flex flex-col grow items-start pt-10 pr-20 pb-7 pl-8 w-full tracking-normal ${bgColor} rounded-3xl max-md:px-5 max-md:mt-8`}
      >
        <h3 className={`text-3xl font-bold leading-none ${color}`}>{name}</h3>
        <p className="mt-2.5 text-sm text-white">{description}</p>
      </div>
      <div className="flex flex-col items-start px-8 pt-6 pb-9 mx-auto w-full font-bold text-white rounded-3xl bg-zinc-900 max-md:px-5 max-md:mt-8">
        <ul className="flex gap-5 text-lg leading-8">
          <div className="basis-auto">
            {features.map((feature, index) => (
              <li
                key={index}
                className={
                  feature.includes("Каталог Классики") ||
                  feature.includes("Демо версии игр") ||
                  feature.includes("Облачный стриминг") ||
                  feature.includes("Каталог фильмов Sony")
                    ? "font-extrabold text-lime-400"
                    : ""
                }
              >
                {feature}
              </li>
            ))}
          </div>
        </ul>
        <div className="mt-16 ml-2.5 text-4xl tracking-tight leading-none max-md:mt-10">
          {price}
        </div>
        <button className="overflow-hidden gap-2.5 self-stretch px-5 py-3.5 mt-5 ml-2.5 text-base leading-none text-center text-black bg-lime-400 min-h-[50px] rounded-[100px]">
          Добавить в корзину
        </button>
      </div>
    </div>
  );
}

export default TariffCard;
