/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function Footer() {
  return (
    <footer className="flex overflow-hidden flex-col items-center px-20 pb-10 mt-36 w-full bg-neutral-900 max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="flex shrink-0 max-w-full h-px bg-neutral-800 w-[1252px]" />
      <div className="flex flex-wrap gap-10 self-start mt-16 w-full max-w-[1186px] max-md:mt-10 max-md:max-w-full">
        <div className="flex flex-col self-start">
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/ca0d1609fc69ed41f5488443cec54775125ad94de0e480ed798b8ce67efeed02?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c" alt="Company logo" className="object-contain max-w-full aspect-[3.72] w-[156px]" />
          <div className="mt-9 mr-7 text-2xl font-semibold leading-none text-neutral-200 max-md:mr-2.5">
            hello@playstationplus.store
          </div>
          <div className="mt-1 text-base font-medium leading-loose text-neutral-400">
            принимаем заявки с 11:00 до 21:00 (МСК)
          </div>
          <div className="flex gap-2 self-start mt-4">
            <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/9e6026c93497c05916de173ea3de67c0fbb215f5f28189918e1ffec1b564ccd3?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c" alt="Social media icon 1" className="object-contain shrink-0 aspect-square fill-zinc-800 w-[42px]" />
            <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/fc98f7b2cc057874edd3a9f97cb549b5a21b0aff88f1a7c616164ae6c4b7012d?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c" alt="Social media icon 2" className="object-contain shrink-0 aspect-square w-[42px]" />
          </div>
        </div>
        <div className="flex-auto max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            <div className="flex flex-col w-[28%] max-md:ml-0 max-md:w-full">
              <div className="flex flex-col whitespace-nowrap max-md:mt-10">
                <h2 className="text-2xl font-semibold leading-none text-neutral-200">магазин</h2>
                <nav className="flex flex-col self-start mt-5 text-sm font-medium leading-loose text-neutral-400">
                  <a href="#catalog">каталог</a>
                  <a href="#subscriptions" className="mt-3">подписки</a>
                  <a href="#discounts" className="mt-3">скидки</a>
                </nav>
              </div>
            </div>
            <div className="flex flex-col ml-5 w-[73%] max-md:ml-0 max-md:w-full">
              <div className="flex flex-col grow max-md:mt-10">
                <h2 className="self-start text-2xl font-semibold leading-none text-neutral-200">покупателям</h2>
                <nav className="flex flex-col mt-5 text-sm font-medium leading-loose text-neutral-400">
                  <a href="#returns">возвраты</a>
                  <a href="#requisites" className="mt-3">реквизиты</a>
                  <a href="#privacy-policy" className="mt-3">политика конфиденциальности</a>
                  <a href="#public-offer" className="mt-3">публичная оферта</a>
                  <a href="#advertising-consent" className="mt-3">согласие на рекламную рассылку</a>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex shrink-0 mt-20 max-w-full h-px bg-neutral-800 w-[1252px] max-md:mt-10" />
      <div className="flex flex-wrap gap-5 justify-between mt-10 w-full max-w-[1252px] max-md:max-w-full">
        <div className="text-sm leading-loose text-neutral-400">
          © 2024, «GamePropaganda»
        </div>
        <div className="flex gap-6">
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/4b4b047e8086fbf221f284ac4bf64255b7e3f229e8db4fc49d58cabbd71f35fc?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c" alt="Payment method 1" className="object-contain shrink-0 my-auto w-10 aspect-[2]" />
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/69745494065a10bcad0b1fd010da60d30fb45ad86ae61016337c28f0888e110a?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c" alt="Payment method 2" className="object-contain shrink-0 my-auto w-11 aspect-[2.2]" />
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/315b14042839a2bb7ead2a7579f299c16ec8df12f8396fb315b31984095f78c3?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c" alt="Payment method 3" className="object-contain shrink-0 my-auto w-12 aspect-[2.4]" />
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/042128eda5c00b2788cd7a23bc276b96ab0332303302f76f4bbfb8df2c75bc36?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c" alt="Payment method 4" className="object-contain shrink-0 aspect-[1.75] w-[42px]" />
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/dc0baa7e237afe7de9b6dc03ffb13c8ac813eea10e192b718edcf6840047f557?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c" alt="Payment method 5" className="object-contain shrink-0 w-9 aspect-[1.5]" />
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/7f7f5997e3b588be9d65f7fe58f8193ecbbdd08cd4a2615d01ebf2a6de0d1126?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c" alt="Payment method 6" className="object-contain shrink-0 aspect-[2.16] w-[52px]" />
        </div>
      </div>
    </footer>
  );
}

export default Footer;
