/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Pagination() {
  return (
    <nav aria-label="Pagination" className="flex flex-col items-center mt-8">
      <div className="flex gap-5 justify-between items-center self-center ml-40 max-w-full text-base font-medium leading-loose whitespace-nowrap text-neutral-200 w-[261px]">
        <a
          href="#page1"
          aria-current="page"
          className="self-stretch my-auto text-center text-lime-400"
        >
          1
        </a>
        <a href="#page2" className="self-stretch my-auto text-center">
          2
        </a>
        <a href="#page3" className="self-stretch my-auto text-center">
          3
        </a>
        <span className="self-stretch my-auto text-center">...</span>
        <a href="#page1029" className="self-stretch my-auto">
          1029
        </a>
        <a href="#next-page" aria-label="Next page">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/7f28baec98d0505eed1bc7b9e2a85d2c56640faaedbcf54795ef8b8c2f37035c?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt=""
            className="object-contain shrink-0 self-stretch w-11 aspect-square"
          />
        </a>
      </div>
      <div className="self-center mt-4 ml-40 text-sm font-medium leading-loose text-center text-neutral-400">
        вы посмотрели 12 из 948 игры
      </div>
    </nav>
  );
}

export default Pagination;
