/**
 * This code was generated by Builder.io.
 */
import React from "react";

const categories = [
  {
    name: "все новости",
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/8abb62d1fb024a23369b2ceac47a2a46f939dccbaec03345f6ef1734929ded5e?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    isActive: true,
  },
  {
    name: "Sony Playstation",
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/49c269a21df59241850cc5a751cdb7b47845879eec223905203e97d0d619f4d2?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    name: "Xbox",
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/deeaee641166bf399eec9f1e670728d0ff4b32ad2f4c0aaa19133450dcc67bc0?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    name: "PC",
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/66859dd682c598dd8e144ed83ca465166f68ed08c4024b1205c2da1bb03ea29d?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
];

function Sidebar() {
  return (
    <aside className="flex flex-col w-[21%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col w-full text-base leading-loose text-neutral-200 max-md:mt-10">
        <div className="flex flex-wrap gap-2 items-start w-full max-w-[245px]">
          {categories.map((category, index) => (
            <div
              key={index}
              className={`flex overflow-hidden gap-3 justify-center items-center py-2 pr-6 pl-2 ${
                category.isActive
                  ? "text-lime-400 border-2 border-lime-400 border-solid shadow-sm"
                  : ""
              } bg-neutral-800 rounded-[50px] max-md:pr-5`}
            >
              <img
                loading="lazy"
                src={category.icon}
                alt=""
                className="object-contain shrink-0 self-stretch my-auto aspect-square w-[52px]"
              />
              <div className="self-stretch my-auto">{category.name}</div>
            </div>
          ))}
        </div>
        <button className="flex overflow-hidden gap-2.5 justify-center items-center self-start px-6 py-3 mt-10 whitespace-nowrap bg-neutral-800 min-h-[50px] rounded-[50px] max-md:px-5">
          <div className="flex gap-2 items-center self-stretch my-auto">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/c600d3c69503ee38960575968914448847cac42b7fdebee229dccd62c88a1685?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto aspect-square w-[22px]"
            />
            <span className="self-stretch my-auto">фильтры</span>
          </div>
        </button>
      </div>
    </aside>
  );
}

export default Sidebar;
