/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Footer() {
  return (
    <footer className="flex overflow-hidden flex-col items-center self-stretch px-20 pb-10 mt-16 w-full bg-neutral-900 max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="flex shrink-0 max-w-full h-px bg-neutral-800 w-[1252px]" />
      <div className="flex flex-wrap gap-10 self-start mt-16 w-full max-w-[1186px] max-md:mt-10 max-md:max-w-full">
        <div className="flex flex-col self-start">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/d1658df44896daf190c66a45739786609c6d393b4af779c7e1c338f1098c4147?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Company logo"
            className="object-contain max-w-full aspect-[3.72] w-[156px]"
          />
          <div className="mt-9 mr-7 text-2xl font-semibold leading-none text-neutral-200 max-md:mr-2.5">
            hello@playstationplus.store
          </div>
          <div className="mt-1 text-base font-medium leading-loose text-neutral-400">
            принимаем заявки с 11:00 до 21:00 (МСК)
          </div>
          <div className="flex gap-2 self-start mt-4">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/9e6026c93497c05916de173ea3de67c0fbb215f5f28189918e1ffec1b564ccd3?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt="Social media icon"
              className="object-contain shrink-0 aspect-square fill-zinc-800 w-[42px]"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/fc98f7b2cc057874edd3a9f97cb549b5a21b0aff88f1a7c616164ae6c4b7012d?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt="Social media icon"
              className="object-contain shrink-0 aspect-square w-[42px]"
            />
          </div>
        </div>
        <div className="flex-auto max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            <div className="flex flex-col w-[28%] max-md:ml-0 max-md:w-full">
              <nav className="flex flex-col whitespace-nowrap max-md:mt-10">
                <h2 className="text-2xl font-semibold leading-none text-neutral-200">
                  магазин
                </h2>
                <ul className="flex flex-col self-start mt-5 text-sm font-medium leading-loose text-neutral-400">
                  <li>
                    <a href="#catalog">каталог</a>
                  </li>
                  <li className="mt-3">
                    <a href="#subscriptions">подписки</a>
                  </li>
                  <li className="mt-3">
                    <a href="#discounts">скидки</a>
                  </li>
                </ul>
              </nav>
            </div>
            <div className="flex flex-col ml-5 w-[73%] max-md:ml-0 max-md:w-full">
              <nav className="flex flex-col grow max-md:mt-10">
                <h2 className="self-start text-2xl font-semibold leading-none text-neutral-200">
                  покупателям
                </h2>
                <ul className="flex flex-col mt-5 text-sm font-medium leading-loose text-neutral-400">
                  <li>
                    <a href="#returns">возвраты</a>
                  </li>
                  <li className="mt-3">
                    <a href="#requisites">реквизиты</a>
                  </li>
                  <li className="mt-3">
                    <a href="#privacy">политика конфиденциальности</a>
                  </li>
                  <li className="mt-3">
                    <a href="#offer">публичная оферта</a>
                  </li>
                  <li className="mt-3">
                    <a href="#consent">согласие на рекламную рассылку</a>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </div>
      </div>
      <div className="flex shrink-0 mt-20 max-w-full h-px bg-neutral-800 w-[1252px] max-md:mt-10" />
      <div className="flex flex-wrap gap-5 justify-between mt-10 w-full max-w-[1252px] max-md:max-w-full">
        <div className="text-sm leading-loose text-neutral-400">
          © 2024, «GamePropaganda»
        </div>
        <div className="flex gap-6">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/96aecdd0c91b35492b8e59041edccd0624f8ead618e0d7ce7475699de2f95e1f?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method"
            className="object-contain shrink-0 my-auto w-10 aspect-[2]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/95acda28fd2217e4ef65cbaf3c297544b9a528a3899a3f11a3955d4dae575093?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method"
            className="object-contain shrink-0 my-auto w-11 aspect-[2.2]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/77657735e847a4dd91a12884bff8b7f4716af90caf5218beb886184b70bbf048?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method"
            className="object-contain shrink-0 my-auto w-12 aspect-[2.4]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/e86d83d2af07f6e6d3eee1245f2ff85b281eccd36189c6be0e527cb6aac79123?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method"
            className="object-contain shrink-0 aspect-[1.75] w-[42px]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/df9dd86c5cfe8f990b7ca57c3c99054529f549b07ac8a1b814d4e74823b070a0?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method"
            className="object-contain shrink-0 w-9 aspect-[1.5]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/6fdaaf9cdac923c8de013c70e7c16d691061ef6eeb8a6065fde60f9ee9ede96d?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Payment method"
            className="object-contain shrink-0 aspect-[2.16] w-[52px]"
          />
        </div>
      </div>
    </footer>
  );
}

export default Footer;
