/**
 * This code was generated by Builder.io.
 */
import React from "react";
import NavItem from "./NavItem";
import SubscriptionButton from "./SubscriptionButton";

const navItems = [
  { text: "каталог", hasDropdown: false },
  { text: "подписки", hasDropdown: true },
  { text: "блог", hasDropdown: false },
  { text: "аккаунты", hasDropdown: true },
  { text: "баланс", hasDropdown: true },
];

function Header() {
  return (
    <header className="flex overflow-hidden flex-col items-center bg-neutral-900">
      <div className="flex flex-col self-stretch pt-4 w-full bg-neutral-900 bg-opacity-60 max-md:max-w-full">
        <div className="flex gap-5 justify-between items-center self-center w-full max-w-[1252px] max-md:max-w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/f9a38d3a4f19b57febf8ce8025b0bfaf8bf8289a9832eb778169057739f3c0bb?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Company logo"
            className="object-contain shrink-0 self-stretch max-w-full aspect-[3.72] w-[156px]"
          />
          <nav className="flex flex-wrap gap-10 self-stretch my-auto text-sm leading-loose max-md:max-w-full">
            <div className="flex flex-auto gap-10 items-start my-auto whitespace-nowrap text-neutral-200 max-md:max-w-full">
              {navItems.map((item, index) => (
                <NavItem
                  key={index}
                  text={item.text}
                  hasDropdown={item.hasDropdown}
                />
              ))}
            </div>
            <SubscriptionButton />
          </nav>
          <div className="flex gap-2.5 self-stretch my-auto">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/67c7c8046a64f55a9a58df4d8198fb23627937744d63f32cbadf9d4b2308b99b?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt="Social media icon 1"
              className="object-contain shrink-0 aspect-square w-[38px]"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/0ca4fb9d3bc9212f9b516d7b8a964484e6b1a75cb74907e73035c24ea81086ca?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt="Social media icon 2"
              className="object-contain shrink-0 aspect-square w-[38px]"
            />
          </div>
        </div>
        <div className="flex mt-3.5 w-full bg-neutral-800 min-h-[1px] max-md:max-w-full" />
      </div>
    </header>
  );
}

export default Header;
