/**
 * This code was generated by Builder.io.
 */
import React from "react";

function HeroSection() {
  return (
    <section className="flex relative flex-col items-center px-20 pt-14 pb-56 w-full text-6xl font-black text-center text-white leading-[61px] min-h-[462px] max-md:px-5 max-md:pb-24 max-md:max-w-full max-md:text-4xl max-md:leading-10">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/74f2db365c5eea7abac52c46dbeb0e3122c867cf68395869e6fb3abeea3072a4?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        alt="Background image"
        className="object-cover absolute inset-0 size-full"
      />
      <h1 className="relative -mb-11 max-w-full w-[652px] max-md:mb-2.5 max-md:max-w-full max-md:text-4xl max-md:leading-10">
        Мы собрали все самые лучшие акции в одном месте
      </h1>
    </section>
  );
}

export default HeroSection;
