/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SubscriptionCard from "./SubscriptionCard";

const subscriptions = [
  {
    title: "Подписка PS+ Essential 1 месяц",
    price: "1 650 ₽",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/e21dde3381372e0e5b936b9c61a23686a8bb7e54ce74e6ce8ec96eda42532bf4?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    title: "Подписка PS+ Essential 1 месяц",
    price: "1 450 ₽",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/5dd824bd4fa698d4eec834016907feed636d8312401b095b5113155307833e04?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    title: "Подписка PS+ Essential 1 месяц",
    price: "990 ₽",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/09572993e1b9e1cbdaaddf0d8061fb6e40bd4ac226f1655050db0271cd468295?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
];

function SubscriptionSection() {
  return (
    <section className="flex relative flex-col items-center px-20 pt-16 pb-24 mt-24 w-full rounded-none max-w-[1400px] min-h-[830px] max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/8b7f8d550c7392c0cce27dc59bf337d0195bae052f352ce4b4d62c3a37a2bc46?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        alt="Background image"
        className="object-cover absolute inset-0 size-full"
      />
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/7a92b0891a3bed96513374f2cc6aab0a6e041abf7f7e7baad774b3d829a492c8?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        alt=""
        className="object-contain rounded-none aspect-square w-[50px]"
      />
      <h2 className="relative mt-1.5 text-5xl font-bold leading-none text-center text-white max-md:max-w-full max-md:text-4xl">
        Подари подписку другу
      </h2>
      <div className="flex relative gap-1 items-center mt-8 ml-5 text-base leading-loose text-neutral-200">
        <button className="gap-2.5 self-stretch px-6 py-4 border-2 border-lime-400 border-solid shadow-sm bg-neutral-800 min-h-[59px] rounded-[50px] max-md:px-5">
          1 месяц
        </button>
        <button className="gap-2.5 self-stretch px-6 py-4 bg-neutral-800 min-h-[59px] rounded-[50px] max-md:px-5">
          3 месяц
        </button>
        <button className="gap-2.5 self-stretch px-6 py-4 bg-neutral-800 min-h-[59px] rounded-[50px] w-[87px] max-md:px-5 text-white">
          12 Месяцев
        </button>
      </div>
      <div className="relative mt-12 w-full max-w-[1216px] max-md:mt-10 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-[66%] max-md:ml-0 max-md:w-full">
            <div className="relative grow max-md:mt-10 max-md:max-w-full">
              <div className="flex gap-5 max-md:flex-col">
                {subscriptions.map((subscription, index) => (
                  <div
                    key={index}
                    className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full"
                  >
                    <SubscriptionCard {...subscription} />
                  </div>
                ))}
              </div>
            </div>
          </div>
          <div className="flex flex-col ml-5 w-[34%] max-md:ml-0 max-md:w-full">
            <div className="flex relative flex-col px-8 py-6 mx-auto w-full rounded-3xl bg-zinc-900 max-md:px-5 max-md:mt-10">
              <div className="flex gap-5 self-start">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/e7b85c36c9bb9d09d0733a99085ef85d247e78263138c801e2f6915672a7444e?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                  alt=""
                  className="object-contain shrink-0 self-start w-11 aspect-square fill-lime-400"
                />
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/61a87ace74c2685db094a58730bdc790d0b80789e8241e7dde219c36ade92317?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                  alt=""
                  className="object-contain shrink-0 aspect-square w-[46px]"
                />
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/05353bcdbd9620f0cc35b824ef3eb1de9929590976292be604f8fa9eee1a88da?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                  alt=""
                  className="object-contain shrink-0 aspect-square w-[46px]"
                />
              </div>
              <h3 className="mt-5 text-xl font-bold tracking-normal leading-7 text-white">
                Экономь своё время. Купи подписку с автоматическим продлением
                оплаты.
              </h3>
              <p className="mt-5 mr-7 text-sm tracking-normal text-white max-md:mr-2.5">
                Просто зарегистрируйся в нашем личном кабинете и привяжи карту
                на стороне банка и мы будем обновлять подписку без твоего
                участия
                <br />
                <br />
                *данные твоей банковской карты мы не храним
              </p>
              <button className="px-16 py-5 mt-7 text-base font-bold leading-none text-center text-lime-400 whitespace-nowrap border border-lime-400 border-solid rounded-[100px] max-md:px-5 max-md:mr-2">
                Зарегистрироваться
              </button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

export default SubscriptionSection;
