/**
 * This code was generated by Builder.io.
 */
import React from "react";

function SubscriptionCard({ title, price, imageSrc }) {
  return (
    <div className="flex overflow-hidden relative flex-col px-2 pt-2 pb-5 mx-auto w-full rounded-3xl bg-neutral-800 max-md:mt-5">
      <div className="flex overflow-hidden flex-col items-center text-lg font-medium leading-none text-center text-yellow-500 bg-white rounded-xl aspect-square">
        <div className="flex relative flex-col px-16 pt-36 pb-16 w-full aspect-square max-md:px-5 max-md:pt-24">
          <img
            loading="lazy"
            src={imageSrc}
            alt={title}
            className="object-cover absolute inset-0 size-full"
          />
          1 месяц
        </div>
      </div>
      <div className="flex flex-col mt-3 text-neutral-200 max-md:mx-2">
        <div className="text-base font-medium leading-5 whitespace-nowrap text-ellipsis">
          {title}
        </div>
        <div className="mt-3 text-2xl font-semibold leading-none">{price}</div>
      </div>
      <button className="overflow-hidden gap-2.5 self-stretch px-5 py-3.5 mt-5 text-base font-bold leading-none text-center text-black bg-lime-400 min-h-[50px] rounded-[100px] max-md:mx-2">
        Оформить подписку
      </button>
    </div>
  );
}

export default SubscriptionCard;
