/**
 * This code was generated by Builder.io.
 */
import React from "react";

function SubscriptionButton() {
  return (
    <button className="overflow-hidden gap-2.5 self-stretch px-5 pt-1.5 pb-2 font-medium text-center text-black bg-lime-400 rounded-[100px]">
      оформить подписку
    </button>
  );
}

export default SubscriptionButton;
