/**
 * This code was generated by Builder.io.
 */
import React from "react";

function FeatureItem({ icon, text }) {
  return (
    <div className="flex gap-6">
      <img
        loading="lazy"
        src={icon}
        alt=""
        className="object-contain shrink-0 self-start rounded-none aspect-square w-[50px]"
      />
      <div>{text}</div>
    </div>
  );
}

export default FeatureItem;
