/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FeatureItem from "./FeatureItem";

const features = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/9ae9c20fb4668edc37ef38c65a9def6b43660a88e4f5d122f0238a8ad16ef407?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    text: "Играй в сотни игр на консоли и ПК",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/a11f108dacd12d10a87ceadfff3ddabfac260caa742d4a860b23cdccfeb298e6?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    text: "Получай игры сразу в день релиза",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/7d31beb5a712ce4f3d97f374a52e523d4d891af877ed68a401027a3ee3dd16d4?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    text: "Скидки и преимущества",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/a6c7f44ff6630662fd03c4887a9867ff6d8780843bb7d6830529746aecb6f05f?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    text: "Онлайн снова доступен",
  },
];

function FeatureSection() {
  return (
    <section className="flex relative z-10 flex-col self-center px-20 pt-96 pb-16 mt-0 w-full rounded-none max-w-[1400px] min-h-[920px] max-md:px-5 max-md:pt-24 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/9c4d911dd33c945437903bbbd3b998327a0768fcd2abd25531dcd2215aa6bbc1?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        alt=""
        className="object-cover absolute inset-0 size-full"
      />
      <div className="flex relative gap-5 justify-between w-full text-xl tracking-normal leading-7 text-white max-w-[1160px] max-md:max-w-full">
        {features.map((feature, index) => (
          <FeatureItem key={index} icon={feature.icon} text={feature.text} />
        ))}
      </div>
    </section>
  );
}

export default FeatureSection;
