/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SocialIcon from "./SocialIcon";
import FooterColumn from "./FooterColumn";
import PaymentMethods from "./PaymentMethods";

const socialIcons = [
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/9e6026c93497c05916de173ea3de67c0fbb215f5f28189918e1ffec1b564ccd3?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    alt: "Social Icon 1",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/82bc375cf21f23dd196b5eb4ba10e90b3c643e0a58d181eacd952cd07d571335?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    alt: "Social Icon 2",
  },
];

const storeLinks = ["каталог", "подписки", "скидки"];
const customerLinks = [
  "возвраты",
  "реквизиты",
  "политика конфиденциальности",
  "публичная оферта",
  "согласие на рекламную рассылку",
];

function Footer() {
  return (
    <footer className="flex overflow-hidden flex-col items-center px-20 pb-10 mt-16 w-full bg-neutral-900 max-md:px-5 max-md:mt-10 max-md:max-w-full">
      Continuing from where we left off:
      <div className="flex shrink-0 max-w-full h-px bg-neutral-800 w-[1252px]" />
      <div className="flex flex-wrap gap-10 self-start mt-16 w-full max-w-[1186px] max-md:mt-10 max-md:max-w-full">
        <div className="flex flex-col self-start">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/ae77d2e47c566dbe26b6c19a1b351a65f0113612622d8be45c08742e80d07015?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Company Logo"
            className="object-contain max-w-full aspect-[3.72] w-[156px]"
          />
          <div className="mt-9 mr-7 text-2xl font-semibold leading-none text-neutral-200 max-md:mr-2.5">
            hello@playstationplus.store
          </div>
          <div className="mt-1 text-base font-medium leading-loose text-neutral-400">
            принимаем заявки с 11:00 до 21:00 (МСК)
          </div>
          <div className="flex gap-2 self-start mt-4">
            {socialIcons.map((icon, index) => (
              <SocialIcon key={index} src={icon.src} alt={icon.alt} />
            ))}
          </div>
        </div>
        <div className="flex-auto max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            <FooterColumn title="магазин" links={storeLinks} />
            <FooterColumn title="покупателям" links={customerLinks} />
          </div>
        </div>
      </div>
      <div className="flex shrink-0 mt-20 max-w-full h-px bg-neutral-800 w-[1252px] max-md:mt-10" />
      <div className="flex flex-wrap gap-5 justify-between mt-10 w-full max-w-[1252px] max-md:max-w-full">
        <div className="text-sm leading-loose text-neutral-400">
          © 2024, «GamePropaganda»
        </div>
        <PaymentMethods />
      </div>
    </footer>
  );
}

export default Footer;
