/**
 * This code was generated by Builder.io.
 */
import React from "react";
import NavItem from "./NavItem";
import Button from "./Button";

const navItems = [
  { text: "каталог", hasDropdown: false },
  { text: "подписки", hasDropdown: true },
  { text: "блог", hasDropdown: false },
  { text: "аккаунты", hasDropdown: true },
  { text: "баланс", hasDropdown: true },
];

function Header() {
  return (
    <header className="flex overflow-hidden relative flex-col pb-52 w-full rounded-none min-h-[770px] max-md:pb-24 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/e2822263b7bf0b453f2beb5f0c248879414b40e2f2d8273d599e5654577ccd7c?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        alt=""
        className="object-cover absolute inset-0 size-full"
      />
      <div className="flex relative flex-col pt-4 w-full bg-neutral-900 bg-opacity-60 max-md:max-w-full">
        <div className="flex gap-5 justify-between items-center self-center w-full max-w-[1252px] max-md:max-w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/a57d4d19ff1e1962df0f53afda4c0847a4c21a0187478ba72479b0b5f99ff3be?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Company Logo"
            className="object-contain shrink-0 self-stretch max-w-full aspect-[3.72] w-[156px]"
          />
          <nav className="flex flex-wrap gap-10 self-stretch my-auto text-sm leading-loose max-md:max-w-full">
            <div className="flex flex-auto gap-10 items-start my-auto whitespace-nowrap text-neutral-200 max-md:max-w-full">
              {navItems.map((item, index) => (
                <NavItem
                  key={index}
                  text={item.text}
                  hasDropdown={item.hasDropdown}
                />
              ))}
            </div>
            <Button
              text="оформить подписку"
              className="overflow-hidden gap-2.5 self-stretch px-5 pt-1.5 pb-2 font-medium text-center text-black bg-lime-400 rounded-[100px]"
            />
          </nav>
          <div className="flex gap-2.5 self-stretch my-auto">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/67c7c8046a64f55a9a58df4d8198fb23627937744d63f32cbadf9d4b2308b99b?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt="Social Icon 1"
              className="object-contain shrink-0 aspect-square w-[38px]"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/0ca4fb9d3bc9212f9b516d7b8a964484e6b1a75cb74907e73035c24ea81086ca?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt="Social Icon 2"
              className="object-contain shrink-0 aspect-square w-[38px]"
            />
          </div>
        </div>
        <div className="flex mt-3.5 w-full bg-neutral-800 min-h-[1px] max-md:max-w-full" />
      </div>
      <div className="flex relative flex-col items-start mt-44 mb-0 ml-24 max-w-full text-white w-[398px] max-md:mt-10 max-md:mb-2.5 max-md:ml-2.5">
        <h1 className="self-stretch text-5xl font-black leading-[50px] max-md:text-4xl max-md:leading-10">
          Пополним твой турцекий аккаунт PSN
        </h1>
        <p className="mt-5 text-3xl tracking-normal">на любую сумму</p>
        <Button
          text="Написать нам"
          className="overflow-hidden gap-2.5 self-stretch px-8 py-4 mt-16 text-base font-bold leading-tight text-black bg-lime-400 min-h-[50px] rounded-[1000px] max-md:px-5 max-md:mt-10"
        />
      </div>
    </header>
  );
}

export default Header;
