/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import PricingSection from "./PricingSection";
import FeatureSection from "./FeatureSection";
import SubscriptionSection from "./SubscriptionSection";
import TestimonialSection from "./TestimonialSection";
import NewsletterSection from "./NewsletterSection";
import Footer from "./Footer";

function MainContent() {
  return (
    <div className="flex overflow-hidden flex-col bg-neutral-900">
      <Header />
      <PricingSection />
      <FeatureSection />
      <SubscriptionSection />
      <TestimonialSection />
      <NewsletterSection />
      <Footer />
    </div>
  );
}

export default MainContent;
