/**
 * This code was generated by Builder.io.
 */
import React from "react";
import NewsletterForm from "./NewsletterForm";
import TelegramSubscription from "./TelegramSubscription";

function NewsletterSection() {
  return (
    <div className="self-center mt-5 w-full max-w-[1252px] max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <NewsletterForm />
        <TelegramSubscription />
      </div>
    </div>
  );
}

export default NewsletterSection;
