/**
 * This code was generated by Builder.io.
 */
import React from "react";

const paymentMethods = [
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/b6157796c02503c58bc24046a65336aaa931cc03549a5d9ed955755e53676bc8?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    alt: "Payment Method 1",
    className: "object-contain shrink-0 my-auto w-10 aspect-[2]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/2e611f345103a2e65f272aedd8b05a1f85b8dde2082b7fc6cf2e2bb3b2ffa565?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    alt: "Payment Method 2",
    className: "object-contain shrink-0 my-auto w-11 aspect-[2.2]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/490ce6070874227b508d1edb2dd0daf3bfae07464b66558fa22ce75d81903f45?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    alt: "Payment Method 3",
    className: "object-contain shrink-0 my-auto w-12 aspect-[2.4]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/f5067269e1b8e67049e248a98def8e8b9a8630a82abeae1c5ebe05071f9fabb5?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    alt: "Payment Method 4",
    className: "object-contain shrink-0 aspect-[1.75] w-[42px]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/b0f32f22cf00c625cc0fc39ff308f6a3dc38e8e112286d4fcc08bae3e8ce8d93?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    alt: "Payment Method 5",
    className: "object-contain shrink-0 w-9 aspect-[1.5]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/db72023755163597de5b2fd1c759a1536570dd4a6f0dae9ba2edc4f40a299d06?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    alt: "Payment Method 6",
    className: "object-contain shrink-0 aspect-[2.16] w-[52px]",
  },
];

function PaymentMethods() {
  return (
    <div className="flex gap-6">
      {paymentMethods.map((method, index) => (
        <img
          key={index}
          loading="lazy"
          src={method.src}
          alt={method.alt}
          className={method.className}
        />
      ))}
    </div>
  );
}

export default PaymentMethods;
