/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Button from "./Button";

function PricingCard({ title, price, imageSrc, isCustom }) {
  return (
    <div className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full">
      <div className="flex relative flex-col items-center px-px pt-8 font-bold text-center rounded-xl max-md:mt-5">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/71b3fa9ecbf79614541fb2c95c06918e8fce72b81d351aa1cdd11cdcb1ebc8d9?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          alt="PlayStation Logo"
          className="object-contain w-24 aspect-[3]"
        />
        {!isCustom && (
          <div className="z-10 mt-14 text-2xl tracking-normal text-white max-md:mt-10">
            {price}
          </div>
        )}
        <div
          className={`flex overflow-hidden relative flex-col self-stretch px-${
            isCustom ? "12" : "11"
          } pt-5 pb-11 w-full ${isCustom ? "" : "aspect-[1.258]"} max-md:px-5`}
        >
          {!isCustom && (
            <img
              loading="lazy"
              src={imageSrc}
              alt=""
              className="object-cover absolute inset-0 size-full"
            />
          )}
          <div
            className={`relative text-5xl tracking-tight leading-none text-white ${
              isCustom ? "mt-14 max-md:mt-10" : ""
            } max-md:mr-1 max-md:text-4xl`}
          >
            {title}
          </div>
          <Button
            text={isCustom ? "Написать нам" : "Купить"}
            className={`overflow-hidden relative gap-2.5 self-stretch px-8 py-4 mt-20 text-base leading-tight ${
              isCustom ? "text-black bg-white" : "text-black bg-white"
            } whitespace-nowrap min-h-[50px] rounded-[1000px] max-md:px-5 max-md:mt-10`}
          />
        </div>
      </div>
    </div>
  );
}

export default PricingCard;
