/**
 * This code was generated by Builder.io.
 */
import React from "react";
import PricingCard from "./PricingCard";

const pricingOptions = [
  {
    title: "500 лир",
    price: "2500 ₽",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/85ce5ddea8282d0b321b1d4dc7e79652f07b2d854769a64f887dce2d1b30f63e?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    title: "1500 лир",
    price: "7500 ₽",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/f9709c07661e3f46224db3f16e73d3d30d62dc656225251fdf7db4cf2b72c698?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    title: "2500 лир",
    price: "12500 ₽",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/8a49cfa2a0a9a16c94df8945444e80952767a6415ef7461e1383a307d8acd000?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  { title: "Любая сумма", price: "", imageSrc: "" },
];

function PricingSection() {
  return (
    <section className="flex overflow-hidden relative flex-col items-center px-20 pt-6 pb-36 mt-16 w-full min-h-[716px] max-md:px-5 max-md:pb-24 max-md:mt-10 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/666402c13e6ff4803520a2bf90d5c32117887f27ce7773fcc60526d8f4ea5b7a?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        alt=""
        className="object-cover absolute inset-0 size-full"
      />
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/f67cc88ce021006cbf3a348db70564d6a9524a9d9c069f3182ab5dbffe2c80c1?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        alt="Pricing Icon"
        className="object-contain rounded-none aspect-square w-[50px]"
      />
      <h2 className="relative mt-3.5 text-5xl font-bold leading-none text-center text-white">
        Выбери номинал
      </h2>
      <div className="relative mt-2.5 mb-0 w-full max-w-[1252px] max-md:mb-2.5 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          {pricingOptions.map((option, index) => (
            <PricingCard
              key={index}
              title={option.title}
              price={option.price}
              imageSrc={option.imageSrc}
              isCustom={index === pricingOptions.length - 1}
            />
          ))}
        </div>
      </div>
    </section>
  );
}

export default PricingSection;
