/**
 * This code was generated by Builder.io.
 */
import React from "react";

function SocialIcon({ src, alt }) {
  return (
    <img
      loading="lazy"
      src={src}
      alt={alt}
      className="object-contain shrink-0 aspect-square fill-zinc-800 w-[42px]"
    />
  );
}

export default SocialIcon;
