/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SubscriptionCard from "./SubscriptionCard";

const subscriptions = [
  {
    title: "Подписка PS+ Deluxe",
    duration: "На 1 месяц",
    price: "1650",
    unit: "₽/мес",
  },
  {
    title: "Подписка PS+ Extra",
    duration: "На 1 месяц",
    price: "1450",
    unit: "₽/мес",
  },
  {
    title: "Подписка PS+ Essential",
    duration: "На 1 месяц",
    price: "990",
    unit: "₽/мес",
  },
];

function SubscriptionSection() {
  return (
    <div className="relative mt-16 max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        {subscriptions.map((sub, index) => (
          <SubscriptionCard
            key={index}
            title={sub.title}
            duration={sub.duration}
            price={sub.price}
            unit={sub.unit}
          />
        ))}
      </div>
    </div>
  );
}

export default SubscriptionSection;
