/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ActionButton = ({ text, primary = false }) => {
  const baseClasses =
    "overflow-hidden gap-2.5 self-stretch px-8 py-4 min-h-[50px] rounded-[1000px] max-md:px-5";
  const colorClasses = primary ? "bg-lime-400" : "bg-white";

  return <button className={`${baseClasses} ${colorClasses}`}>{text}</button>;
};

export default ActionButton;
