/**
 * This code was generated by Builder.io.
 */
import React from "react";

const CurrencyCard = ({ image, title, price }) => {
  return (
    <div className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full">
      <div className="flex overflow-hidden flex-col px-2 pt-2 pb-5 mx-auto w-full rounded-3xl bg-neutral-800 max-md:mt-5">
        <div className="flex overflow-hidden flex-col items-center rounded-xl aspect-square bg-zinc-800">
          <img
            loading="lazy"
            src={image}
            alt={title}
            className="object-contain w-full aspect-square"
          />
        </div>
        <div className="flex gap-5 justify-between mt-3 text-base font-medium leading-7 whitespace-nowrap text-neutral-200 max-md:mx-2">
          <div className="text-ellipsis">{title}</div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/23fdcc02a6edebcef5667085442387b3e1318ecc3a0a9486aabc96b98f178b53?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt="Favorite icon"
            className="object-contain shrink-0 self-start mt-1 w-5 aspect-square"
          />
        </div>
        <div className="gap-2.5 self-start mt-8 text-2xl font-semibold leading-none text-neutral-200 max-md:ml-2">
          {price}
        </div>
      </div>
    </div>
  );
};

export default CurrencyCard;
