/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FeatureCard from "./FeatureCard";

function FeatureSection({ features }) {
  return (
    <div className="flex flex-wrap justify-center items-center gap-2.5 w-full max-md:mt-10 max-md:max-w-full mt-4">
      {features.map((feature, index) => (
        <FeatureCard key={index} emoji={feature.emoji} text={feature.text} />
      ))}
    </div>
  );
}

export default FeatureSection;
