/**
 * This code was generated by Builder.io.
 */
import React from "react";
import GameCard from "./GameCard";
import GamePassCard from "./GamePassCard";
import PromotionCard from "./PromotionCard";

const GameGallery = () => {
  const gameCards = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/12226b39c7afb4c3c849fec3d107baa2334c00f50418d54ad842df06d7a20fbb?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
      alt: "Game 1",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/f97bb0f855453e58c004472122c98a00130a704a4b1bce8f337e4c35449bbe60?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
      alt: "Game 2",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/9c56c3adc1012a76cb8af97db64d383fdf653db1047661902f234245f08d6bb7?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
      alt: "Game 3",
    },
  ];

  return (
<main className="flex flex-wrap justify-center items-center gap-2.5 w-full font-medium leading-loose rounded-none">
{gameCards.map((card, index) => (
        <GameCard key={index} imageSrc={card.src} alt={card.alt} />
      ))}
      <GamePassCard />
      <PromotionCard />
    </main>
  );
};

export default GameGallery;
