/**
 * This code was generated by Builder.io.
 */
import React from "react";

const GamePassCard = () => (
  <div className="flex relative flex-col text-2xl text-white rounded-xl aspect-[0.648]">
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/d533e33a30a8133d302b20e4965573476152f4899cbb66db69f0f6852d7fdce8?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
      alt="Game Pass background"
      className="object-cover absolute inset-0 size-full"
    />
    <div className="flex relative flex-col items-center pt-4 pr-14 pb-80 pl-24 rounded-xl max-md:px-5 max-md:pb-24">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/cf419e51ed6bc6521f29b084f773dbc04bed75990703e42a3b1c4317daf05819?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        alt="Game Pass icon"
        className="object-contain w-8 aspect-square"
      />
      <div className="mt-3 mb-0 max-md:mb-2.5">GAME PASS</div>
    </div>
  </div>
);

export default GamePassCard;
