/**
 * This code was generated by Builder.io.
 */
import React from "react";
import GameGrid1 from "./GameGrid1";

const GameGridContainer = () => {
  return (
    <main className="rounded-none max-md:pr-5 mt-10">
      <GameGrid1 />
    </main>
  );
};

export default GameGridContainer;
