/**
 * This code was generated by Builder.io.
 */
import React from "react";

const GameCard1 = ({
  imageSrc,
  title,
  originalPrice,
  discountedPrice,
  discount,
  logoSrc,
}) => {
  return (
    <article className="flex overflow-hidden flex-col px-2 pt-2 pb-5 mx-auto w-full rounded-3xl bg-neutral-800 max-md:mt-5">
      <div className="flex overflow-hidden flex-col items-center rounded-xl aspect-square bg-zinc-800">
        <img
          loading="lazy"
          src={imageSrc}
          alt={title}
          className="object-contain z-10 -mt-2 w-full aspect-square"
        />
      </div>
      <div className="flex gap-5 justify-between items-start mt-3 text-base font-medium leading-loose whitespace-nowrap text-neutral-200 max-md:mx-2">
        <h2 className="text-ellipsis">{title}</h2>
        {logoSrc && (
          <img
            loading="lazy"
            src={logoSrc}
            alt=""
            className="object-contain shrink-0 mt-1 aspect-[1.3] w-[26px]"
          />
        )}
      </div>
      <div className="flex gap-2.5 items-center self-start mt-11 text-2xl font-semibold leading-none text-neutral-200 max-md:mt-10 max-md:ml-2">
        {originalPrice && (
          <span className="self-stretch my-auto text-neutral-500">
            {originalPrice}
          </span>
        )}
        <span className="self-stretch my-auto">{discountedPrice}</span>
        {discount && (
          <span className="overflow-hidden gap-2.5 self-stretch px-2 py-0.5 my-auto text-sm font-medium leading-loose whitespace-nowrap bg-purple-600 rounded">
            {discount}
          </span>
        )}
      </div>
    </article>
  );
};

export default GameCard1;
