/**
 * This code was generated by Builder.io.
 */
import React from "react";

const GameCard = ({ imageSrc, alt }) => (
  <img
    loading="lazy"
    src={imageSrc}
    alt={alt}
    className="object-contain shrink-0 max-w-full rounded-none aspect-[0.65] w-[284px]"
  />
);

export default GameCard;
