/**
 * This code was generated by Builder.io.
 */
import React from "react";

const GameSection = ({ title, description, listItems, imageSource }) => (
  <section className="mt-10 ml-[159px] w-full max-w-[1116px] max-md:mt-10 max-md:mb-2.5 max-md:max-w-full z-[10]">
    <div className="flex gap-5 max-md:flex-col">
      <aside className="flex flex-col w-[61%] max-md:ml-0 max-md:w-full">
        <img
          loading="lazy"
          src={imageSource}
          alt="Game Scene"
          className="object-contain grow w-full rounded-none aspect-[1.38] max-md:mt-10 max-md:max-w-full"
        />
      </aside>
      <aside className="flex flex-col ml-5 w-[39%] max-md:ml-0 max-md:w-full">
        <div className="flex flex-col self-stretch my-auto w-full max-md:mt-10">
          <h2 className="self-start text-4xl font-bold leading-none text-white">
            {title}
          </h2>
          <p className="mt-8 text-lg leading-7 text-white">{description}</p>
          <div className="flex gap-5 mt-8">
            <div className="flex flex-col self-start">
              {listItems.map((item, index) => (
                <img
                  key={index}
                  loading="lazy"
                  src={item.image}
                  alt={item.alt}
                  className="object-contain w-6 aspect-square"
                />
              ))}
            </div>
            <div className="flex flex-col grow shrink-0 text-lg leading-6 text-white basis-0 w-fit">
              {listItems.map((item, index) => (
                <div key={index}>{item.text}</div>
              ))}
            </div>
          </div>
          <div className="flex gap-5 self-start mt-4 text-lg leading-none text-white">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/6616b1b37410dd49dc20f758315958276b33a689f3e22abe54ce66488360ee0f?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt="Catalog Icon"
              className="object-contain shrink-0 w-6 aspect-square"
            />
            <div className="flex-auto">Самый большой каталог игр в России</div>
          </div>
        </div>
      </aside>
    </div>
  </section>
);

export default GameSection;
