/**
 * This code was generated by Builder.io.
 */
import React from "react";
import GameCard from "./GameCard";

const games = [
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/12226b39c7afb4c3c849fec3d107baa2334c00f50418d54ad842df06d7a20fbb?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "",
    price: "",
    icon: "",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/d533e33a30a8133d302b20e4965573476152f4899cbb66db69f0f6852d7fdce8?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "GAME PASS",
    price: "",
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/cf419e51ed6bc6521f29b084f773dbc04bed75990703e42a3b1c4317daf05819?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/165c9a952fdf2965be38d273338e8eadd908b1fc0bae1c430564db656ef2d0cc?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "",
    price: "",
    icon: "",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/f97bb0f855453e58c004472122c98a00130a704a4b1bce8f337e4c35449bbe60?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "",
    price: "",
    icon: "",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/9c56c3adc1012a76cb8af97db64d383fdf653db1047661902f234245f08d6bb7?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "",
    price: "",
    icon: "",
  },
];

const GameCards = () => {
  return (
    <div className="flex flex-wrap gap-2.5 self-stretch mt-2.5 w-full text-2xl font-medium leading-loose text-white max-md:max-w-full">
      {games.map((game, index) => (
        <GameCard key={index} {...game} />
      ))}
    </div>
  );
};

export default GameCards;
