/**
 * This code was generated by Builder.io.
 */
import React from "react";
import GameCard from "./GameCard1";

const gameData = [
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/e05b5faa8dc7a26d2ba114bfdabaa23640ff358cd2053173d634cf6b2bf409c0?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Gran Turismo™ 7",
    originalPrice: "8 290 ₽",
    discountedPrice: "4 790 ₽",
    discount: "-45%",
    logoSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/f967734eefefe1cdc4ea9489ace07005a2a45704ccaaf137c3df0d1e03752595?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/9f218e0675addc629c4d90d2981625b05931dbc394362174edffb6b72ba05e76?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "God of War Ragnarök",
    discountedPrice: "9 490 ₽",
    logoSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/a7b1259eb22bae02b95a6fc891c9ed394613dcda14b42fec4869592069526717?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/5ff531319288da44eec5fa445fbceeab498625df45f8071ab1a5d11a2779e1df?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Hogwarts Legacy PS5 Version",
    originalPrice: "10 190 ₽",
    discountedPrice: "5 390 ₽",
    discount: "-45%",
    logoSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/9c4d009d02bd4f6a4042ed8b88c8e8043c4e855e7d0f442fb1e8859f83bb60b1?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/d48b90448529f1891e4c87cec902e9b2c47aa313a966355d85c2aec8efa2ab43?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Doki Doki Literature Club Plus!",
    originalPrice: "1 690 ₽",
    discountedPrice: "1 290 ₽",
    discount: "-14%",
    logoSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/9c4d009d02bd4f6a4042ed8b88c8e8043c4e855e7d0f442fb1e8859f83bb60b1?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
];

const GameGrid1 = () => {
  return (
    <section className="rounded-none max-md:pr-5">
      <div className="flex gap-5 max-md:flex-col">
        {gameData.map((game, index) => (
          <div
            key={index}
            className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full"
          >
            <GameCard {...game} />
          </div>
        ))}
      </div>
    </section>
  );
};

export default GameGrid1;
