/**
 * This code was generated by Builder.io.
 */
import React from "react";
import GameGridContainer from "./GameGridContainer";
const HotDeals = () => {
  return (
    <section className="flex flex-col items-center mt-24 w-full max-w-[1252px] max-md:mt-10 max-md:max-w-full mx-auto">
      <h2 className="text-5xl font-bold tracking-normal leading-none text-center text-white ">
        Горячие скидки
      </h2>
      <GameGridContainer/>
      <button className="overflow-hidden gap-2.5 px-8 py-4 mt-8 mx-auto text-[15px] font-bold leading-tight text-center text-black bg-lime-400 min-h-[50px] rounded-[1000px] w-[206px] max-md:px-5">
  Перейти в каталог
</button>


    </section>
  );
};

export default HotDeals;
