/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ImageCard = ({ src, alt, children }) => (
  <div className="flex flex-col absolute  items-center px-20 py-28 w-full text-6xl font-black text-center text-white leading-[61px] max-w-[1400px] min-h-[2011px] max-md:px-5 max-md:py-24 max-md:max-w-full max-md:text-4xl max-md:leading-10">
    <img
      loading="lazy"
      src={src}
      alt={alt}
      className="object-cover absolute inset-0 size-full"
    />
    {children}
  </div>
);

export default ImageCard;
