/**
 * This code was generated by Builder.io.
 */
import React from "react";

const InfoCard = ({ title, description, items }) => (
  <div className="flex flex-col items-start self-stretch my-auto w-full text-lg text-white max-md:mt-10 max-md:max-w-full">
    <div className="text-4xl font-bold leading-none">{title}</div>
    <div className="mt-8 leading-7">{description}</div>
    {items.map((item, index) => (
      <div className="flex gap-5 mt-4 leading-6" key={index}>
        <img
          loading="lazy"
          src={item.image}
          alt={item.alt}
          className="object-contain shrink-0 w-6 aspect-square"
        />
        <div className="flex-auto">{item.text}</div>
      </div>
    ))}
  </div>
);

export default InfoCard;
