/**
 * This code was generated by Builder.io.
 */
import React from "react";
import CurrencyCard from "./CurrencyCard";

const currencies = [
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/54f0dfe6b8191c77c37d699015f0a2685e18178bd983a85c47228744866270d1?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "EA SPORTS FC™ 24 — FC Points 1050",
    price: "1 690 ₽",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/e7bf942853c704dd8ffd2cc6afaae79075610732719dbcfbf6a566aa67bdbf6d?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "150,000 Source Crystals",
    price: "5 190 ₽",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/1d097c6007d53de30af89cea17a67f2665f7bc660778d00b57a2ec3f773f631d?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "PBA Pro Bowling: 1,250 Gold Pins",
    price: "1 690 ₽",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/9e527d61415a8e6d7a0021a255da6e3dd72a32d2895883db8a7a082161d2b5ac?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Fortnite — 2,800 V-Bucks",
    price: "2 390 ₽",
  },
];

const InGameCurrency = () => {
  return (
    <section className="mt-28 w-full max-w-[1252px] max-md:mt-10 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/0a35bbe91dca48c06d0c50cfa6f59a31ee3acda64b3b394a61447c4cf587d82f?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        alt="Currency icon"
        className="object-contain mt-28 rounded-none aspect-square w-[50px] max-md:mt-10"
      />
      <h2 className="mt-3.5 text-5xl font-bold leading-10 text-center text-white w-[554px] max-md:max-w-full">
        Покупай любую валюту для любимых игр
      </h2>
      <div className="flex gap-5 mt-16 max-md:flex-col max-md:mt-10">
        {currencies.map((currency, index) => (
          <CurrencyCard key={index} {...currency} />
        ))}
      </div>
    </section>
  );
};

export default InGameCurrency;
