/**
 * This code was generated by Builder.io.
 */
import React from "react";
import MentionCard from "./MentionCard";

const mentions = [
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/659d4f849e12559cf8816b364b5023da1d500d6e762802e75578457288065cf2?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    name: "Safronov",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/52bdef44b6b70aeb39adca5515277f01d98dcb95d13f0b385725cf84a2ca2db1?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    name: "Wingelm",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/35455ec84e4aed61e002e72401bc47a69880dce8c29016764ea5cfbcdfeef36b?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    name: "Honeymad",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/52bdef44b6b70aeb39adca5515277f01d98dcb95d13f0b385725cf84a2ca2db1?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    name: "DEADP47",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/82b98ac64e839a37e9847470577d7035e79b640c0393d3e3fc4d197b16fbea5c?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    name: "GSTV",
  },
];

const InternetMentions = () => {
  return (
    <section className="mt-28 max-md:mt-10">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/d8fea7d95a058996310562be2e7c1cab035b0fceb2d110b67a721c9c2a444dc6?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        alt="Mentions icon"
        className="object-contain mt-28 rounded-none aspect-square w-[50px] max-md:mt-10"
      />
      <h2 className="mt-3.5 text-5xl font-bold leading-10 text-center text-white w-[484px] max-md:max-w-full">
        Нас часто упоминают в интернетах
      </h2>
      <div className="flex flex-wrap gap-2.5 self-stretch mt-16 w-full text-lg font-semibold leading-none text-white whitespace-nowrap max-md:mt-10 max-md:max-w-full">
        {mentions.map((mention, index) => (
          <MentionCard key={index} {...mention} />
        ))}
      </div>
    </section>
  );
};

export default InternetMentions;
