/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Footer from "./Footer";

const Layout = ({ children }) => {
  return (
    <div className="flex overflow-hidden flex-col items-center pb-80 bg-neutral-900 max-md:pb-24">
      <Header />
      <main>{children}</main>
      <Footer />
    </div>
  );
};

export default Layout;
