/**
 * This code was generated by Builder.io.
 */
import React from "react";

const MentionCard = ({ image, name }) => {
  return (
    <div className="flex relative flex-col flex-1 rounded-3xl aspect-[0.626]">
      <img
        loading="lazy"
        src={image}
        alt={`${name}'s mention`}
        className="object-cover absolute inset-0 size-full"
      />
      <div className="flex relative gap-4 items-start px-2.5 pt-96 pb-5 rounded-3xl max-md:pt-24">
        <img
          loading="lazy"
          src={``}
          // src={`http://b.io/ext_${70 + mentions.indexOf({ image, name })}-`}
          alt={`${name}'s avatar`}
          className="object-contain shrink-0 aspect-square rounded-[100px] w-[50px]"
        />
        <div className="grow shrink mt-3 w-[178px]">{name}</div>
      </div>
    </div>
  );
};

export default MentionCard;
