/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ImageCard from "./ImageCard";
import InfoCard from "./InfoCard";
import SubscribeSection from "./SubscribeSection";
import GameSection from "./GameSection";

const PlayStationSection = () => {
  const accountInfoItems = [
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/42ea9eb3aaa9d34137c9bb8ee14e5da9e02811adf5c1c9db84e146edda08f05c?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
      alt: "Clock Icon",
      text: "От 2-х до 4-х часов у тебя будет доступ к твоему аккаунту",
    },
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/740a74bdc6fc80d99240345428d24494970ef59443965237bfa973ddb52f70e6?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
      alt: "Security Icon",
      text: "После покупки ты можешь поменять все данные и подключить 2FA",
    },
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/ac962a161047ad6b755a32fed8ac16560b918d656594587b7b812b0dabd5e9f7?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
      alt: "Link Icon",
      text: "Поможем связать старый и новый аккаунты",
    },
  ];

  const subscriptionItems = [
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/ac975a27a4635d15317902f762f75a9aeadcc25a5cd48ec6e318b2f57a7fa3dc?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
      alt: "Check Icon",
      text: "Продлим старую или оформим новую на твою почту",
    },
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/393c558787648f4145a17db2796304c7acdab096aab7a353e8a2dbadc8234207?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
      alt: "Credit Card Icon",
      text: "Ты можешь подключить автоматические платежи",
    },
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/aa54bf6553acc7ad560508b995d3576362fad7250d5415d97859c25fbe819627?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
      alt: "Reminder Icon",
      text: "Напомним, когда подписка закончится",
    },
  ];

  const gameItems = [
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/3eba67490c11385781bfd1c1284687307ffb61984ad80db111d9b6abf0e70d77?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
      alt: "Controller Icon",
      text: "Полная интеграция с каталогом Sony включая: игры, подписки, дополнения, наборы оружия и внутриигровой валюты",
    },
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/b9b005104a399fa779e395401286c87d5b7048b0b56f8580576ca7ea2a9e63aa?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
      alt: "Discount Icon",
      text: "Ежедневное обновление цен и актуальных скидок на все товары",
    },
  ];

  return (
    <main className="flex flex-col rounded-none mt-24 h-[2011px]">
      <section className="flex flex-col items-center pb-10 w-full rounded-[40px] max-md:px-5 max-md:pb-24 max-md:max-w-full">
        <ImageCard
  src="/img/pssec.png"  // Замените на путь к изображению в папке public
  alt="Background Image"
        >
          <div className="flex relative flex-col mb-0 w-full max-w-[962px] max-md:mb-2.5 max-md:max-w-full max-md:text-4xl max-md:leading-10">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/355a9538207805d0871fe24e250c2546dd23aeb1bcdddc06c0d6725a6548b239?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt="Logo"
              className="object-contain self-center rounded-none aspect-square w-[90px]"
            />
            <div className="mt-5 max-md:max-w-full max-md:text-4xl max-md:leading-10">
              Мы собрали все для Sony PlayStation в одном месте
            </div>
          </div>
        </ImageCard>
        <section className="z-10 mt-0 w-full max-w-[1131px] max-md:max-w-full mt-[400px]">
          <div className="flex gap-5 max-md:flex-col">
            <aside className="flex flex-col w-3/5 max-md:ml-0 max-md:w-full">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/80c91423e867bff7756f5c730763978cd5002854190769bf01f585f9dfbba1e6?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
                alt="User Account"
                className="object-contain grow w-full rounded-none aspect-[1.38] max-md:mt-10 max-md:max-w-full"
              />
            </aside>
            <aside className="flex flex-col ml-5 w-2/5 max-md:ml-0 max-md:w-full">
              <InfoCard
                title="Завести аккаунт"
                description="Команда Game Propaganda поможет тебе оформить аккаунт Sony Playstation"
                items={accountInfoItems}
              />
            </aside>
          </div>
        </section>
      </section>
      <SubscribeSection
        title="Оформить подписку"
        description="Команда Game Propaganda поможет тебе оформить подписку Sony Playstation"
        items={subscriptionItems}
        image={{
          src: "https://cdn.builder.io/api/v1/image/assets/TEMP/2c2a7de7862aadeb7ac8f1ab344951c2b6c04ba6d250385b356d7c971814a6fa?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
          alt: "Subscription",
        }}
      />
      <GameSection
        title="Выбрать игру"
        description="Каталог Game Propaganda включает в себя все игры, дополнения и новинки, которые появляются в официальном каталоге Sony"
        listItems={gameItems}
        imageSource="https://cdn.builder.io/api/v1/image/assets/TEMP/257b6a16fc73e8adc0858a85118c1e83fe73779a2e138c1736aa56697912f631?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
      />
    </main>
  );
};

export default PlayStationSection;
