/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ProductCard from "./ProductCard";

const products = [
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/1db612b45ac8aea299ffa9be53fb7116a8c8f7f733e77088ceb12e4fe9ec6b16?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Star Wars Outlaws",
    price: "9 490 ₽",
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/23fdcc02a6edebcef5667085442387b3e1318ecc3a0a9486aabc96b98f178b53?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/4ee7bdf7c3ba4327304c3aa712708bba8a6abab3f2cfdb4e3be174ebd82e3ac3?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Death's Door",
    price: "2 690 ₽",
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/9c4d009d02bd4f6a4042ed8b88c8e8043c4e855e7d0f442fb1e8859f83bb60b1?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/5687194c40331e1940902bea5c033a5d6cbba8302e742a00fb92643f1eb10e11?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "God of War Ragnarök",
    price: "9 490 ₽",
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/f701ba37823f725343f081f508ce7e4f336021777b85eeed22564f435efaa7ba?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/3bb9524df9041f0cf641ecddfbde79500c6faaab6e786c55a20f9b32eb1e29a5?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    title: "Doki Doki Literature Club Plus!",
    price: "1 290 ₽",
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/23fdcc02a6edebcef5667085442387b3e1318ecc3a0a9486aabc96b98f178b53?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
  },
];

const PlayersChoice = () => {
  return (
    <section className="mt-24 w-full max-w-[1252px] max-md:mt-10 max-md:max-w-full mx-auto">
      <h2 className="text-5xl font-bold tracking-normal leading-none text-center text-white">
        Выбор игроков
      </h2>
      <div className="flex gap-5 mt-12 max-md:flex-col max-md:mt-10">
        {products.map((product, index) => (
          <ProductCard key={index} {...product} />
        ))}
      </div>
    </section>
  );
};

export default PlayersChoice;
