/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ProductCard = ({ image, title, price, icon }) => {
  return (
    <div className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full">
      <div className="flex overflow-hidden flex-col px-2 pt-2 pb-5 mx-auto w-full rounded-3xl bg-neutral-800 max-md:mt-5">
        <div className="flex overflow-hidden flex-col items-center rounded-xl aspect-square bg-zinc-800">
          <img
            loading="lazy"
            src={image}
            alt={title}
            className="object-contain w-full aspect-square"
          />
        </div>
        <div className="flex gap-5 justify-between mt-3 text-neutral-200 max-md:mx-2">
          <div className="flex flex-col">
            <div className="text-base font-medium leading-loose whitespace-nowrap text-ellipsis">
              {title}
            </div>
            <div className="gap-2.5 self-start mt-14 text-2xl font-semibold leading-none max-md:mt-10">
              {price}
            </div>
          </div>
          <img
            loading="lazy"
            src={icon}
            alt="Product icon"
            className="object-contain shrink-0 self-start mt-1 w-5 aspect-square"
          />
        </div>
      </div>
    </div>
  );
};

export default ProductCard;
