/**
 * This code was generated by Builder.io.
 */
import React from "react";

const PromotionCard = () => (
  <div className="flex flex-col self-stretch text-sm text-center text-white w-[284px]">
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/165c9a952fdf2965be38d273338e8eadd908b1fc0bae1c430564db656ef2d0cc?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
      alt="Promotion image"
      className="object-cover w-full rounded-none aspect-[0.65] max-w-[419px]"
    />
    {/* <button className="overflow-hidden gap-2.5 self-stretch px-5 py-3.5 mt-5 border border-white border-solid min-h-[50px] rounded-[100px]">
      Смотреть все акции
    </button> */}
  </div>
);

export default PromotionCard;
