/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FeatureSection from "./FeatureSection";

function ServiceHighlight() {
  const featureGroups = [
    [
      { emoji: "💬", text: "2000 Положительных отзывов" },
      { emoji: "💻", text: "Работа 24/7" },
      { emoji: "💳", text: "Официальные платежи" },
      { emoji: "🧑‍💻", text: "Офигенский личный кабинет" },
    ],
    [
      { emoji: "🫶", text: "Заботливый сервис" },
      { emoji: "🤩", text: "Пожизненная гарантия" },
      { emoji: "📜", text: "Прозрачная публичная оферта" },
      { emoji: "👾", text: "Большое коммьюнити из 15к человек" },
    ],
    [
      { emoji: "🎮", text: "Самый большой каталог игр в России" },
      { emoji: "🧑", text: "Поддержка 200 блогеров" },
      { emoji: "🚀", text: "Индивидуальный подход" },
    ],
  ];

  return (
    <section className="flex flex-col items-center mx-auto text-white rounded-none max-w-[1228px] mt-24">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/2960845de16aa759817c27788dd26d5a221f3382c3c4093c66b0839d6c07d61b?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        className="object-contain aspect-square fill-lime-400 w-[91px]"
        alt="Service logo"
      />
      <h1 className="mt-8 text-6xl font-black text-center leading-[61px] max-md:max-w-full max-md:text-4xl max-md:leading-10">
        Мы создали сервис, которым пользуемся сами
      </h1>
      {featureGroups.map((features, index) => (
        <FeatureSection key={index} features={features} />
      ))}
    </section>
  );
}

export default ServiceHighlight;
