/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ServiceIcon = ({ icon, text }) => {
  return (
    <div className="flex flex-col">
      <img
        loading="lazy"
        src={icon}
        alt={text}
        className="object-contain self-center aspect-square w-[34px]"
      />
      <div className="mt-2.5">
        {text.split(" ").map((word, index) => (
          <React.Fragment key={index}>
            {word}
            <br />
          </React.Fragment>
        ))}
      </div>
    </div>
  );
};

export default ServiceIcon;
