/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SocialIcon = ({ src, alt }) => {
  return (
    <img
      loading="lazy"
      src={src}
      alt={alt}
      className="object-contain shrink-0 aspect-square w-[38px]"
    />
  );
};

export default SocialIcon;
