/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SubscribeSection = ({ title, description, items, image }) => (
  <section className=" ml-[159px] w-full max-w-[1116px] max-md:mt-10 max-md:max-w-full z-[10]">
    <div className="flex gap-5 max-md:flex-col">
      <aside className="flex flex-col w-[39%] max-md:ml-0 max-md:w-full">
        <article className="flex flex-col self-stretch my-auto w-full text-lg text-white max-md:mt-10">
          <h2 className="self-start text-4xl font-bold leading-none">
            {title}
          </h2>
          <p className="self-start mt-8 leading-7">{description}</p>
          {items.map((item, index) => (
            <div className="flex gap-5 mt-4 leading-6" key={index}>
              <img
                loading="lazy"
                src={item.image}
                alt={item.alt}
                className="object-contain shrink-0 self-start w-6 aspect-square"
              />
              <div className="flex-auto">{item.text}</div>
            </div>
          ))}
        </article>
      </aside>
      <aside className="flex flex-col ml-5 w-[61%] max-md:ml-0 max-md:w-full">
        <img
          loading="lazy"
          src={image.src}
          alt={image.alt}
          className="object-contain grow w-full rounded-none aspect-[1.38] max-md:mt-10 max-md:max-w-full"
        />
      </aside>
    </div>
  </section>
);

export default SubscribeSection;
