/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ViewAllPromotions = () => {
  return (
<div className="flex justify-center">
  <button className="mx-auto overflow-hidden gap-2.5 px-5 py-3.5 mt-5 text-sm font-medium leading-loose text-center text-white border border-white border-solid min-h-[50px] rounded-[100px] w-[284px]">
    Смотреть все акции
  </button>
</div>

  );
};

export default ViewAllPromotions;
