/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ServiceSection from "./ServiceSection";
import FeatureList from "./FeatureList";

const accountFeatures = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/950e1e519f1ba0ce7ad86835afe96af913fae1dd1bec77e13a35c39d924b0583?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    text: "От 2-х до 4-х часов у тебя будет доступ к твоему аккаунту",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/9e69d213924e5b89254caeed1bcc2f30ea1fc07b3208a19426e2a05911175a0a?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    text: "После покупки ты можешь поменять все данные и подключить 2FA",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/b8e0ef3c2a3774f7fff726aabc9d0c634229ff5a42a18e8e1adcf3a37d95251d?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    text: "Низкие цены на игры и подписку",
  },
];

const subscriptionFeatures = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/80bc988ac3ab5b1c3a89c031690b7fbb2215921e9bc3e43955ac1a792a7fdb4e?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    text: "Продлим старую или оформим новую на твою почту",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/386b46c82b86c9615603badb3cc03898b830b0f2e4aae304d145f2f7bc95975f?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    text: "Ты можешь подключить автоматические платежи",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/53a3413d9d570dbceebfafb4c1d9b871c8f1494d796c20300317877d06a9b567?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    text: "Напомним, когда подписка закончится",
  },
];

const gameFeatures = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/f32c31968f1bbc83dd0271c32488a9e5a5c0f32759af49cc9a7fd54ba9ca218f?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    text: "Полная интеграция",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/4fe0bbc011a2dc11c975cfdbb7b702d293568c3d19e366e6b8ab5d8f31e601f6?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    text: "Самый большой каталог",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/4fd1634e382b72c368aff9b27d7cd4e6d9dfc257539e1413431022694b549975?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c",
    text: "Ежедневное обновление",
  },
];

function XboxSection() {
  return (
    <main className="flex flex-col rounded-none">
      <section className="flex flex-col items-center ml-5 mt-5 px-20 pb-32 w-full rounded-[40px] max-md:px-5 max-md:pb-24 max-w-[1400px]"   style={{ backgroundImage: "url('/img/xboxsec.png')", backgroundSize: "cover", backgroundPosition: "center" }}
      >
        <header className="flex relative flex-col justify-center items-center px-20 py-28 w-full text-6xl font-black text-center text-white leading-[61px] max-w-[1205px] min-h-[460px] max-md:px-5 max-md:py-24 max-md:max-w-full max-md:text-4xl max-md:leading-10">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/dad0352c8b7b74f865c53c53677865d438458736ad9476d850e8b82d10091f76?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
            alt=""
            className="object-cover absolute inset-0 size-full"
          />
          <div className="flex relative flex-col mb-0 max-w-full w-[649px] max-md:mb-2.5 max-md:text-4xl max-md:leading-10">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/cd0fe115d3fbb85c451518e3a477f750655366dce3fb36948291ed36cec4f0b1?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
              alt="Xbox logo"
              className="object-contain self-center rounded-none aspect-square w-[90px]"
            />
            <h1 className="mt-5 max-md:max-w-full max-md:text-4xl max-md:leading-10">
              ... и провернули тоже самое для Xbox
            </h1>
          </div>
        </header>

        <ServiceSection
          title="Завести аккаунт"
          description="Команда Game Propaganda поможет тебе оформить аккаунт XBOX"
          imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/2029e6932ae2df7db1929033dc0ec902b835133a7579116a3723726c43b4fb4a?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          imageAlt="Xbox account setup illustration"
          features={accountFeatures}
          imageFirst={false}
        />

        <ServiceSection
          title="Оформить подписку"
          description="Команда Game Propaganda поможет тебе оформить подписку GAME PASS"
          imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/37efe667df47a4fdfb3b02965a1f325da12616cd1a22952aab8276cd33bed861?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          imageAlt="Xbox Game Pass subscription illustration"
          features={subscriptionFeatures}
          imageFirst={true}
        />

        <ServiceSection
          title="Купить игру"
          description="Менеджеры Game Propaganda помогут тебе купить любую игру, которая есть на официальном сайте XBOX"
          imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/257b6a16fc73e8adc0858a85118c1e83fe73779a2e138c1736aa56697912f631?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          imageAlt="Xbox game purchase illustration"
          features={gameFeatures}
          imageFirst={false}
        />
      </section>
    </main>
  );
}

export default XboxSection;
