/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Layout from "../components/Layout";
import Hero from "../components/Hero";
import HowItWorks from "../components/HowItWorks";
import TurkishRegion from "../components/TurkishRegion";
import PSPlusSection from "../components/PSPlusSection";
import PSTariffs from "../components/PSTariffs";
import GameCatalog from "../components/GameCatalog";
import PlaystationTopUp from "../components/PlaystationTopUp";
import MonthlyGames from "../components/MonthlyGames";
import NewGamesInCatalog from "../components/NewGamesInCatalog";
import Guarantees from "../components/Guarantees";
import FAQ from "../components/FAQ";
import Testimonials from "../components/Testimonials";
import Newsletter from "../components/Newsletter";

function HomePage() {
  return (
    <Layout>
      <Hero />
      <HowItWorks />
      <TurkishRegion />
      <PSPlusSection />
      <PSTariffs />
      <GameCatalog />
      <PlaystationTopUp />
      <MonthlyGames />
      <NewGamesInCatalog />
      <Guarantees />
      <FAQ />
      <Testimonials />
      <Newsletter />
    </Layout>
  );
}

export default HomePage;
